import type { ChainNode } from '@/db/repositories/chain.repo';

export type ExportLang = 'python' | 'javascript';

// ── Python export ─────────────────────────────────────────────────────────────

function escapePython(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
}

export function exportPython(chainTitle: string, nodes: ChainNode[]): string {
  const nodeSteps = nodes
    .map((n, i) => {
      const content = escapePython(n.content_md || n.title || `Step ${i + 1}`);
      return `    """${content}""",`;
    })
    .join('\n');

  return `"""
Prompt Chain: ${chainTitle}
Generated by PromptBase — https://promptbase.app
"""

import anthropic

client = anthropic.Anthropic(api_key="YOUR_ANTHROPIC_API_KEY")

# Chain steps — use {{prev_output}} to reference the previous step's output
nodes = [
${nodeSteps}
]

MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 2048

def run_chain() -> list[str]:
    outputs: list[str] = []
    prev_output = ""

    for i, prompt_template in enumerate(nodes):
        # Inject previous output into the prompt
        prompt = prompt_template.replace("{{prev_output}}", prev_output)

        print(f"\\n{'='*60}")
        print(f"Step {i + 1}/{len(nodes)}")
        print(f"{'='*60}")

        message = client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            messages=[{"role": "user", "content": prompt}],
        )

        output = message.content[0].text
        outputs.append(output)
        prev_output = output

        print(output)

    return outputs


if __name__ == "__main__":
    run_chain()
`;
}

// ── JavaScript (Node.js) export ───────────────────────────────────────────────

function escapeJs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
}

export function exportJavaScript(chainTitle: string, nodes: ChainNode[]): string {
  const nodeSteps = nodes
    .map((n, i) => {
      const content = escapeJs(n.content_md || n.title || `Step ${i + 1}`);
      return `  \`${content}\`,`;
    })
    .join('\n');

  return `/**
 * Prompt Chain: ${chainTitle}
 * Generated by PromptBase — https://promptbase.app
 */

import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic({ apiKey: "YOUR_ANTHROPIC_API_KEY" });

// Chain steps — use {{prev_output}} to reference the previous step's output
const nodes = [
${nodeSteps}
];

const MODEL = "claude-haiku-4-5-20251001";
const MAX_TOKENS = 2048;

async function runChain() {
  const outputs = [];
  let prevOutput = "";

  for (let i = 0; i < nodes.length; i++) {
    // Inject previous output into the prompt
    const prompt = nodes[i].replace(/\\{\\{prev_output\\}\\}/g, prevOutput);

    console.log(\`\\n${"=".repeat(60)}\`);
    console.log(\`Step \${i + 1}/\${nodes.length}\`);
    console.log("=".repeat(60));

    const message = await client.messages.create({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      messages: [{ role: "user", content: prompt }],
    });

    const output = message.content[0].text;
    outputs.push(output);
    prevOutput = output;

    console.log(output);
  }

  return outputs;
}

runChain().catch(console.error);
`;
}

// ── Unified export ────────────────────────────────────────────────────────────

export function generateExport(
  lang: ExportLang,
  chainTitle: string,
  nodes: ChainNode[],
): string {
  return lang === 'python'
    ? exportPython(chainTitle, nodes)
    : exportJavaScript(chainTitle, nodes);
}
