-- Migration: 200 high-quality prompts — Part 2: Writing (50 prompts)
-- Date: 2026-06-11

INSERT INTO public.system_templates (title, description, category, difficulty, tags, blocks, variables, content_md, ai_score, fork_count, is_featured, order_index) VALUES

('SEO Blog Post Writer',
 'Pisze zoptymalizowane pod SEO posty blogowe z nagłówkami i CTA.',
 'writing', 'beginner',
 ARRAY['blog','seo','content-marketing','copywriting'],
 '[{"id":"1","content":"You are an experienced SEO content writer who creates engaging, well-structured blog posts that rank on Google and convert readers into customers.","order_index":0,"section_slug":"role"},{"id":"2","content":"Topic: {{topic}}\nTarget keyword: {{keyword}}\nAudience: {{audience}}\nWord count: {{word_count}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write a complete blog post with: H1 title (including keyword), engaging introduction with hook, 5-7 H2 sections with practical content, bullet points and examples, internal link suggestions, FAQ section (3 questions), compelling CTA, and SEO meta description (155 chars).","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat posta","defaultValue":""},{"name":"keyword","type":"text","label":"Słowo kluczowe","defaultValue":""},{"name":"audience","type":"text","label":"Docelowi czytelnicy","defaultValue":"marketing professionals"},{"name":"word_count","type":"text","label":"Liczba słów","defaultValue":"1500"}]'::jsonb,
 '## Role\nSEO content writer.\n\n## Topic\n{{topic}} targeting keyword: {{keyword}}\n\n## Task\nFull blog post with H1-H2 structure, FAQ, CTA, meta description.',
 87, 45, true, 200),

('Email Newsletter Creator',
 'Tworzy angażujące newslettery emailowe z wysokim CTR.',
 'writing', 'intermediate',
 ARRAY['email','newsletter','copywriting','marketing'],
 '[{"id":"1","content":"You are an email marketing specialist who writes newsletters that get opened, read, and clicked with compelling subject lines and clear value propositions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Newsletter topic: {{topic}}\nBrand voice: {{voice}}\nSubscribers: {{subscribers}}\nMain CTA: {{cta}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create: 1) 5 subject line variants with emojis and without 2) Preview text (90 chars) 3) Personalized greeting 4) Hook sentence 5) Main content (3 sections) 6) One primary CTA button 7) P.S. line 8) Unsubscribe-friendly footer note","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat newslettera","defaultValue":""},{"name":"voice","type":"text","label":"Głos marki","defaultValue":"professional yet friendly"},{"name":"subscribers","type":"text","label":"Segment subskrybentów","defaultValue":"SaaS founders"},{"name":"cta","type":"text","label":"Główne CTA","defaultValue":"Read full article"}]'::jsonb,
 '## Role\nEmail marketing specialist.\n\n## Topic\n{{topic}} for {{subscribers}}\n\n## Task\n5 subject lines, preview text, content sections, CTA, P.S.',
 86, 28, true, 201),

('LinkedIn Thought Leadership Article',
 'Pisze artykuły na LinkedIn budujące autorytet i zaangażowanie.',
 'writing', 'intermediate',
 ARRAY['linkedin','thought-leadership','personal-branding','b2b'],
 '[{"id":"1","content":"You are a LinkedIn content strategist who writes thought leadership posts that generate thousands of impressions, comments, and profile views.","order_index":0,"section_slug":"role"},{"id":"2","content":"Topic/insight: {{insight}}\nAuthor background: {{background}}\nIndustry: {{industry}}\nGoal: {{goal}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write a LinkedIn article with: Provocative opening line (no ''I'' start), personal story or counter-intuitive insight, 3-5 key lessons with bold headers, specific numbers and examples, vulnerability moment, strong call-to-engagement question at end, optimal formatting with white space.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"insight","type":"text","label":"Główna myśl/insight","defaultValue":""},{"name":"background","type":"text","label":"Tło autora","defaultValue":"10 years in B2B sales"},{"name":"industry","type":"text","label":"Branża","defaultValue":"SaaS"},{"name":"goal","type":"text","label":"Cel posta","defaultValue":"establish expertise, generate leads"}]'::jsonb,
 '## Role\nLinkedIn content strategist.\n\n## Insight\n{{insight}}\n\n## Task\nThought leadership post with story, lessons, numbers, engagement hook.',
 88, 33, true, 202),

('Product Description Copywriter',
 'Pisze opisy produktów które sprzedają przez emocje i korzyści.',
 'writing', 'beginner',
 ARRAY['copywriting','e-commerce','product','conversion'],
 '[{"id":"1","content":"You are a conversion copywriter who writes product descriptions that focus on benefits over features, using sensory language and social proof triggers.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nKey features: {{features}}\nTarget buyer: {{buyer}}\nMain pain point solved: {{pain_point}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: 1) Headline (benefit-focused, under 10 words) 2) Subheadline with social proof hook 3) Opening paragraph (buyer transformation) 4) 5 bullet points (feature → benefit format) 5) Sensory description paragraph 6) Objection-handling sentence 7) Urgency-driven CTA 8) SEO-friendly 160-char meta description","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Nazwa produktu","defaultValue":""},{"name":"features","type":"text","label":"Główne cechy","defaultValue":""},{"name":"buyer","type":"text","label":"Docelowy kupujący","defaultValue":""},{"name":"pain_point","type":"text","label":"Rozwiązywany problem","defaultValue":""}]'::jsonb,
 '## Role\nConversion copywriter.\n\n## Product\n{{product}}\n\n## Task\nBenefit headline, bullets, sensory description, CTA, meta.',
 85, 38, true, 203),

('Press Release Writer',
 'Pisze profesjonalne informacje prasowe według standardów AP Style.',
 'writing', 'advanced',
 ARRAY['pr','press-release','journalism','corporate-communication'],
 '[{"id":"1","content":"You are a PR specialist with 15 years of experience writing press releases that get picked up by journalists, following AP Style and newsroom standards.","order_index":0,"section_slug":"role"},{"id":"2","content":"Announcement: {{announcement}}\nCompany: {{company}}\nQuote from: {{spokesperson}}\nRelease date: {{date}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write AP Style press release: FOR IMMEDIATE RELEASE header, compelling headline (active voice), dateline, lead paragraph (who/what/when/where/why), supporting paragraphs, executive quote, company boilerplate, ### end mark, contact information block.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"announcement","type":"textarea","label":"Ogłoszenie/news","defaultValue":""},{"name":"company","type":"text","label":"Nazwa firmy","defaultValue":""},{"name":"spokesperson","type":"text","label":"Osoba do cytatu","defaultValue":"CEO"},{"name":"date","type":"text","label":"Data publikacji","defaultValue":"FOR IMMEDIATE RELEASE"}]'::jsonb,
 '## Role\nPR specialist — AP Style press releases.\n\n## Announcement\n{{announcement}}\n\n## Task\nFull press release: headline, lead, quotes, boilerplate.',
 90, 15, false, 204),

('Technical White Paper',
 'Tworzy szczegółowe white papers techniczne dla decydentów B2B.',
 'writing', 'advanced',
 ARRAY['white-paper','b2b','technical-writing','thought-leadership'],
 '[{"id":"1","content":"You are a technical writer who creates compelling white papers that educate enterprise decision-makers and position your company as the expert solution.","order_index":0,"section_slug":"role"},{"id":"2","content":"Topic: {{topic}}\nTarget reader: {{reader}}\nCompany solution: {{solution}}\nLength: {{pages}} pages","order_index":1,"section_slug":"context"},{"id":"3","content":"Structure: Executive Summary, Problem Statement (with industry data), Technical Deep Dive, Case Study or Use Case, Solution Framework, Implementation Roadmap, ROI Analysis, Conclusion with next steps. Include citations format and sidebar callouts.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat white paper","defaultValue":""},{"name":"reader","type":"text","label":"Docelowy czytelnik","defaultValue":"CTO, VP Engineering"},{"name":"solution","type":"text","label":"Rozwiązanie firmy","defaultValue":""},{"name":"pages","type":"text","label":"Liczba stron","defaultValue":"12"}]'::jsonb,
 '## Role\nTechnical writer for B2B white papers.\n\n## Topic\n{{topic}}\n\n## Task\nFull white paper: exec summary, problem, deep dive, ROI, roadmap.',
 91, 12, false, 205),

('Case Study Writer',
 'Tworzy przekonujące case studies pokazujące wyniki i ROI klienta.',
 'writing', 'advanced',
 ARRAY['case-study','sales','social-proof','b2b-marketing'],
 '[{"id":"1","content":"You are a B2B content writer who creates compelling case studies using the Problem-Solution-Results framework that sales teams use to close deals.","order_index":0,"section_slug":"role"},{"id":"2","content":"Client: {{client}}\nIndustry: {{industry}}\nChallenge: {{challenge}}\nResults achieved: {{results}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Customer quote for title, challenge section (3 pain points), solution narrative (not a feature list), quantified results (% improvements, time/cost saved), client quote after results, sidebar with key metrics, next steps, and 3 related use cases.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"client","type":"text","label":"Klient","defaultValue":""},{"name":"industry","type":"text","label":"Branża klienta","defaultValue":""},{"name":"challenge","type":"textarea","label":"Wyzwanie klienta","defaultValue":""},{"name":"results","type":"text","label":"Osiągnięte wyniki","defaultValue":""}]'::jsonb,
 '## Role\nB2B case study writer.\n\n## Client\n{{client}} in {{industry}}\n\n## Task\nProblem-Solution-Results with quotes, metrics, sidebar.',
 89, 22, true, 206),

('Landing Page Copywriter',
 'Pisze teksty landing page z wysoką konwersją.',
 'writing', 'intermediate',
 ARRAY['landing-page','conversion','copywriting','cro'],
 '[{"id":"1","content":"You are a direct-response copywriter who writes high-converting landing pages using proven frameworks (PAS, AIDA, BAB) with psychological triggers.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product/service: {{product}}\nTarget audience: {{audience}}\nMain offer: {{offer}}\nPrice point: {{price}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write full landing page copy: Hero headline + subheadline, above-fold CTA, social proof strip (logos/numbers), 3 pain points (agitation), solution reveal, 5 feature-benefit pairs, testimonials (3 formats), FAQ objection handling, pricing anchor, final CTA with guarantee.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt/usługa","defaultValue":""},{"name":"audience","type":"text","label":"Docelowi odbiorcy","defaultValue":""},{"name":"offer","type":"text","label":"Główna oferta","defaultValue":""},{"name":"price","type":"text","label":"Cena","defaultValue":""}]'::jsonb,
 '## Role\nDirect-response landing page copywriter.\n\n## Product\n{{product}}\n\n## Task\nFull LP: hero, pain points, benefits, testimonials, CTA, FAQ.',
 92, 47, true, 207),

('YouTube Video Script',
 'Pisze skrypty YouTube zoptymalizowane pod retencję i monetyzację.',
 'writing', 'intermediate',
 ARRAY['youtube','video-script','content-creation','engagement'],
 '[{"id":"1","content":"You are a YouTube scriptwriter who crafts videos that hook viewers in 30 seconds, maintain 70%+ retention, and drive subscriptions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Video topic: {{topic}}\nChannel niche: {{niche}}\nVideo length: {{length}}\nThumbnail concept: {{thumbnail}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: [HOOK - 30s] pattern interrupt opening, [INTRO - 30s] channel value prop, [BODY] 5-7 points with transitions and b-roll cues, [MID-ROLL CTA] at 40% mark, [OUTRO - 60s] summary, subscribe ask, next video teaser. Include timestamps and tone directions.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat wideo","defaultValue":""},{"name":"niche","type":"text","label":"Nisza kanału","defaultValue":"tech/productivity"},{"name":"length","type":"text","label":"Długość wideo","defaultValue":"10 minutes"},{"name":"thumbnail","type":"text","label":"Koncepcja miniatury","defaultValue":""}]'::jsonb,
 '## Role\nYouTube scriptwriter — retention-focused.\n\n## Topic\n{{topic}}\n\n## Task\nHook, intro, body with cues, mid-roll CTA, outro with subscribe.',
 87, 34, true, 208),

('Cold Outreach Email Sequence',
 'Tworzy sekwencje zimnych emaili B2B z wysokim wskaźnikiem odpowiedzi.',
 'writing', 'advanced',
 ARRAY['cold-email','outreach','sales','b2b'],
 '[{"id":"1","content":"You are a B2B sales copywriter who writes cold email sequences with 20%+ reply rates using the BASHO framework and pattern interrupts.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product/service: {{product}}\nIdeal customer profile: {{icp}}\nPain point addressed: {{pain}}\nValue proposition: {{value_prop}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write 5-email sequence: Email 1 (personalized BASHO opener, one insight, soft CTA), Email 2 (day 3, social proof, case study reference), Email 3 (day 7, different angle/pain point), Email 4 (day 14, last try, value-first), Email 5 (breakup email). Each under 100 words.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt/usługa","defaultValue":""},{"name":"icp","type":"text","label":"Idealny profil klienta","defaultValue":"VP Sales at 50-500 person SaaS companies"},{"name":"pain","type":"text","label":"Główny problem klienta","defaultValue":""},{"name":"value_prop","type":"text","label":"Propozycja wartości","defaultValue":""}]'::jsonb,
 '## Role\nB2B cold email copywriter — BASHO framework.\n\n## Product\n{{product}}\n\n## Task\n5-email sequence: opener, social proof, pivot, value, breakup.',
 91, 29, true, 209),

('Cover Letter Generator',
 'Pisze spersonalizowane listy motywacyjne dopasowane do oferty pracy.',
 'writing', 'beginner',
 ARRAY['cover-letter','job-search','career','hr'],
 '[{"id":"1","content":"You are a career coach and hiring manager who writes cover letters that get candidates to the interview stage by matching skills to job requirements.","order_index":0,"section_slug":"role"},{"id":"2","content":"Job title: {{job_title}}\nCompany: {{company}}\nKey requirements: {{requirements}}\nApplicant''s top 3 achievements: {{achievements}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write a 3-paragraph cover letter: Opening (specific company hook, not generic), Middle (3 achievement-to-requirement matches with metrics), Closing (mutual value, confident ask). Under 300 words, no clichés (''I am passionate about...''), ATS-friendly keywords.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"job_title","type":"text","label":"Stanowisko","defaultValue":""},{"name":"company","type":"text","label":"Firma","defaultValue":""},{"name":"requirements","type":"text","label":"Kluczowe wymagania","defaultValue":""},{"name":"achievements","type":"text","label":"Top 3 osiągnięcia kandydata","defaultValue":""}]'::jsonb,
 '## Role\nCareer coach writing cover letters.\n\n## Position\n{{job_title}} at {{company}}\n\n## Task\n3 paragraphs: company hook, achievement matches, confident close.',
 84, 52, true, 210),

('Executive Summary Writer',
 'Tworzy zwięzłe podsumowania wykonawcze dla raportów i propozycji.',
 'writing', 'intermediate',
 ARRAY['executive-summary','business-writing','reports','leadership'],
 '[{"id":"1","content":"You are a business writer who creates concise executive summaries that help C-level executives make decisions without reading full documents.","order_index":0,"section_slug":"role"},{"id":"2","content":"Document type: {{document_type}}\nKey findings: {{findings}}\nRecommendation: {{recommendation}}\nAudience: {{audience}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write a 1-page executive summary: Situation (2 sentences), Complication (key problem), Key findings (3 bullets with data), Recommendation (specific action), Expected outcome (with metrics), Risk acknowledgment, Call to action.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"document_type","type":"text","label":"Typ dokumentu","defaultValue":"market analysis report"},{"name":"findings","type":"textarea","label":"Kluczowe ustalenia","defaultValue":""},{"name":"recommendation","type":"text","label":"Rekomendacja","defaultValue":""},{"name":"audience","type":"text","label":"Odbiorcy","defaultValue":"Board of Directors"}]'::jsonb,
 '## Role\nBusiness writer for executives.\n\n## Document\n{{document_type}}\n\n## Task\nSituation, complication, findings, recommendation, outcome, CTA.',
 88, 18, false, 211),

('Job Description Creator',
 'Pisze opisy stanowisk które przyciągają najlepszych kandydatów.',
 'writing', 'intermediate',
 ARRAY['job-description','hr','recruiting','employer-branding'],
 '[{"id":"1","content":"You are an HR copywriter who writes inclusive job descriptions that attract top talent by focusing on impact, growth, and culture over laundry-list requirements.","order_index":0,"section_slug":"role"},{"id":"2","content":"Role: {{role}}\nTeam: {{team}}\nMust-have skills: {{must_haves}}\nCompany culture: {{culture}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Compelling role headline, ''What you''ll do'' (impact-focused bullets), ''What you bring'' (5 must-haves, 3 nice-to-haves), ''What we offer'' (beyond salary), Company culture paragraph, Salary range, Diversity statement. Avoid jargon and gendered language.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"role","type":"text","label":"Stanowisko","defaultValue":""},{"name":"team","type":"text","label":"Zespół","defaultValue":""},{"name":"must_haves","type":"text","label":"Wymagane umiejętności","defaultValue":""},{"name":"culture","type":"text","label":"Kultura firmy","defaultValue":""}]'::jsonb,
 '## Role\nInclusive HR copywriter.\n\n## Role\n{{role}}\n\n## Task\nImpact-focused JD with must-haves, perks, culture, diversity statement.',
 85, 24, false, 212),

('Sales Email Sequence',
 'Tworzy sekwencje emaili sprzedażowych dla istniejących leadów.',
 'writing', 'advanced',
 ARRAY['sales','email-marketing','nurturing','conversion'],
 '[{"id":"1","content":"You are a sales email strategist who creates lead nurturing sequences that move prospects from interest to purchase through value-first education.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nLead source: {{lead_source}}\nSales cycle length: {{cycle}}\nMain objections: {{objections}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create 7-email nurture sequence over 14 days: Welcome + immediate value, Educational content, Social proof story, Pain agitation, Solution reveal, Objection handling, Final offer. Each email has: Subject line, preview text, body (under 150 words), CTA.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt","defaultValue":""},{"name":"lead_source","type":"text","label":"Źródło leada","defaultValue":"free trial signup"},{"name":"cycle","type":"text","label":"Długość cyklu sprzedaży","defaultValue":"14 days"},{"name":"objections","type":"text","label":"Główne obiekcje","defaultValue":"price, complexity, timing"}]'::jsonb,
 '## Role\nSales email strategist.\n\n## Product\n{{product}}\n\n## Task\n7-email nurture: welcome, education, proof, pain, solution, objections, offer.',
 90, 31, true, 213),

('Investor Pitch Narrative',
 'Tworzy przekonującą narrację dla prezentacji inwestorskich.',
 'writing', 'advanced',
 ARRAY['pitch-deck','startup','fundraising','storytelling'],
 '[{"id":"1","content":"You are a startup pitch coach who has helped companies raise $500M+, crafting narratives that make investors see a billion-dollar opportunity.","order_index":0,"section_slug":"role"},{"id":"2","content":"Startup: {{startup}}\nProblem: {{problem}}\nTraction: {{traction}}\nAsk: {{ask}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write pitch narrative covering: Hook (memorable problem stat), Villain (the problem personified), Hero''s journey (founder story), Market size (TAM/SAM/SOM with logic), Solution magic, Unfair advantage, Traction proof, Team credibility, Financial ask with use of funds, Vision (5-year moonshot).","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"startup","type":"text","label":"Startup","defaultValue":""},{"name":"problem","type":"text","label":"Problem do rozwiązania","defaultValue":""},{"name":"traction","type":"text","label":"Trakcja","defaultValue":""},{"name":"ask","type":"text","label":"Kwota i cel rundy","defaultValue":""}]'::jsonb,
 '## Role\nStartup pitch coach.\n\n## Startup\n{{startup}}\n\n## Task\nPitch narrative: hook, problem, solution, traction, ask, vision.',
 93, 26, true, 214),

('Brand Story Creator',
 'Pisze autentyczną historię marki według frameworku StoryBrand.',
 'writing', 'intermediate',
 ARRAY['brand-story','storytelling','brand-identity','marketing'],
 '[{"id":"1","content":"You are a brand strategist trained in Donald Miller''s StoryBrand framework, creating narratives where the customer is the hero and the brand is the guide.","order_index":0,"section_slug":"role"},{"id":"2","content":"Brand: {{brand}}\nCustomer hero: {{customer}}\nCustomer''s problem: {{problem}}\nBrand''s transformation promise: {{transformation}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write brand story using StoryBrand 7-part framework: Character (customer), Problem (external/internal/philosophical), Guide (your brand with empathy and authority), Plan (3-step simplicity), Call to Action (clear ask), Avoid failure, Achieve success. Include 3 platform variations: website hero, social bio, elevator pitch.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"brand","type":"text","label":"Nazwa marki","defaultValue":""},{"name":"customer","type":"text","label":"Kim jest klient-bohater","defaultValue":""},{"name":"problem","type":"text","label":"Problem klienta","defaultValue":""},{"name":"transformation","type":"text","label":"Obietnica transformacji","defaultValue":""}]'::jsonb,
 '## Role\nStoryBrand brand strategist.\n\n## Brand\n{{brand}}\n\n## Task\n7-part StoryBrand narrative for website, social, elevator pitch.',
 89, 19, false, 215),

('Twitter/X Thread Writer',
 'Tworzy wciągające wątki na Twitter/X z wysokim zasięgiem organicznym.',
 'writing', 'beginner',
 ARRAY['twitter','social-media','thread','content-creation'],
 '[{"id":"1","content":"You are a Twitter growth expert who writes viral threads that educate, entertain, and grow followings through strategic hook writing and value delivery.","order_index":0,"section_slug":"role"},{"id":"2","content":"Thread topic: {{topic}}\nMain insight/lesson: {{insight}}\nTarget audience: {{audience}}\nNumber of tweets: {{tweet_count}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write thread: Tweet 1 (curiosity hook + promise), Tweet 2-N-1 (numbered points, each standalone with example/stat), Tweet N-1 (counterintuitive twist), Tweet N (summary + follow ask + what''s next). Under 280 chars each, no hashtag spam, add emoji sparingly.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat wątku","defaultValue":""},{"name":"insight","type":"text","label":"Główna myśl","defaultValue":""},{"name":"audience","type":"text","label":"Odbiorcy","defaultValue":"founders, marketers"},{"name":"tweet_count","type":"text","label":"Liczba tweetów","defaultValue":"10"}]'::jsonb,
 '## Role\nTwitter thread writer — viral format.\n\n## Topic\n{{topic}}\n\n## Task\nHook tweet, numbered insights with examples, twist, follow CTA.',
 84, 41, true, 216),

('Technical Documentation Writer',
 'Tworzy dokumentację techniczną dla API, SDK i bibliotek.',
 'writing', 'intermediate',
 ARRAY['technical-writing','documentation','api','developer-experience'],
 '[{"id":"1","content":"You are a technical writer who creates documentation that developers love — clear, scannable, with working code examples and a brilliant getting-started experience.","order_index":0,"section_slug":"role"},{"id":"2","content":"What to document: {{subject}}\nPrimary audience: {{audience}}\nTech stack: {{stack}}\nKey concepts: {{concepts}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Quick Start (5-min success path), Conceptual overview with diagram description, API Reference (method signatures, params table, return values, errors), 3 complete code examples (beginner/intermediate/advanced), Troubleshooting FAQ, and Changelog entry format.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"subject","type":"text","label":"Co dokumentować","defaultValue":"REST API for user management"},{"name":"audience","type":"text","label":"Odbiorcy","defaultValue":"developers integrating our API"},{"name":"stack","type":"text","label":"Stack / języki","defaultValue":"Node.js, Python, cURL examples"},{"name":"concepts","type":"text","label":"Kluczowe koncepty","defaultValue":"authentication, pagination, webhooks"}]'::jsonb,
 '## Role\nTechnical writer for developers.\n\n## Subject\n{{subject}}\n\n## Task\nQuick start, API reference, code examples, troubleshooting.',
 88, 16, false, 217),

('Performance Review Template',
 'Tworzy konstruktywne oceny pracownicze z konkretnymi przykładami.',
 'writing', 'intermediate',
 ARRAY['performance-review','hr','feedback','management'],
 '[{"id":"1","content":"You are an HR manager and leadership coach who writes fair, growth-oriented performance reviews that motivate employees and document performance accurately.","order_index":0,"section_slug":"role"},{"id":"2","content":"Employee role: {{role}}\nReview period: {{period}}\nKey achievements: {{achievements}}\nDevelopment areas: {{development}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write review sections: Overall performance rating with justification, Top 3 achievements (STAR format), 2 development areas (with growth plan, not criticism), Leadership/collaboration examples, Goals for next period (SMART), Compensation recommendation language, Forward-looking vision.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"role","type":"text","label":"Stanowisko pracownika","defaultValue":"Senior Software Engineer"},{"name":"period","type":"text","label":"Okres oceny","defaultValue":"Q4 2025 / Annual 2025"},{"name":"achievements","type":"textarea","label":"Kluczowe osiągnięcia","defaultValue":""},{"name":"development","type":"textarea","label":"Obszary rozwoju","defaultValue":""}]'::jsonb,
 '## Role\nHR manager — performance reviews.\n\n## Employee\n{{role}}\n\n## Task\nSTAR achievements, growth plan, SMART goals, compensation language.',
 87, 20, false, 218),

('Grant Proposal Writer',
 'Pisze wnioski grantowe z przekonującą narracją i budżetem.',
 'writing', 'advanced',
 ARRAY['grant','nonprofit','funding','proposal'],
 '[{"id":"1","content":"You are a grant writer with a 70%+ success rate who understands what funders look for: clear need, measurable outcomes, and organizational credibility.","order_index":0,"section_slug":"role"},{"id":"2","content":"Organization: {{organization}}\nGrant type: {{grant_type}}\nProject: {{project}}\nBudget requested: {{budget}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write proposal sections: Executive Summary (1 page), Statement of Need (with data), Project Description (goals, activities, timeline), Evaluation Plan (SMART metrics), Organizational Capacity, Budget narrative, Sustainability plan, Community impact statement.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"organization","type":"text","label":"Organizacja wnioskująca","defaultValue":""},{"name":"grant_type","type":"text","label":"Typ grantu","defaultValue":"EU Horizon Europe"},{"name":"project","type":"text","label":"Opis projektu","defaultValue":""},{"name":"budget","type":"text","label":"Wnioskowany budżet","defaultValue":""}]'::jsonb,
 '## Role\nGrant writer — 70%+ success rate.\n\n## Project\n{{project}}\n\n## Task\nFull proposal: need, description, evaluation, capacity, sustainability.',
 92, 11, false, 219),

('Onboarding Email Sequence',
 'Tworzy sekwencję emaili powitalnych aktywującą nowych użytkowników.',
 'writing', 'intermediate',
 ARRAY['onboarding','email','saas','user-activation'],
 '[{"id":"1","content":"You are a SaaS growth specialist who designs onboarding email sequences that get users to their first ''aha moment'' within 7 days.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nAha moment: {{aha_moment}}\nKey features to show: {{features}}\nChurn risk signal: {{churn_signal}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write 6-email onboarding sequence: Day 0 (welcome + single next step), Day 1 (value-building tip), Day 3 (social proof + feature highlight), Day 5 (power feature introduction), Day 7 (check-in + help offer), Day 10 (inactive rescue or power user upgrade). Each with subject, body, CTA.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt SaaS","defaultValue":""},{"name":"aha_moment","type":"text","label":"Moment odkrycia wartości","defaultValue":"first successful integration"},{"name":"features","type":"text","label":"Kluczowe funkcje do pokazania","defaultValue":""},{"name":"churn_signal","type":"text","label":"Sygnał ryzyka odejścia","defaultValue":"no login after day 3"}]'::jsonb,
 '## Role\nSaaS onboarding specialist.\n\n## Product\n{{product}}\n\n## Task\n6-email sequence driving to aha moment, rescue for inactive users.',
 89, 27, true, 220),

('FAQ Section Generator',
 'Tworzy sekcje FAQ optymalizowane pod SEO i featured snippets.',
 'writing', 'beginner',
 ARRAY['faq','seo','content','customer-support'],
 '[{"id":"1","content":"You are a content strategist who writes FAQ sections that answer real customer questions, reduce support tickets, and rank for featured snippets.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product/service: {{product}}\nTop customer questions: {{questions}}\nTarget keyword cluster: {{keywords}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write 15-question FAQ: Group by theme (Getting Started, Pricing, Technical, Support), each answer under 50 words for featured snippet potential, include long-tail keyword naturally, add follow-up resource links, FAQ Schema markup (JSON-LD) for rich results.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt/usługa","defaultValue":""},{"name":"questions","type":"textarea","label":"Najczęstsze pytania klientów","defaultValue":""},{"name":"keywords","type":"text","label":"Klaster słów kluczowych","defaultValue":""}]'::jsonb,
 '## Role\nFAQ content strategist — SEO.\n\n## Product\n{{product}}\n\n## Task\n15 FAQs grouped by theme with schema markup for rich results.',
 83, 36, false, 221),

('App Store Description Writer',
 'Tworzy opisy aplikacji na App Store i Google Play z ASO.',
 'writing', 'intermediate',
 ARRAY['app-store','aso','mobile','copywriting'],
 '[{"id":"1","content":"You are an App Store Optimization (ASO) specialist who writes app descriptions that rank in searches and convert browsers to downloads.","order_index":0,"section_slug":"role"},{"id":"2","content":"App name: {{app_name}}\nCategory: {{category}}\nTop 3 features: {{features}}\nTarget users: {{users}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Short description (80 chars, keyword-dense), Long description (first 3 lines must hook before ''more'', feature bullets, social proof, privacy note), Keyword list (100 chars), Release notes template, and 5 screenshot caption suggestions.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"app_name","type":"text","label":"Nazwa aplikacji","defaultValue":""},{"name":"category","type":"text","label":"Kategoria","defaultValue":"Productivity"},{"name":"features","type":"text","label":"Top 3 funkcje","defaultValue":""},{"name":"users","type":"text","label":"Docelowi użytkownicy","defaultValue":""}]'::jsonb,
 '## Role\nASO specialist.\n\n## App\n{{app_name}}\n\n## Task\nShort desc, long desc (first 3 lines hook), keywords, screenshot captions.',
 86, 21, false, 222),

('Podcast Episode Script',
 'Pisze skrypty odcinków podcastów z naturalnym przepływem rozmowy.',
 'writing', 'intermediate',
 ARRAY['podcast','script','audio','content-creation'],
 '[{"id":"1","content":"You are a podcast producer and scriptwriter who creates engaging episode structures that maintain listener attention and deliver clear takeaways.","order_index":0,"section_slug":"role"},{"id":"2","content":"Episode topic: {{topic}}\nGuest (if any): {{guest}}\nPodcast style: {{style}}\nLength: {{length}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write episode structure: Cold open (30s hook), Host intro, Episode promise (what listener will learn), Main content (5 acts with transition phrases), Guest introduction script, 5 interview questions with follow-up probes, Mid-episode recap, Outro with next episode tease, Sponsor read template.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat odcinka","defaultValue":""},{"name":"guest","type":"text","label":"Gość (opcjonalnie)","defaultValue":"solo episode"},{"name":"style","type":"text","label":"Styl podcastu","defaultValue":"interview / educational"},{"name":"length","type":"text","label":"Długość odcinka","defaultValue":"45 minutes"}]'::jsonb,
 '## Role\nPodcast scriptwriter.\n\n## Topic\n{{topic}}\n\n## Task\nCold open, acts, interview questions, transition phrases, outro.',
 85, 17, false, 223),

('Content Calendar Creator',
 'Planuje miesięczny kalendarz treści dla wielu platform.',
 'writing', 'intermediate',
 ARRAY['content-strategy','social-media','editorial-calendar','marketing'],
 '[{"id":"1","content":"You are a content strategist who creates data-driven content calendars aligned with business goals, audience interests, and platform algorithms.","order_index":0,"section_slug":"role"},{"id":"2","content":"Brand: {{brand}}\nPlatforms: {{platforms}}\nContent pillars: {{pillars}}\nMonth/campaign: {{month}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create 30-day calendar with: Weekly content themes, Daily post schedule per platform, Content type mix (education 40%, entertainment 30%, promotion 20%, community 10%), Hook formulas for each type, Repurposing plan (long-form → micro-content), KPIs per content type.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"brand","type":"text","label":"Marka","defaultValue":""},{"name":"platforms","type":"text","label":"Platformy","defaultValue":"Instagram, LinkedIn, Twitter, Newsletter"},{"name":"pillars","type":"text","label":"Filary treści","defaultValue":""},{"name":"month","type":"text","label":"Miesiąc/kampania","defaultValue":"January 2026"}]'::jsonb,
 '## Role\nContent strategist.\n\n## Brand\n{{brand}} on {{platforms}}\n\n## Task\n30-day calendar: themes, schedule, content mix, repurposing plan.',
 87, 23, false, 224),

('Website About Page',
 'Pisze stronę O nas która buduje zaufanie i konwertuje odwiedzających.',
 'writing', 'intermediate',
 ARRAY['about-page','brand','website','storytelling'],
 '[{"id":"1","content":"You are a conversion copywriter who writes About pages that build trust, communicate unique value, and turn visitors into customers by making the company human.","order_index":0,"section_slug":"role"},{"id":"2","content":"Company: {{company}}\nFounded: {{founding_story}}\nMission: {{mission}}\nTeam size: {{team}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Origin story (''why we started''), Mission statement (what change you create), Values with proof (not just words), Team highlights (skills + human side), Social proof (customers, revenue, awards), Future vision, Personal invitation CTA. Under 600 words, conversational tone.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"company","type":"text","label":"Firma","defaultValue":""},{"name":"founding_story","type":"text","label":"Historia założenia","defaultValue":""},{"name":"mission","type":"text","label":"Misja","defaultValue":""},{"name":"team","type":"text","label":"Zespół","defaultValue":""}]'::jsonb,
 '## Role\nConversion copywriter — About pages.\n\n## Company\n{{company}}\n\n## Task\nOrigin story, mission, values with proof, team, vision, CTA.',
 86, 19, false, 225),

('Webinar Description & Promotion',
 'Tworzy opisy webinarów i teksty promocyjne zwiększające rejestracje.',
 'writing', 'intermediate',
 ARRAY['webinar','event','lead-generation','copywriting'],
 '[{"id":"1","content":"You are an event marketing specialist who writes webinar copy that creates FOMO and drives registrations through benefit-focused messaging.","order_index":0,"section_slug":"role"},{"id":"2","content":"Webinar topic: {{topic}}\nSpeaker(s): {{speakers}}\nDate/time: {{datetime}}\nTarget attendees: {{audience}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create: Webinar title (outcome-focused), 3 registration page variants (short/medium/long), 5 email subject lines, Social media announcement copy (LinkedIn + Twitter), Reminder email sequence (1 week, 1 day, 1 hour before), Post-webinar replay email.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat webinaru","defaultValue":""},{"name":"speakers","type":"text","label":"Prelegent(ci)","defaultValue":""},{"name":"datetime","type":"text","label":"Data i godzina","defaultValue":""},{"name":"audience","type":"text","label":"Docelowi uczestnicy","defaultValue":""}]'::jsonb,
 '## Role\nEvent marketing specialist.\n\n## Webinar\n{{topic}}\n\n## Task\nTitle, registration page, email sequence, social copy.',
 85, 14, false, 226),

('Thought Leadership Article',
 'Pisze artykuły eksperckie budujące autorytet w branży.',
 'writing', 'advanced',
 ARRAY['thought-leadership','content-marketing','expertise','pr'],
 '[{"id":"1","content":"You are a ghostwriter for C-level executives and industry experts, crafting thought leadership articles that get published in Forbes, HBR, and industry journals.","order_index":0,"section_slug":"role"},{"id":"2","content":"Author''s unique perspective: {{perspective}}\nIndustry trend to address: {{trend}}\nControversial take: {{controversial_take}}\nPublication target: {{publication}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write 1200-word article: Provocative title, Opening scene or statistic, Thesis (what others get wrong), 3 supporting arguments with evidence, Industry implications, Actionable recommendations, Vision of what''s possible, Author bio pitch.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"perspective","type":"textarea","label":"Unikalny punkt widzenia autora","defaultValue":""},{"name":"trend","type":"text","label":"Trend branżowy","defaultValue":""},{"name":"controversial_take","type":"text","label":"Kontrowersyjne stanowisko","defaultValue":""},{"name":"publication","type":"text","label":"Docelowa publikacja","defaultValue":"Forbes / Harvard Business Review"}]'::jsonb,
 '## Role\nGhostwriter for thought leaders.\n\n## Perspective\n{{perspective}}\n\n## Task\n1200-word article: provocative title, thesis, evidence, implications.',
 92, 17, true, 227),

('Product Launch Announcement',
 'Tworzy komunikaty o launchu produktu na wszystkie kanały.',
 'writing', 'intermediate',
 ARRAY['product-launch','marketing','announcement','pr'],
 '[{"id":"1","content":"You are a product marketing manager who orchestrates launch communications that build anticipation and drive first-day adoption.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nKey differentiator: {{differentiator}}\nLaunch date: {{launch_date}}\nPrimary channel: {{channel}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create launch package: Product name + tagline, Hero announcement email (day of), Social media posts for 5 platforms, Product Hunt launch copy, Press release headline + lead, Internal announcement for employees, Customer success team talking points.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt","defaultValue":""},{"name":"differentiator","type":"text","label":"Główny wyróżnik","defaultValue":""},{"name":"launch_date","type":"text","label":"Data launchu","defaultValue":""},{"name":"channel","type":"text","label":"Główny kanał","defaultValue":"email + Product Hunt"}]'::jsonb,
 '## Role\nProduct marketing manager.\n\n## Product\n{{product}}\n\n## Task\nLaunch package: email, social, Product Hunt, press release, talking points.',
 88, 26, true, 228),

('Customer Success Story',
 'Pisze anglojęzyczne success stories klientów dla celów sprzedażowych.',
 'writing', 'intermediate',
 ARRAY['customer-success','social-proof','case-study','sales'],
 '[{"id":"1","content":"You are a customer marketing specialist who turns client wins into compelling stories that resonate with prospects at every sales funnel stage.","order_index":0,"section_slug":"role"},{"id":"2","content":"Customer: {{customer}}\nBefore state: {{before}}\nAfter state: {{after}}\nKey metric: {{metric}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write 3-format success story: Long form (600 words, full narrative arc), Short form (150 words for website), Tweet/quote card version (140 chars). All include: emotional before/after, the turning point, specific metric, customer quote, and transferable lesson.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"customer","type":"text","label":"Klient","defaultValue":""},{"name":"before","type":"text","label":"Stan przed","defaultValue":""},{"name":"after","type":"text","label":"Stan po","defaultValue":""},{"name":"metric","type":"text","label":"Kluczowy wskaźnik","defaultValue":"40% reduction in time-to-close"}]'::jsonb,
 '## Role\nCustomer marketing specialist.\n\n## Customer\n{{customer}}\n\n## Task\n3 formats: long (600w), short (150w), tweet. All with metric + quote.',
 87, 18, false, 229),

('Partnership Proposal',
 'Tworzy propozycje współpracy dla partnerów biznesowych i strategicznych.',
 'writing', 'advanced',
 ARRAY['partnership','business-development','proposal','b2b'],
 '[{"id":"1","content":"You are a business development director who writes partnership proposals that create win-win scenarios and advance both parties'' strategic goals.","order_index":0,"section_slug":"role"},{"id":"2","content":"Our company: {{our_company}}\nProspective partner: {{partner}}\nPartnership type: {{type}}\nValue exchange: {{value}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write proposal: Executive summary (1 paragraph), Mutual opportunity analysis, Proposed collaboration model, Revenue/value split framework, GTM strategy, Success metrics, Pilot project suggestion, Legal/risk considerations, Next steps timeline.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"our_company","type":"text","label":"Nasza firma","defaultValue":""},{"name":"partner","type":"text","label":"Potencjalny partner","defaultValue":""},{"name":"type","type":"text","label":"Typ partnerstwa","defaultValue":"technology integration / reseller"},{"name":"value","type":"text","label":"Wymiana wartości","defaultValue":""}]'::jsonb,
 '## Role\nBusiness development director.\n\n## Partnership\n{{our_company}} × {{partner}}\n\n## Task\nProposal: opportunity, model, revenue split, GTM, metrics, pilot.',
 90, 13, false, 230),

('User Manual Writer',
 'Tworzy instrukcje obsługi i przewodniki użytkownika.',
 'writing', 'beginner',
 ARRAY['user-manual','technical-writing','documentation','ux-writing'],
 '[{"id":"1","content":"You are a UX writer and technical communicator who creates user manuals that help people succeed with products without frustration.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nUser skill level: {{skill_level}}\nKey tasks to cover: {{tasks}}\nFormat: {{format}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write manual sections: Quick Start guide (5 steps to first win), Feature reference (each feature with screenshots placeholders, steps, tips), Common workflows, Troubleshooting table, Glossary, Index. Use numbered steps, warning boxes, and tip callouts.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt","defaultValue":""},{"name":"skill_level","type":"text","label":"Poziom umiejętności użytkownika","defaultValue":"non-technical"},{"name":"tasks","type":"text","label":"Kluczowe zadania do opisania","defaultValue":""},{"name":"format","type":"text","label":"Format","defaultValue":"PDF / web-based help"}]'::jsonb,
 '## Role\nUX writer and technical communicator.\n\n## Product\n{{product}}\n\n## Task\nQuick start, feature reference, workflows, troubleshooting, glossary.',
 84, 15, false, 231),

('Changelog Writer',
 'Pisze notatki do wydań oprogramowania w przyjaznym użytkownikom stylu.',
 'writing', 'beginner',
 ARRAY['changelog','release-notes','product','communication'],
 '[{"id":"1","content":"You are a product writer who transforms technical git commits into user-friendly changelog entries that celebrate improvements and build product trust.","order_index":0,"section_slug":"role"},{"id":"2","content":"Version: {{version}}\nChanges (raw): {{changes}}\nProduct name: {{product}}\nRelease date: {{date}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write changelog entry: Version header with date, Emoji-categorized sections (✨ New, 🐛 Fixed, 💅 Improved, ⚡ Performance, 🔒 Security, 💥 Breaking), Each item: user benefit (not technical detail), upgrade note if breaking, link placeholders for docs. Also write tweet announcement.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"version","type":"text","label":"Wersja","defaultValue":"v2.5.0"},{"name":"changes","type":"textarea","label":"Lista zmian (surowe)","defaultValue":""},{"name":"product","type":"text","label":"Nazwa produktu","defaultValue":""},{"name":"date","type":"text","label":"Data wydania","defaultValue":""}]'::jsonb,
 '## Role\nProduct writer for changelogs.\n\n## Version\n{{version}} of {{product}}\n\n## Task\nUser-friendly changelog with emoji categories + tweet announcement.',
 83, 28, false, 232),

('Scholarship Essay Guide',
 'Pomaga napisać esej do wniosku stypendialnego który wyróżnia kandydata.',
 'writing', 'intermediate',
 ARRAY['scholarship','essay','education','college'],
 '[{"id":"1","content":"You are an admissions consultant who has helped hundreds of students win scholarships by crafting authentic, compelling essays that stand out to selection committees.","order_index":0,"section_slug":"role"},{"id":"2","content":"Scholarship: {{scholarship}}\nEssay prompt: {{prompt}}\nApplicant background: {{background}}\nKey message: {{message}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write the essay: Opening scene (in media res), connection to prompt (subtle, not direct), Personal transformation narrative, Specific example with details, Universal insight drawn from personal experience, Future vision tied to scholarship mission, Memorable closing that echoes opening. Under 650 words.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"scholarship","type":"text","label":"Stypendium","defaultValue":""},{"name":"prompt","type":"textarea","label":"Temat eseju","defaultValue":""},{"name":"background","type":"text","label":"Tło kandydata","defaultValue":""},{"name":"message","type":"text","label":"Główne przesłanie","defaultValue":""}]'::jsonb,
 '## Role\nAdmissions consultant.\n\n## Scholarship\n{{scholarship}}\n\n## Task\nEssay with opening scene, transformation arc, future vision, echo close.',
 88, 14, false, 233),

('Annual Report Summary',
 'Tworzy podsumowania raportów rocznych dostępne dla wszystkich interesariuszy.',
 'writing', 'advanced',
 ARRAY['annual-report','corporate','investor-relations','financial'],
 '[{"id":"1","content":"You are a corporate communications director who transforms dense annual reports into compelling narratives that engage investors, employees, and the public.","order_index":0,"section_slug":"role"},{"id":"2","content":"Company: {{company}}\nYear: {{year}}\nKey financials: {{financials}}\nMajor milestones: {{milestones}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: CEO letter to shareholders (authentic voice, honest about challenges), Year in numbers (infographic-ready stats), Strategic highlights (3-5 major wins), Innovation spotlight, Community impact section, Looking ahead (2-year vision), Financial performance narrative (non-accountant friendly).","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"company","type":"text","label":"Firma","defaultValue":""},{"name":"year","type":"text","label":"Rok","defaultValue":"2025"},{"name":"financials","type":"text","label":"Kluczowe dane finansowe","defaultValue":""},{"name":"milestones","type":"text","label":"Główne osiągnięcia","defaultValue":""}]'::jsonb,
 '## Role\nCorporate communications director.\n\n## Company\n{{company}} Annual Report {{year}}\n\n## Task\nCEO letter, year in numbers, strategy, community, financial narrative.',
 89, 10, false, 234),

('Meeting Agenda Creator',
 'Tworzy agendy spotkań z celami i oczekiwanymi wynikami.',
 'writing', 'beginner',
 ARRAY['meetings','productivity','business','leadership'],
 '[{"id":"1","content":"You are a facilitator and executive assistant who designs meeting agendas that respect participants'' time and always achieve clear outcomes.","order_index":0,"section_slug":"role"},{"id":"2","content":"Meeting type: {{meeting_type}}\nDuration: {{duration}}\nAttendees: {{attendees}}\nDesired outcome: {{outcome}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create agenda: Meeting purpose (1 sentence), Pre-read list (links/docs), Timed agenda items with owner and decision/discussion label, Parking lot section, Decision log template, Action items table (who/what/when), Follow-up email template. Include facilitator tips.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"meeting_type","type":"text","label":"Typ spotkania","defaultValue":"Quarterly strategy review"},{"name":"duration","type":"text","label":"Czas trwania","defaultValue":"90 minutes"},{"name":"attendees","type":"text","label":"Uczestnicy","defaultValue":"leadership team (8 people)"},{"name":"outcome","type":"text","label":"Oczekiwany wynik","defaultValue":"Q2 priorities aligned and assigned"}]'::jsonb,
 '## Role\nMeeting facilitator.\n\n## Meeting\n{{meeting_type}} ({{duration}})\n\n## Task\nAgenda with timebox, owners, decision log, action items, follow-up template.',
 82, 31, false, 235),

('Project Proposal Writer',
 'Pisze formalne propozycje projektowe z zakresem i kosztami.',
 'writing', 'intermediate',
 ARRAY['project-management','proposal','business','freelance'],
 '[{"id":"1","content":"You are a senior project manager and business consultant who writes winning project proposals that set clear expectations and win client approval.","order_index":0,"section_slug":"role"},{"id":"2","content":"Project type: {{project_type}}\nClient: {{client}}\nScope: {{scope}}\nTimeline: {{timeline}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write proposal: Executive summary, Problem statement, Proposed solution (methodology), Scope of work (in/out of scope table), Deliverables with acceptance criteria, Project timeline (milestones), Team and credentials, Investment (pricing table), Terms and payment schedule, Next steps.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"project_type","type":"text","label":"Typ projektu","defaultValue":"Website redesign"},{"name":"client","type":"text","label":"Klient","defaultValue":""},{"name":"scope","type":"text","label":"Zakres","defaultValue":""},{"name":"timeline","type":"text","label":"Harmonogram","defaultValue":"8 weeks"}]'::jsonb,
 '## Role\nSenior project manager.\n\n## Project\n{{project_type}} for {{client}}\n\n## Task\nFull proposal: scope table, deliverables, timeline, pricing, terms.',
 87, 22, false, 236),

('Welcome Email Sequence',
 'Tworzy sekwencję powitalną budującą lojalność od pierwszego kontaktu.',
 'writing', 'intermediate',
 ARRAY['email','welcome-sequence','retention','brand-voice'],
 '[{"id":"1","content":"You are an email copywriter specializing in relationship-building welcome sequences that turn new subscribers into loyal brand advocates.","order_index":0,"section_slug":"role"},{"id":"2","content":"Brand: {{brand}}\nLead magnet: {{lead_magnet}}\nBrand voice: {{voice}}\nUltimate offer: {{offer}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write 5-email welcome sequence: Email 1 (deliver lead magnet + founder story), Email 2 (biggest insight/lesson, day 2), Email 3 (social proof story, day 4), Email 4 (content upgrade, day 6), Email 5 (soft pitch with value stack, day 8). Each: subject, preview, body (200 words), CTA.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"brand","type":"text","label":"Marka","defaultValue":""},{"name":"lead_magnet","type":"text","label":"Lead magnet","defaultValue":"free guide / checklist"},{"name":"voice","type":"text","label":"Głos marki","defaultValue":"expert but approachable"},{"name":"offer","type":"text","label":"Główna oferta","defaultValue":""}]'::jsonb,
 '## Role\nRelationship-building email copywriter.\n\n## Brand\n{{brand}}\n\n## Task\n5-email welcome: lead magnet, story, proof, upgrade, soft pitch.',
 88, 24, false, 237),

('Testimonial Request Email',
 'Wysyła emaile z prośbą o recenzje i testimoniale od klientów.',
 'writing', 'beginner',
 ARRAY['testimonial','review','customer-success','social-proof'],
 '[{"id":"1","content":"You are a customer success manager who knows exactly how to ask for testimonials in a way that gets enthusiastic responses and useful quotes.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product/service: {{product}}\nCustomer segment: {{segment}}\nTiming: {{timing}}\nUse case for testimonial: {{use_case}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: 3 email variants (formal/casual/quick), Each with subject line, personalized opening, specific achievement reference, testimonial ask with format guide (3-4 sentences), easy yes/no option, thank you P.S. Also create: LinkedIn recommendation request, G2/Capterra review request, Video testimonial script guide.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt/usługa","defaultValue":""},{"name":"segment","type":"text","label":"Segment klientów","defaultValue":"power users, 6+ months"},{"name":"timing","type":"text","label":"Moment wysyłki","defaultValue":"after achieving milestone"},{"name":"use_case","type":"text","label":"Cel testimonialów","defaultValue":"website, sales decks"}]'::jsonb,
 '## Role\nCustomer success manager.\n\n## Product\n{{product}}\n\n## Task\n3 email variants + LinkedIn + review site + video testimonial guide.',
 83, 19, false, 238),

('Pricing Page Copy',
 'Pisze teksty strony cennikowej redukujące tarcie i zwiększające konwersje.',
 'writing', 'intermediate',
 ARRAY['pricing','saas','conversion','copywriting'],
 '[{"id":"1","content":"You are a SaaS pricing specialist who writes pricing pages that reduce friction, address value objections, and guide prospects to the right plan.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nPlans: {{plans}}\nTarget customer per plan: {{customers}}\nMain objection: {{objection}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Page headline (value, not features), Billing toggle copy (monthly/annual savings framing), Plan names and taglines, Feature table with help text, ''Most popular'' badge psychology, FAQ section (5 objection-handling questions), Trust signals (security badges, logos), Money-back guarantee copy, Enterprise inquiry CTA.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt SaaS","defaultValue":""},{"name":"plans","type":"text","label":"Plany cenowe","defaultValue":"Starter, Pro, Business, Enterprise"},{"name":"customers","type":"text","label":"Klient per plan","defaultValue":""},{"name":"objection","type":"text","label":"Główna obiekcja","defaultValue":"too expensive vs competitors"}]'::jsonb,
 '## Role\nSaaS pricing page specialist.\n\n## Product\n{{product}}\n\n## Task\nHeadline, plan names, feature table, FAQ, trust signals, guarantees.',
 89, 29, true, 239),

('Company Mission & Values',
 'Definiuje misję, wizję i wartości firmy w autentyczny i inspirujący sposób.',
 'writing', 'intermediate',
 ARRAY['brand','culture','mission-statement','values'],
 '[{"id":"1","content":"You are a brand strategist who helps companies articulate their purpose in a way that attracts customers who share their values and employees who are mission-driven.","order_index":0,"section_slug":"role"},{"id":"2","content":"Company: {{company}}\nWhat you do: {{what}}\nWho you serve: {{who}}\nChange you create: {{change}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Mission statement (1 sentence, action verb, audience, outcome), Vision statement (10-year aspirational future), 5 core values (name + 2-sentence behavior description), Purpose statement (why you exist beyond profit), Culture code highlights (3 principles with ''we'' statements), Origin story paragraph.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"company","type":"text","label":"Firma","defaultValue":""},{"name":"what","type":"text","label":"Co robisz","defaultValue":""},{"name":"who","type":"text","label":"Dla kogo","defaultValue":""},{"name":"change","type":"text","label":"Jaka zmiana w świecie","defaultValue":""}]'::jsonb,
 '## Role\nBrand strategist — purpose articulation.\n\n## Company\n{{company}}\n\n## Task\nMission, vision, 5 values, culture code, origin story.',
 88, 16, false, 240),

('Social Media Bio Writer',
 'Pisze angażujące biogramy na platformy społecznościowe.',
 'writing', 'beginner',
 ARRAY['social-media','bio','personal-branding','linkedin'],
 '[{"id":"1","content":"You are a personal branding specialist who writes social media bios that communicate value clearly and attract the right followers and opportunities.","order_index":0,"section_slug":"role"},{"id":"2","content":"Person: {{person}}\nProfession: {{profession}}\nUnique value: {{unique_value}}\nTarget audience: {{audience}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write optimized bios for: Twitter/X (160 chars), LinkedIn headline (220 chars) + About summary, Instagram (150 chars), TikTok (80 chars), Website bio (100 words). Each platform bio: unique hook for that audience, keywords for discoverability, personality, clear CTA or link.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"person","type":"text","label":"Imię i nazwisko","defaultValue":""},{"name":"profession","type":"text","label":"Zawód/rola","defaultValue":""},{"name":"unique_value","type":"text","label":"Unikalna wartość","defaultValue":""},{"name":"audience","type":"text","label":"Docelowi obserwatorzy","defaultValue":""}]'::jsonb,
 '## Role\nPersonal branding specialist.\n\n## Person\n{{person}} — {{profession}}\n\n## Task\nBios for Twitter, LinkedIn, Instagram, TikTok, website (platform-optimized).',
 82, 44, true, 241),

('Employee Handbook Section',
 'Pisze sekcje regulaminu pracowniczego w jasnym i ludzkim języku.',
 'writing', 'advanced',
 ARRAY['hr','employee-handbook','policy','culture'],
 '[{"id":"1","content":"You are an HR writer who translates corporate policies into human-readable text that employees actually read and follow.","order_index":0,"section_slug":"role"},{"id":"2","content":"Policy topic: {{topic}}\nCompany size: {{company_size}}\nCulture: {{culture}}\nLegal jurisdiction: {{jurisdiction}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write handbook section: Plain-language policy statement, ''Why this matters'' rationale, Step-by-step procedures, Examples of what is/isn''t acceptable, How to report concerns, Consequences explanation (progressive, not punitive), Manager guide sidebar, FAQ (5 questions), Legal disclaimer.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat polityki","defaultValue":"Remote work and flexible hours policy"},{"name":"company_size","type":"text","label":"Wielkość firmy","defaultValue":"50-200 employees"},{"name":"culture","type":"text","label":"Kultura firmy","defaultValue":"trust-based, results-oriented"},{"name":"jurisdiction","type":"text","label":"Jurysdykcja","defaultValue":"Poland / EU"}]'::jsonb,
 '## Role\nHR writer — human-readable policies.\n\n## Topic\n{{topic}}\n\n## Task\nPlain language policy with rationale, procedures, examples, FAQ.',
 86, 13, false, 242),

('Book Proposal Writer',
 'Tworzy propozycje książkowe dla agentów i wydawców.',
 'writing', 'advanced',
 ARRAY['book','publishing','proposal','nonfiction'],
 '[{"id":"1","content":"You are a literary agent consultant who has placed 200+ nonfiction books with major publishers, knowing exactly what makes a winning book proposal.","order_index":0,"section_slug":"role"},{"id":"2","content":"Book concept: {{concept}}\nTarget reader: {{reader}}\nAuthor platform: {{platform}}\nComparable titles: {{comp_titles}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write proposal: Overview (2-page pitch), Market analysis (size, trends, comps), Author bio + platform statistics, Chapter-by-chapter outline (1 paragraph each), Sample chapter selection recommendation, Promotion plan (speaking, social, media), Publisher fit notes.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"concept","type":"textarea","label":"Koncepcja książki","defaultValue":""},{"name":"reader","type":"text","label":"Docelowy czytelnik","defaultValue":""},{"name":"platform","type":"text","label":"Platforma autora","defaultValue":"newsletter 50k, LinkedIn 20k"},{"name":"comp_titles","type":"text","label":"Porównywalne tytuły","defaultValue":""}]'::jsonb,
 '## Role\nLiterary agent consultant.\n\n## Book\n{{concept}}\n\n## Task\nOverview, market analysis, chapter outline, sample chapter, promo plan.',
 91, 9, false, 243),

('Refund & Return Policy',
 'Pisze politykę zwrotów która buduje zaufanie i redukuje tarcie zakupowe.',
 'writing', 'beginner',
 ARRAY['ecommerce','policy','legal','customer-experience'],
 '[{"id":"1","content":"You are a customer experience specialist who writes refund policies that build purchase confidence and reduce cart abandonment, while protecting the business.","order_index":0,"section_slug":"role"},{"id":"2","content":"Business type: {{business_type}}\nProducts: {{products}}\nReturn window: {{window}}\nSpecial conditions: {{conditions}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Plain English policy (no legalese), Eligibility criteria (clear yes/no), Step-by-step return process, Refund timeline with method, Exceptions table, Digital product policy, Damaged/defective item procedure, Contact information, Trust-building intro paragraph that frames returns as easy.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"business_type","type":"text","label":"Typ biznesu","defaultValue":"e-commerce / SaaS"},{"name":"products","type":"text","label":"Produkty","defaultValue":"physical goods + digital downloads"},{"name":"window","type":"text","label":"Okno zwrotu","defaultValue":"30 days"},{"name":"conditions","type":"text","label":"Specjalne warunki","defaultValue":"unopened only, no software keys"}]'::jsonb,
 '## Role\nCustomer experience specialist — policies.\n\n## Business\n{{business_type}}\n\n## Task\nPlain English policy: eligibility, process, timeline, exceptions.',
 84, 17, false, 244),

('Thought Leadership Newsletter',
 'Pisze premium newslettery eksperckie budujące lojalną społeczność.',
 'writing', 'advanced',
 ARRAY['newsletter','thought-leadership','community','monetization'],
 '[{"id":"1","content":"You are a newsletter strategist who helps experts build premium publications with high open rates, paid subscribers, and cult followings.","order_index":0,"section_slug":"role"},{"id":"2","content":"Newsletter: {{newsletter_name}}\nNiche: {{niche}}\nMain insight this issue: {{insight}}\nSubscriber type: {{subscribers}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write issue: 3 subject line options (curiosity gap, direct value, contrarian), Opening hook (1 bold statement), Main essay (500-700 words: insight + story + framework + action step), 5 curated resources with opinionated 1-line commentary, Community spotlight, Sponsor slot, Closing with reply-to question.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"newsletter_name","type":"text","label":"Nazwa newslettera","defaultValue":""},{"name":"niche","type":"text","label":"Nisza","defaultValue":""},{"name":"insight","type":"text","label":"Główny insight w tym wydaniu","defaultValue":""},{"name":"subscribers","type":"text","label":"Typ subskrybentów","defaultValue":""}]'::jsonb,
 '## Role\nPremium newsletter strategist.\n\n## Newsletter\n{{newsletter_name}} for {{subscribers}}\n\n## Task\nSubject lines, hook, essay, curated resources, community, sponsor.',
 90, 21, true, 245),

('Technical Interview Prep Guide',
 'Tworzy spersonalizowane przewodniki przygotowania do rozmów technicznych.',
 'writing', 'intermediate',
 ARRAY['interview','career','technical','preparation'],
 '[{"id":"1","content":"You are a FAANG interview coach who has helped 500+ engineers land jobs at top tech companies through structured preparation plans.","order_index":0,"section_slug":"role"},{"id":"2","content":"Role target: {{role}}\nCompany: {{company}}\nCandidate background: {{background}}\nWeeks until interview: {{weeks}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create prep plan: Week-by-week study schedule, Topic priority list with time allocation, 20 essential interview questions with answer frameworks (STAR for behavioral), System design topics to master, Coding problem categories and recommended practice sets, Mock interview questions, Day-before checklist.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"role","type":"text","label":"Docelowe stanowisko","defaultValue":"Senior Software Engineer"},{"name":"company","type":"text","label":"Firma","defaultValue":"FAANG / top tech company"},{"name":"background","type":"text","label":"Tło kandydata","defaultValue":"5 years backend, Python/Java"},{"name":"weeks","type":"text","label":"Tygodnie do rozmowy","defaultValue":"6"}]'::jsonb,
 '## Role\nFAANG interview coach.\n\n## Target\n{{role}} at {{company}}\n\n## Task\nWeek-by-week plan, STAR questions, system design topics, mock Qs.',
 89, 35, true, 246),

('Freelance Proposal Template',
 'Tworzy propozycje freelancerskie które wygrywają projekty premium.',
 'writing', 'intermediate',
 ARRAY['freelance','proposal','client-acquisition','business'],
 '[{"id":"1","content":"You are a 6-figure freelancer who writes project proposals that consistently win high-value clients by focusing on outcomes, not deliverables.","order_index":0,"section_slug":"role"},{"id":"2","content":"Service: {{service}}\nClient project: {{project}}\nBudget range: {{budget}}\nCompetition level: {{competition}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write proposal: Client-focused summary (their problem, not your services), Understanding of their goals, Proposed approach (3-phase methodology), Why this approach, Deliverables list with timeline, Investment options (Good/Better/Best pricing), Relevant portfolio examples, Guarantee statement, Clear next step.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"service","type":"text","label":"Usługa freelancerska","defaultValue":"web development / design / copywriting"},{"name":"project","type":"text","label":"Projekt klienta","defaultValue":""},{"name":"budget","type":"text","label":"Budżet klienta","defaultValue":""},{"name":"competition","type":"text","label":"Poziom konkurencji","defaultValue":"3-5 competing proposals"}]'::jsonb,
 '## Role\n6-figure freelancer.\n\n## Service\n{{service}}\n\n## Task\nClient-focused proposal: problem, approach, 3-tier pricing, guarantee.',
 88, 27, false, 247),

('Social Proof Collection System',
 'Tworzy system zbierania i prezentowania dowodów społecznych.',
 'writing', 'intermediate',
 ARRAY['social-proof','conversion','marketing','testimonials'],
 '[{"id":"1","content":"You are a conversion rate optimizer who designs systematic approaches to collecting, curating, and displaying social proof that removes buyer hesitation.","order_index":0,"section_slug":"role"},{"id":"2","content":"Business: {{business}}\nExisting proof: {{existing_proof}}\nConversion goal: {{goal}}\nMain objection: {{objection}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create system: 5 testimonial request templates (email, in-app, post-purchase), Question framework to get specific/quantifiable testimonials, Testimonial editing guide (authentic + impactful), Display strategy by funnel stage, Review site optimization plan, Case study sourcing framework, Social proof calendar.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"business","type":"text","label":"Biznes","defaultValue":""},{"name":"existing_proof","type":"text","label":"Istniejące dowody","defaultValue":"few unstructured testimonials"},{"name":"goal","type":"text","label":"Cel konwersji","defaultValue":"increase trial-to-paid conversion"},{"name":"objection","type":"text","label":"Główna obiekcja","defaultValue":"does this work for my use case?"}]'::jsonb,
 '## Role\nConversion rate optimizer — social proof.\n\n## Business\n{{business}}\n\n## Task\nRequest templates, editing guide, display strategy, review optimization.',
 87, 15, false, 248),

('Employee Resignation Letter',
 'Pisze profesjonalne listy rezygnacyjne zachowujące relacje zawodowe.',
 'writing', 'beginner',
 ARRAY['career','hr','resignation','professional'],
 '[{"id":"1","content":"You are a career coach who helps professionals leave jobs gracefully, maintaining relationships and reputation while moving forward positively.","order_index":0,"section_slug":"role"},{"id":"2","content":"Current role: {{role}}\nCompany: {{company}}\nLast day: {{last_day}}\nReason (optional, for context only): {{reason}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Write: Formal resignation letter (clear statement, last day, gratitude, transition support offer), Informal version for close manager, Goodbye email to team (positive, no bridges burned), LinkedIn recommendation request template, Exit interview preparation notes.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"role","type":"text","label":"Aktualne stanowisko","defaultValue":""},{"name":"company","type":"text","label":"Firma","defaultValue":""},{"name":"last_day","type":"text","label":"Ostatni dzień pracy","defaultValue":""},{"name":"reason","type":"text","label":"Powód (opcjonalnie)","defaultValue":"new opportunity"}]'::jsonb,
 '## Role\nCareer coach — graceful exits.\n\n## Role\n{{role}} at {{company}}\n\n## Task\nFormal letter, informal version, team goodbye, LinkedIn request.',
 82, 22, false, 249);
