-- Migration: 200 high-quality prompts — Part 3: Analysis (50 prompts)
-- Date: 2026-06-11

INSERT INTO public.system_templates (title, description, category, difficulty, tags, blocks, variables, content_md, ai_score, fork_count, is_featured, order_index) VALUES

('Business Data Analyzer',
 'Analizuje dane biznesowe i dostarcza actionable insights z rekomendacjami.',
 'analysis', 'beginner',
 ARRAY['data-analysis','business-intelligence','kpi','insights'],
 '[{"id":"1","content":"You are a senior business analyst with expertise in translating raw data into strategic insights and clear recommendations for decision-makers.","order_index":0,"section_slug":"role"},{"id":"2","content":"Data: {{data}}\nBusiness context: {{context}}\nKey question: {{question}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Data quality assessment 2) Key findings (top 5 with supporting numbers) 3) Trend identification 4) Anomalies and outliers 5) Root cause hypotheses 6) Actionable recommendations (ranked by impact/effort) 7) Suggested next analysis steps","order_index":2,"section_slug":"task"},{"id":"4","content":"Format: Executive summary first, then detailed sections. Use tables for comparisons. Bold key numbers.","order_index":3,"section_slug":"format"}]'::jsonb,
 '[{"name":"data","type":"textarea","label":"Dane do analizy (CSV, opis lub liczby)","defaultValue":""},{"name":"context","type":"text","label":"Kontekst biznesowy","defaultValue":"e-commerce company, Q3 2025"},{"name":"question","type":"text","label":"Kluczowe pytanie biznesowe","defaultValue":""}]'::jsonb,
 '## Role\nSenior business analyst.\n\n## Data\n{{data}}\n\n## Task\nFindings, trends, anomalies, root causes, ranked recommendations.',
 86, 28, true, 300),

('Market Research Report',
 'Przeprowadza badania rynku i tworzy raporty z insightami konkurencyjnymi.',
 'analysis', 'intermediate',
 ARRAY['market-research','competitive-intelligence','strategy','tam'],
 '[{"id":"1","content":"You are a market research analyst who synthesizes industry data, competitive intelligence, and consumer trends into actionable market reports.","order_index":0,"section_slug":"role"},{"id":"2","content":"Market: {{market}}\nGeography: {{geography}}\nTime horizon: {{horizon}}\nResearch question: {{question}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Market size (TAM/SAM/SOM with methodology) 2) Growth drivers and inhibitors 3) Competitive landscape (Porter''s Five Forces) 4) Customer segments and personas 5) Technology trends disrupting the market 6) Regulatory environment 7) 3-year market forecast with scenarios","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"market","type":"text","label":"Rynek do analizy","defaultValue":"B2B SaaS project management tools"},{"name":"geography","type":"text","label":"Obszar geograficzny","defaultValue":"Europe"},{"name":"horizon","type":"text","label":"Horyzont czasowy","defaultValue":"2025-2028"},{"name":"question","type":"text","label":"Pytanie badawcze","defaultValue":"Is there a gap for AI-native tools?"}]'::jsonb,
 '## Role\nMarket research analyst.\n\n## Market\n{{market}} in {{geography}}\n\n## Task\nTAM/SAM/SOM, Porter''s 5 forces, segments, tech trends, forecast.',
 89, 19, true, 301),

('Competitive Analysis Framework',
 'Tworzy kompleksową analizę konkurencji z macierzą pozycjonowania.',
 'analysis', 'intermediate',
 ARRAY['competitive-analysis','strategy','positioning','benchmarking'],
 '[{"id":"1","content":"You are a competitive intelligence specialist who builds comprehensive competitor profiles and identifies strategic opportunities for differentiation.","order_index":0,"section_slug":"role"},{"id":"2","content":"Your company: {{our_company}}\nCompetitors to analyze: {{competitors}}\nFocus areas: {{focus}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Deliver: 1) Competitor profile cards (product, pricing, positioning, strengths, weaknesses) 2) Feature comparison matrix 3) Positioning map (2×2) 4) Go-to-market strategy comparison 5) Content/SEO gap analysis 6) Customer review sentiment summary 7) Strategic opportunities identified 8) Threats to monitor","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"our_company","type":"text","label":"Nasza firma i produkt","defaultValue":""},{"name":"competitors","type":"text","label":"Konkurenci (lista)","defaultValue":""},{"name":"focus","type":"text","label":"Obszary analizy","defaultValue":"product features, pricing, marketing, UX"}]'::jsonb,
 '## Role\nCompetitive intelligence specialist.\n\n## Market\n{{our_company}} vs {{competitors}}\n\n## Task\nProfiles, feature matrix, positioning map, SEO gaps, opportunities.',
 90, 24, true, 302),

('SWOT Analysis Generator',
 'Przeprowadza pogłębioną analizę SWOT z priorytetyzacją strategiczną.',
 'analysis', 'beginner',
 ARRAY['swot','strategy','business-planning','decision-making'],
 '[{"id":"1","content":"You are a strategic management consultant who conducts rigorous SWOT analyses and translates them into prioritized strategic actions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Subject: {{subject}}\nIndustry context: {{industry}}\nTime frame: {{timeframe}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Strengths (internal advantages, with evidence) 2) Weaknesses (internal gaps, honest assessment) 3) Opportunities (external trends, emerging markets) 4) Threats (competition, regulation, technology disruption) 5) TOWS matrix (SO/ST/WO/WT strategies) 6) Top 3 priority actions from analysis","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"subject","type":"text","label":"Podmiot analizy","defaultValue":"our company / product / strategy"},{"name":"industry","type":"text","label":"Kontekst branżowy","defaultValue":""},{"name":"timeframe","type":"text","label":"Horyzont czasowy","defaultValue":"12-24 months"}]'::jsonb,
 '## Role\nStrategic management consultant.\n\n## Subject\n{{subject}}\n\n## Task\nSWOT + TOWS matrix + top 3 priority actions.',
 85, 42, true, 303),

('Financial Statement Analyzer',
 'Analizuje sprawozdania finansowe i ocenia kondycję finansową firmy.',
 'analysis', 'advanced',
 ARRAY['finance','financial-analysis','accounting','valuation'],
 '[{"id":"1","content":"You are a financial analyst with CFA expertise who analyzes P&L, balance sheets, and cash flow statements to assess financial health and investment potential.","order_index":0,"section_slug":"role"},{"id":"2","content":"Company: {{company}}\nFinancial data: {{financial_data}}\nAnalysis purpose: {{purpose}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Profitability ratios (gross/net margin, EBITDA) 2) Liquidity ratios (current, quick) 3) Leverage ratios (debt/equity, interest coverage) 4) Efficiency ratios (asset turnover, receivables days) 5) YoY trend analysis 6) Industry benchmark comparison 7) Red flags and positive signals 8) Valuation implications","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"company","type":"text","label":"Firma","defaultValue":""},{"name":"financial_data","type":"textarea","label":"Dane finansowe (P&L, bilans lub opis)","defaultValue":""},{"name":"purpose","type":"text","label":"Cel analizy","defaultValue":"investment decision / due diligence"}]'::jsonb,
 '## Role\nCFA financial analyst.\n\n## Company\n{{company}}\n\n## Task\nRatios analysis, trends, benchmarks, red flags, valuation.',
 93, 16, false, 304),

('Customer Churn Analysis',
 'Identyfikuje wzorce churnu i rekomenduje strategie retencji.',
 'analysis', 'advanced',
 ARRAY['churn','retention','saas','customer-analytics'],
 '[{"id":"1","content":"You are a customer analytics specialist who identifies churn patterns, predicts at-risk customers, and designs evidence-based retention strategies.","order_index":0,"section_slug":"role"},{"id":"2","content":"Churn data: {{churn_data}}\nProduct type: {{product}}\nCurrent churn rate: {{churn_rate}}\nCustomer segments: {{segments}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Churn rate calculation and benchmarking 2) Cohort churn analysis 3) Leading indicators of churn (behavioral signals) 4) Customer segments most at risk 5) Revenue impact (MRR churn vs logo churn) 6) Root cause analysis (survey data, support tickets) 7) Retention playbook recommendations 8) Metrics to track improvement","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"churn_data","type":"textarea","label":"Dane o churnie","defaultValue":""},{"name":"product","type":"text","label":"Typ produktu","defaultValue":"B2B SaaS"},{"name":"churn_rate","type":"text","label":"Aktualny wskaźnik churnu","defaultValue":"5% monthly"},{"name":"segments","type":"text","label":"Segmenty klientów","defaultValue":"SMB, Mid-Market, Enterprise"}]'::jsonb,
 '## Role\nCustomer analytics specialist.\n\n## Data\n{{churn_data}}\n\n## Task\nCohort analysis, leading indicators, revenue impact, retention playbook.',
 91, 22, true, 305),

('A/B Test Results Analyzer',
 'Interpretuje wyniki testów A/B z poprawną analizą statystyczną.',
 'analysis', 'intermediate',
 ARRAY['ab-testing','statistics','cro','experimentation'],
 '[{"id":"1","content":"You are a data scientist specializing in experimentation and statistical analysis who ensures A/B test conclusions are statistically valid and business-relevant.","order_index":0,"section_slug":"role"},{"id":"2","content":"Test description: {{test_description}}\nVariant A results: {{variant_a}}\nVariant B results: {{variant_b}}\nTest duration: {{duration}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Statistical significance (p-value, confidence interval) 2) Practical significance (minimum detectable effect) 3) Sample size adequacy 4) Segmentation analysis (did effect vary by segment?) 5) Novelty effect check 6) Guardrail metrics impact 7) Recommendation (ship/iterate/abandon) with confidence level 8) Next experiment suggestions","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"test_description","type":"text","label":"Opis testu","defaultValue":"checkout button color change"},{"name":"variant_a","type":"text","label":"Wyniki wariantu A (control)","defaultValue":"conversion: 3.2%, n=5000"},{"name":"variant_b","type":"text","label":"Wyniki wariantu B (treatment)","defaultValue":"conversion: 3.8%, n=4800"},{"name":"duration","type":"text","label":"Czas trwania testu","defaultValue":"14 days"}]'::jsonb,
 '## Role\nExperimentation data scientist.\n\n## Test\n{{test_description}}\n\n## Task\nStatistical significance, segmentation, guardrails, recommendation.',
 92, 25, true, 306),

('User Survey Data Synthesizer',
 'Syntezuje dane z badań użytkowników w insights i rekomendacje produktowe.',
 'analysis', 'intermediate',
 ARRAY['user-research','qualitative','product','insights'],
 '[{"id":"1","content":"You are a UX researcher who synthesizes qualitative and quantitative survey data into clear themes, personas, and product recommendations.","order_index":0,"section_slug":"role"},{"id":"2","content":"Survey topic: {{topic}}\nResponses: {{responses}}\nNumber of respondents: {{n}}\nResearch goal: {{goal}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Synthesize: 1) Affinity clustering of open-ended responses 2) Quantitative summary of closed questions 3) Top 5 user pain points (with frequency) 4) User sentiment analysis 5) Emerging themes and patterns 6) Contradictions worth investigating 7) Product opportunity recommendations 8) Suggested follow-up research","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"topic","type":"text","label":"Temat badania","defaultValue":"onboarding experience satisfaction"},{"name":"responses","type":"textarea","label":"Odpowiedzi (fragment lub opis)","defaultValue":""},{"name":"n","type":"text","label":"Liczba respondentów","defaultValue":"150"},{"name":"goal","type":"text","label":"Cel badania","defaultValue":"improve activation rate"}]'::jsonb,
 '## Role\nUX researcher.\n\n## Survey\n{{topic}} (n={{n}})\n\n## Task\nAffinity clusters, pain points, sentiment, contradictions, product opportunities.',
 88, 17, false, 307),

('SEO Performance Report',
 'Analizuje wydajność SEO i tworzy plan działań optymalizacyjnych.',
 'analysis', 'intermediate',
 ARRAY['seo','search-analytics','content-strategy','google'],
 '[{"id":"1","content":"You are an SEO analyst who interprets Google Search Console and Analytics data to identify growth opportunities and technical issues.","order_index":0,"section_slug":"role"},{"id":"2","content":"Website: {{website}}\nSEO data: {{data}}\nMain goals: {{goals}}\nCurrent issues: {{issues}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Organic traffic trends (MoM, YoY) 2) Top performing pages and queries 3) Click-through rate optimization opportunities 4) Keyword cannibalization 5) Core Web Vitals impact 6) Technical SEO issues (crawl errors, indexing) 7) Content gap analysis 8) 90-day action plan with priority ranking","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"website","type":"text","label":"Witryna internetowa","defaultValue":""},{"name":"data","type":"textarea","label":"Dane SEO (GSC, Analytics lub opis)","defaultValue":""},{"name":"goals","type":"text","label":"Główne cele","defaultValue":"increase organic traffic 30% in 6 months"},{"name":"issues","type":"text","label":"Znane problemy","defaultValue":""}]'::jsonb,
 '## Role\nSEO analyst.\n\n## Website\n{{website}}\n\n## Task\nTraffic trends, CTR opps, cannibalization, Core Web Vitals, 90-day plan.',
 87, 20, false, 308),

('Sales Funnel Audit',
 'Diagnozuje wąskie gardła lejka sprzedażowego i optymalizuje konwersje.',
 'analysis', 'intermediate',
 ARRAY['sales-funnel','conversion','crm','revenue-operations'],
 '[{"id":"1","content":"You are a revenue operations analyst who audits sales funnels to identify conversion leaks, optimize stage progression, and increase win rates.","order_index":0,"section_slug":"role"},{"id":"2","content":"Funnel stages: {{stages}}\nConversion rates: {{conversion_rates}}\nAverage deal size: {{deal_size}}\nSales cycle: {{cycle}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Audit: 1) Stage-by-stage conversion analysis 2) Biggest drop-off points 3) Velocity analysis (time in each stage) 4) Win/loss rate by segment 5) Activity-to-outcome correlation 6) ICP fit scoring recommendations 7) Bottleneck root causes 8) Improvement experiments to run","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"stages","type":"text","label":"Etapy lejka","defaultValue":"Lead → MQL → SQL → Demo → Proposal → Closed"},{"name":"conversion_rates","type":"text","label":"Współczynniki konwersji","defaultValue":"30% → 40% → 60% → 30% → 50%"},{"name":"deal_size","type":"text","label":"Średnia wartość transakcji","defaultValue":"$15,000 ACV"},{"name":"cycle","type":"text","label":"Cykl sprzedaży","defaultValue":"45 days"}]'::jsonb,
 '## Role\nRevenue operations analyst.\n\n## Funnel\n{{stages}}\n\n## Task\nDrop-off analysis, velocity, win/loss, bottlenecks, experiments.',
 89, 21, false, 309),

('Risk Assessment Matrix',
 'Tworzy macierz ryzyk z prawdopodobieństwem, wpływem i planem mitygacji.',
 'analysis', 'advanced',
 ARRAY['risk-management','project-management','compliance','strategy'],
 '[{"id":"1","content":"You are a risk management consultant who builds comprehensive risk registers and mitigation strategies for complex projects and organizations.","order_index":0,"section_slug":"role"},{"id":"2","content":"Context: {{context}}\nScope of analysis: {{scope}}\nStakeholders: {{stakeholders}}\nTime horizon: {{horizon}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create: 1) Risk identification (strategic, operational, financial, compliance, technology) 2) Probability × Impact scoring matrix 3) Risk heat map description 4) Top 10 risks detailed (description, likelihood, impact, velocity) 5) Mitigation strategies per risk 6) Risk owner assignments 7) Early warning indicators 8) Residual risk after mitigation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"context","type":"text","label":"Kontekst (projekt/firma)","defaultValue":"launching new SaaS product in EU market"},{"name":"scope","type":"text","label":"Zakres analizy","defaultValue":"product, market, regulatory, technical"},{"name":"stakeholders","type":"text","label":"Interesariusze","defaultValue":"investors, customers, employees, regulators"},{"name":"horizon","type":"text","label":"Horyzont czasowy","defaultValue":"18 months"}]'::jsonb,
 '## Role\nRisk management consultant.\n\n## Context\n{{context}}\n\n## Task\nRisk register, P×I matrix, top 10 risks, mitigation, early warnings.',
 92, 15, false, 310),

('KPI Framework Designer',
 'Projektuje strukturę KPI dostosowaną do celów biznesowych.',
 'analysis', 'intermediate',
 ARRAY['kpi','metrics','okr','performance-management'],
 '[{"id":"1","content":"You are a performance management expert who designs KPI frameworks that align teams with business goals and enable data-driven decisions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Company/team: {{team}}\nBusiness goals: {{goals}}\nDepartments: {{departments}}\nReporting cadence: {{cadence}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Design: 1) North Star Metric with rationale 2) 3 Input metrics per business goal 3) Leading vs lagging indicators balance 4) Department-level metric cascades 5) Metric definitions and measurement methodology 6) Data sources and collection method 7) Dashboard structure recommendation 8) Metric review cadence","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"team","type":"text","label":"Firma/zespół","defaultValue":"B2B SaaS startup, 50 employees"},{"name":"goals","type":"text","label":"Cele biznesowe","defaultValue":"reach $5M ARR, reduce churn to 2%, NPS > 50"},{"name":"departments","type":"text","label":"Działy","defaultValue":"Sales, Marketing, Product, Customer Success"},{"name":"cadence","type":"text","label":"Częstotliwość raportowania","defaultValue":"weekly/monthly/quarterly"}]'::jsonb,
 '## Role\nPerformance management expert.\n\n## Team\n{{team}}\n\n## Task\nNorth Star metric, input metrics, leading/lagging, cascades, dashboard.',
 88, 23, true, 311),

('Customer Sentiment Analysis',
 'Analizuje sentyment opinii klientów i identyfikuje tematy w feedbacku.',
 'analysis', 'intermediate',
 ARRAY['sentiment-analysis','nps','customer-feedback','product'],
 '[{"id":"1","content":"You are a customer insights analyst who extracts meaning from large volumes of customer feedback using sentiment analysis and thematic clustering.","order_index":0,"section_slug":"role"},{"id":"2","content":"Feedback source: {{source}}\nFeedback data: {{data}}\nProduct area: {{product_area}}\nTime period: {{period}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Overall sentiment score and distribution 2) Top positive themes (with frequency and example quotes) 3) Top negative themes (with frequency and example quotes) 4) Emerging concerns vs long-standing issues 5) Competitor mentions 6) Feature request extraction 7) Priority matrix (sentiment impact × frequency) 8) Recommended actions","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"source","type":"text","label":"Źródło opinii","defaultValue":"App Store reviews, G2, support tickets"},{"name":"data","type":"textarea","label":"Dane z opinii","defaultValue":""},{"name":"product_area","type":"text","label":"Obszar produktu","defaultValue":"mobile app"},{"name":"period","type":"text","label":"Okres","defaultValue":"last 90 days"}]'::jsonb,
 '## Role\nCustomer insights analyst.\n\n## Feedback\n{{source}} ({{period}})\n\n## Task\nSentiment distribution, themes with quotes, priority matrix, actions.',
 87, 18, false, 312),

('Product-Market Fit Assessment',
 'Ocenia dopasowanie produktu do rynku używając wielowymiarowych wskaźników.',
 'analysis', 'advanced',
 ARRAY['pmf','product-strategy','startup','growth'],
 '[{"id":"1","content":"You are a product strategist who assesses product-market fit using Sean Ellis test, retention curves, and qualitative signals to determine growth readiness.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nTarget market: {{market}}\nCurrent metrics: {{metrics}}\nUser feedback highlights: {{feedback}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Assess: 1) Sean Ellis Test interpretation (''very disappointed'' %) 2) Retention curve analysis (flat vs declining) 3) NPS and qualitative signals 4) Word-of-mouth coefficient 5) Usage frequency vs expected 6) Customer profile fit score 7) PMF score (0-10 rubric) 8) If PMF achieved: growth levers; if not: pivot hypotheses","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt","defaultValue":""},{"name":"market","type":"text","label":"Docelowy rynek","defaultValue":""},{"name":"metrics","type":"textarea","label":"Aktualne metryki","defaultValue":""},{"name":"feedback","type":"textarea","label":"Feedback użytkowników (kluczowe cytaty)","defaultValue":""}]'::jsonb,
 '## Role\nPMF strategist.\n\n## Product\n{{product}}\n\n## Task\nSean Ellis, retention curve, NPS, WOM, PMF score, growth/pivot plan.',
 93, 20, true, 313),

('Social Media Analytics Report',
 'Analizuje wyniki w mediach społecznościowych i optymalizuje strategię.',
 'analysis', 'beginner',
 ARRAY['social-media','analytics','content-strategy','engagement'],
 '[{"id":"1","content":"You are a social media analyst who interprets platform analytics to optimize content strategy and maximize organic reach and engagement.","order_index":0,"section_slug":"role"},{"id":"2","content":"Platforms: {{platforms}}\nAnalytics data: {{data}}\nGoals: {{goals}}\nTime period: {{period}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Reach and impression trends 2) Engagement rate by content type 3) Best performing posts (what made them work) 4) Audience growth rate and demographics 5) Optimal posting times 6) Competitor benchmark 7) Content gap opportunities 8) 30-day content optimization recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"platforms","type":"text","label":"Platformy","defaultValue":"Instagram, LinkedIn, Twitter"},{"name":"data","type":"textarea","label":"Dane analityczne","defaultValue":""},{"name":"goals","type":"text","label":"Cele","defaultValue":"increase followers 20%, drive website traffic"},{"name":"period","type":"text","label":"Okres","defaultValue":"last 30 days"}]'::jsonb,
 '## Role\nSocial media analyst.\n\n## Platforms\n{{platforms}}\n\n## Task\nEngagement trends, top content analysis, optimal timing, 30-day plan.',
 84, 26, false, 314),

('Pricing Strategy Analyzer',
 'Analizuje i optymalizuje strategię cenową dla maksymalizacji przychodów.',
 'analysis', 'advanced',
 ARRAY['pricing','strategy','revenue','monetization'],
 '[{"id":"1","content":"You are a pricing strategist who uses psychological pricing principles and competitive analysis to optimize revenue without harming growth.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nCurrent pricing: {{current_pricing}}\nCompetitor pricing: {{competitor_pricing}}\nCustomer segments: {{segments}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Price sensitivity assessment (Van Westendorp methodology) 2) Value metric identification 3) Competitive positioning (premium/parity/penetration) 4) Packaging optimization 5) Discount strategy analysis 6) Expansion revenue opportunities (upsell/cross-sell) 7) Pricing page conversion optimization 8) Revenue model alternatives","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt","defaultValue":""},{"name":"current_pricing","type":"text","label":"Aktualne ceny","defaultValue":""},{"name":"competitor_pricing","type":"text","label":"Ceny konkurencji","defaultValue":""},{"name":"segments","type":"text","label":"Segmenty klientów","defaultValue":"SMB, Mid-Market, Enterprise"}]'::jsonb,
 '## Role\nPricing strategist.\n\n## Product\n{{product}}\n\n## Task\nVan Westendorp, value metric, packaging, discounts, expansion revenue.',
 91, 19, false, 315),

('Customer Segmentation Analysis',
 'Segmentuje bazę klientów według wartości, zachowań i potrzeb.',
 'analysis', 'advanced',
 ARRAY['segmentation','crm','marketing','revenue'],
 '[{"id":"1","content":"You are a customer analytics expert who creates actionable customer segments using RFM analysis, behavioral clustering, and lifetime value modeling.","order_index":0,"section_slug":"role"},{"id":"2","content":"Customer data: {{data}}\nBusiness model: {{model}}\nSegmentation goal: {{goal}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Deliver: 1) RFM (Recency, Frequency, Monetary) analysis 2) 5-7 customer segments with profiles 3) Segment size and revenue contribution 4) Behavioral characteristics per segment 5) Customer Lifetime Value by segment 6) Acquisition channel correlation 7) Tailored engagement strategy per segment 8) Segment migration tracking","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"data","type":"textarea","label":"Dane klientów (opis lub CSV)","defaultValue":""},{"name":"model","type":"text","label":"Model biznesowy","defaultValue":"subscription SaaS"},{"name":"goal","type":"text","label":"Cel segmentacji","defaultValue":"personalize marketing, reduce churn"}]'::jsonb,
 '## Role\nCustomer analytics expert.\n\n## Data\n{{data}}\n\n## Task\nRFM analysis, 5-7 segments with CLV, engagement strategies, migration tracking.',
 90, 17, false, 316),

('ROI Calculator & Analysis',
 'Oblicza i analizuje zwrot z inwestycji dla projektów i inicjatyw.',
 'analysis', 'intermediate',
 ARRAY['roi','finance','investment','business-case'],
 '[{"id":"1","content":"You are a financial analyst who builds rigorous ROI models for business initiatives, ensuring all costs and benefits are captured with realistic assumptions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Investment: {{investment}}\nCost inputs: {{costs}}\nBenefit assumptions: {{benefits}}\nTime horizon: {{horizon}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Calculate: 1) Total cost of ownership (direct + indirect + opportunity costs) 2) Quantified benefit streams (revenue increase, cost reduction, risk mitigation) 3) NPV calculation with discount rate justification 4) Payback period 5) Sensitivity analysis (3 scenarios: pessimistic/base/optimistic) 6) Break-even analysis 7) Non-financial benefits (strategic value) 8) Go/No-go recommendation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"investment","type":"text","label":"Inwestycja do oceny","defaultValue":"migrating to cloud infrastructure"},{"name":"costs","type":"text","label":"Koszty","defaultValue":"migration cost $50k, monthly $8k infra"},{"name":"benefits","type":"text","label":"Oczekiwane korzyści","defaultValue":"30% server cost reduction, 99.9% uptime"},{"name":"horizon","type":"text","label":"Horyzont analizy","defaultValue":"3 years"}]'::jsonb,
 '## Role\nFinancial ROI analyst.\n\n## Investment\n{{investment}}\n\n## Task\nTCO, NPV, payback, sensitivity (3 scenarios), break-even, recommendation.',
 89, 21, false, 317),

('Technical Debt Assessment',
 'Kwantyfikuje dług techniczny i priorytetyzuje plan spłaty.',
 'analysis', 'advanced',
 ARRAY['technical-debt','engineering','code-quality','architecture'],
 '[{"id":"1","content":"You are a software engineering lead who quantifies technical debt in business terms and creates prioritized remediation roadmaps that engineering and business can both understand.","order_index":0,"section_slug":"role"},{"id":"2","content":"Codebase description: {{codebase}}\nDebt areas identified: {{debt_areas}}\nTeam velocity: {{velocity}}\nBusiness context: {{business_context}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Assess: 1) Technical debt taxonomy (code, architectural, test, documentation, dependency) 2) Business impact per debt item (velocity loss %, bug rate, onboarding time) 3) Cost to remediate vs cost to ignore 4) Priority matrix (impact × effort × risk) 5) Remediation roadmap (quick wins + strategic investments) 6) ''Debt budget'' recommendation (% of sprint capacity)","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"codebase","type":"text","label":"Opis codebase","defaultValue":"5-year-old Node.js monolith, 200k LOC"},{"name":"debt_areas","type":"textarea","label":"Zidentyfikowane obszary długu","defaultValue":""},{"name":"velocity","type":"text","label":"Velocity zespołu","defaultValue":"30 story points/sprint"},{"name":"business_context","type":"text","label":"Kontekst biznesowy","defaultValue":"preparing for Series B, need to scale"}]'::jsonb,
 '## Role\nEngineering lead — technical debt.\n\n## Codebase\n{{codebase}}\n\n## Task\nDebt taxonomy, business impact, priority matrix, roadmap, debt budget.',
 92, 24, true, 318),

('NPS Analysis & Action Plan',
 'Analizuje wyniki Net Promoter Score i tworzy plan poprawy.',
 'analysis', 'intermediate',
 ARRAY['nps','customer-satisfaction','retention','cx'],
 '[{"id":"1","content":"You are a customer experience analyst who transforms NPS data into actionable improvement programs that move Detractors to Promoters.","order_index":0,"section_slug":"role"},{"id":"2","content":"NPS data: {{nps_data}}\nComments/verbatims: {{verbatims}}\nProduct type: {{product}}\nIndustry benchmark: {{benchmark}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) NPS score calculation and trend 2) Promoter/Passive/Detractor breakdown 3) Segment NPS (by plan, region, company size) 4) Verbatim theme analysis 5) Key drivers of satisfaction and dissatisfaction 6) Detractor recovery priority list 7) Promoter amplification strategy 8) 30/60/90-day improvement roadmap","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"nps_data","type":"text","label":"Dane NPS","defaultValue":"Score: 32, P:45%, Pa:30%, D:25%, n=200"},{"name":"verbatims","type":"textarea","label":"Komentarze (próbka)","defaultValue":""},{"name":"product","type":"text","label":"Produkt","defaultValue":"B2B SaaS"},{"name":"benchmark","type":"text","label":"Benchmark branżowy","defaultValue":"industry average: 35"}]'::jsonb,
 '## Role\nCX analyst — NPS programs.\n\n## NPS\n{{nps_data}}\n\n## Task\nSegmented NPS, driver analysis, detractor recovery, 30/60/90-day plan.',
 88, 18, false, 319),

('Startup Metrics Dashboard',
 'Definiuje kluczowe metryki startupowe i tworzy framework monitorowania.',
 'analysis', 'intermediate',
 ARRAY['startup','metrics','saas','growth'],
 '[{"id":"1","content":"You are a startup advisor and former VC analyst who knows exactly which metrics matter at each stage of growth and how to measure them accurately.","order_index":0,"section_slug":"role"},{"id":"2","content":"Stage: {{stage}}\nBusiness model: {{model}}\nCurrent metrics: {{metrics}}\nInvestor expectations: {{investor_exp}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) Stage-appropriate metric priorities (pre-PMF vs growth vs scale) 2) The 5 metrics your investors care most about 3) Vanity vs actionable metrics for your model 4) Calculation formulas with data sources 5) Benchmark ranges for each metric 6) Weekly/monthly/quarterly review framework 7) Red-flag alert thresholds 8) Investor update metrics template","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"stage","type":"text","label":"Etap startupu","defaultValue":"Series A ($2M ARR)"},{"name":"model","type":"text","label":"Model biznesowy","defaultValue":"B2B SaaS, PLG motion"},{"name":"metrics","type":"textarea","label":"Aktualne metryki","defaultValue":""},{"name":"investor_exp","type":"text","label":"Oczekiwania inwestorów","defaultValue":"triple ARR, improve net retention > 110%"}]'::jsonb,
 '## Role\nStartup advisor + VC analyst.\n\n## Stage\n{{stage}} — {{model}}\n\n## Task\nStage-appropriate metrics, formulas, benchmarks, investor template.',
 90, 27, true, 320),

('Process Efficiency Audit',
 'Diagnozuje nieefektywności procesów biznesowych i rekomenduje usprawnienia.',
 'analysis', 'intermediate',
 ARRAY['process-improvement','lean','operations','productivity'],
 '[{"id":"1","content":"You are a business process consultant certified in Lean Six Sigma who identifies waste, bottlenecks, and automation opportunities in operational processes.","order_index":0,"section_slug":"role"},{"id":"2","content":"Process: {{process}}\nCurrent metrics: {{metrics}}\nPain points: {{pain_points}}\nStakeholders: {{stakeholders}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Audit: 1) Process mapping (current state) 2) 8 wastes identification (DOWNTIME framework) 3) Cycle time and lead time analysis 4) Bottleneck identification 5) Root cause analysis (5 Whys or Fishbone) 6) Future state process design 7) Automation opportunities 8) Implementation roadmap with effort/impact matrix","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"process","type":"text","label":"Proces do audytu","defaultValue":"customer onboarding process"},{"name":"metrics","type":"text","label":"Aktualne metryki","defaultValue":"time-to-first-value: 14 days, 40% dropout"},{"name":"pain_points","type":"text","label":"Problemy i bóle","defaultValue":""},{"name":"stakeholders","type":"text","label":"Interesariusze","defaultValue":"CS team, product, sales"}]'::jsonb,
 '## Role\nLean Six Sigma consultant.\n\n## Process\n{{process}}\n\n## Task\nProcess map, 8 wastes, bottlenecks, 5 Whys, future state, automation opps.',
 87, 16, false, 321),

('Content Performance Analysis',
 'Analizuje wydajność treści i identyfikuje najskuteczniejsze formaty.',
 'analysis', 'beginner',
 ARRAY['content-marketing','analytics','seo','performance'],
 '[{"id":"1","content":"You are a content analytics specialist who identifies what content drives the most business value and builds data-driven content strategies.","order_index":0,"section_slug":"role"},{"id":"2","content":"Content inventory: {{content}}\nPerformance data: {{data}}\nBusiness goal: {{goal}}\nTime period: {{period}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Content performance by format (blog/video/podcast/social) 2) Organic traffic and ranking analysis 3) Engagement metrics (time on page, scroll depth) 4) Conversion attribution by content 5) Content ROI (cost to produce vs revenue influenced) 6) Topic cluster gaps 7) Content refresh opportunities 8) Q1 content investment recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"content","type":"text","label":"Inwentarz treści","defaultValue":"50 blog posts, 10 videos, weekly newsletter"},{"name":"data","type":"textarea","label":"Dane wydajności","defaultValue":""},{"name":"goal","type":"text","label":"Cel biznesowy","defaultValue":"generate leads, improve SEO authority"},{"name":"period","type":"text","label":"Okres","defaultValue":"last 6 months"}]'::jsonb,
 '## Role\nContent analytics specialist.\n\n## Content\n{{content}}\n\n## Task\nPerformance by format, ROI, topic gaps, refresh opportunities, Q1 plan.',
 85, 22, false, 322),

('E-commerce Funnel Analysis',
 'Analizuje lejek e-commerce i identyfikuje możliwości wzrostu konwersji.',
 'analysis', 'intermediate',
 ARRAY['ecommerce','conversion-funnel','cro','analytics'],
 '[{"id":"1","content":"You are an e-commerce analytics specialist who optimizes conversion funnels using behavioral data, session recordings, and cohort analysis.","order_index":0,"section_slug":"role"},{"id":"2","content":"Store: {{store}}\nFunnel data: {{funnel_data}}\nTop categories: {{categories}}\nTraffic sources: {{traffic}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Funnel visualization (visit→PDP→cart→checkout→purchase) 2) Drop-off rates and monetary impact 3) Cart abandonment analysis (reasons and recovery) 4) Product page optimization opportunities 5) Checkout friction points 6) Mobile vs desktop conversion gap 7) Returning vs new customer behavior 8) 10 highest-impact CRO experiments","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"store","type":"text","label":"Sklep internetowy","defaultValue":""},{"name":"funnel_data","type":"text","label":"Dane lejka","defaultValue":"sessions:10k, PDP:40%, cart:15%, checkout:8%, purchase:3%"},{"name":"categories","type":"text","label":"Główne kategorie","defaultValue":""},{"name":"traffic","type":"text","label":"Źródła ruchu","defaultValue":"organic 40%, paid 35%, direct 25%"}]'::jsonb,
 '## Role\nE-commerce analytics specialist.\n\n## Funnel\n{{funnel_data}}\n\n## Task\nDrop-off impact, cart abandonment, friction points, 10 CRO experiments.',
 88, 24, false, 323),

('Employee Engagement Analysis',
 'Analizuje zaangażowanie pracowników i identyfikuje czynniki retencji.',
 'analysis', 'intermediate',
 ARRAY['hr-analytics','engagement','retention','culture'],
 '[{"id":"1","content":"You are an HR analytics specialist who diagnoses employee engagement issues and designs evidence-based retention strategies.","order_index":0,"section_slug":"role"},{"id":"2","content":"Survey data: {{survey_data}}\nTurnover rate: {{turnover}}\nTeam size: {{team_size}}\nIndustry: {{industry}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Engagement score breakdown by dimension (culture, growth, compensation, management) 2) eNPS calculation 3) Flight risk segmentation 4) Correlation between engagement and performance 5) Department/tenure comparison 6) Generational differences 7) Turnover cost calculation 8) Intervention priority matrix 9) Manager effectiveness correlation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"survey_data","type":"textarea","label":"Dane z ankiety zaangażowania","defaultValue":""},{"name":"turnover","type":"text","label":"Wskaźnik rotacji","defaultValue":"18% annually"},{"name":"team_size","type":"text","label":"Wielkość zespołu","defaultValue":"120 employees"},{"name":"industry","type":"text","label":"Branża","defaultValue":"technology"}]'::jsonb,
 '## Role\nHR analytics specialist.\n\n## Data\n{{survey_data}}\n\n## Task\nEngagement dimensions, eNPS, flight risk, turnover cost, interventions.',
 86, 14, false, 324),

('Ad Campaign Performance Audit',
 'Audytuje kampanie reklamowe i optymalizuje alokację budżetu.',
 'analysis', 'intermediate',
 ARRAY['paid-advertising','ppc','facebook-ads','google-ads','roas'],
 '[{"id":"1","content":"You are a performance marketing analyst who audits paid advertising campaigns across channels to maximize ROAS and reduce wasted spend.","order_index":0,"section_slug":"role"},{"id":"2","content":"Campaign data: {{campaign_data}}\nTotal spend: {{spend}}\nObjective: {{objective}}\nChannels: {{channels}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Audit: 1) Overall ROAS and trend 2) Channel-by-channel performance comparison 3) Campaign/ad set/creative breakdown 4) Audience overlap and fatigue analysis 5) Attribution model assessment 6) Budget allocation optimization 7) Winning creative patterns 8) Waste identification (low performing + high spend) 9) 30-day optimization roadmap","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"campaign_data","type":"textarea","label":"Dane kampanii","defaultValue":""},{"name":"spend","type":"text","label":"Całkowity spend","defaultValue":"$20,000/month"},{"name":"objective","type":"text","label":"Cel kampanii","defaultValue":"leads / purchases / ROAS 3x"},{"name":"channels","type":"text","label":"Kanały reklamowe","defaultValue":"Google Search, Facebook, LinkedIn"}]'::jsonb,
 '## Role\nPerformance marketing analyst.\n\n## Spend\n{{spend}} across {{channels}}\n\n## Task\nROAS by channel, creative patterns, waste identification, 30-day plan.',
 89, 20, false, 325),

('SaaS Metrics Deep Dive',
 'Dogłębnie analizuje metryki SaaS: MRR, ARR, CAC, LTV, churn.',
 'analysis', 'advanced',
 ARRAY['saas','mrr','arr','ltv','cac'],
 '[{"id":"1","content":"You are a SaaS financial analyst who builds comprehensive revenue models and identifies growth levers in subscription businesses.","order_index":0,"section_slug":"role"},{"id":"2","content":"SaaS metrics: {{metrics}}\nBusiness stage: {{stage}}\nGrowth target: {{target}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) MRR/ARR growth decomposition (new + expansion - contraction - churn) 2) CAC by channel and payback period 3) LTV:CAC ratio and trend 4) Net Revenue Retention (NRR/NDR) 5) Quick Ratio (growth efficiency) 6) Magic Number (sales efficiency) 7) Rule of 40 score 8) Revenue quality assessment 9) Unit economics improvement recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"metrics","type":"textarea","label":"Dane SaaS (MRR, churn, CAC, LTV)","defaultValue":""},{"name":"stage","type":"text","label":"Etap biznesu","defaultValue":"$500k MRR, 15% MoM growth"},{"name":"target","type":"text","label":"Cel wzrostu","defaultValue":"reach $2M MRR in 12 months"}]'::jsonb,
 '## Role\nSaaS financial analyst.\n\n## Metrics\n{{metrics}}\n\n## Task\nMRR decomposition, NRR, Quick Ratio, Rule of 40, unit economics.',
 93, 28, true, 326),

('User Journey Analysis',
 'Mapuje i analizuje ścieżki użytkownika w produkcie cyfrowym.',
 'analysis', 'intermediate',
 ARRAY['user-journey','product-analytics','ux','behavioral'],
 '[{"id":"1","content":"You are a product analyst who maps user journeys using behavioral data to identify friction points and optimization opportunities that improve activation and retention.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product: {{product}}\nJourney to analyze: {{journey}}\nBehavioral data: {{data}}\nSuccess metric: {{success}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Journey map (touchpoints, actions, emotions) 2) Funnel drop-off at each step 3) Time-to-complete analysis 4) User behavior clustering (fast/stuck/churned paths) 5) Friction point identification 6) Feature discovery analysis 7) Aha moment validation 8) Personalization opportunities 9) Redesign recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"product","type":"text","label":"Produkt","defaultValue":"project management SaaS"},{"name":"journey","type":"text","label":"Ścieżka do analizy","defaultValue":"signup → first project created → invite team"},{"name":"data","type":"textarea","label":"Dane behawioralne","defaultValue":""},{"name":"success","type":"text","label":"Metryka sukcesu","defaultValue":"team invited within 7 days of signup"}]'::jsonb,
 '## Role\nProduct analyst — user journeys.\n\n## Journey\n{{journey}}\n\n## Task\nJourney map, drop-off, friction, aha moment, redesign recommendations.',
 88, 19, false, 327),

('Break-even Analysis',
 'Przeprowadza analizę progu rentowności dla nowych produktów i inicjatyw.',
 'analysis', 'intermediate',
 ARRAY['finance','break-even','business-planning','pricing'],
 '[{"id":"1","content":"You are a financial consultant who builds break-even models for new products and business initiatives to guide investment decisions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Product/initiative: {{initiative}}\nFixed costs: {{fixed_costs}}\nVariable costs: {{variable_costs}}\nPrice point: {{price}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Calculate: 1) Break-even point (units and revenue) 2) Contribution margin analysis 3) Break-even timeline under different growth scenarios 4) Sensitivity to price changes (±10%, ±20%) 5) Fixed cost reduction impact 6) Variable cost optimization opportunities 7) Margin of safety 8) Visual break-even chart description 9) Go/no-go recommendation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"initiative","type":"text","label":"Produkt/inicjatywa","defaultValue":"new SaaS product tier"},{"name":"fixed_costs","type":"text","label":"Koszty stałe","defaultValue":"$15,000/month (team, infrastructure)"},{"name":"variable_costs","type":"text","label":"Koszty zmienne","defaultValue":"$5 per customer/month"},{"name":"price","type":"text","label":"Cena","defaultValue":"$49/month"}]'::jsonb,
 '## Role\nFinancial consultant — break-even.\n\n## Initiative\n{{initiative}}\n\n## Task\nBreak-even units/revenue, sensitivity analysis, margin of safety, recommendation.',
 87, 16, false, 328),

('Cohort Retention Analysis',
 'Analizuje retencję kohort użytkowników i identyfikuje wzorce.',
 'analysis', 'advanced',
 ARRAY['cohort-analysis','retention','product','growth'],
 '[{"id":"1","content":"You are a growth analyst who builds cohort retention models to understand user behavior over time and identify the most impactful retention interventions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Cohort data: {{cohort_data}}\nProduct: {{product}}\nTime buckets: {{time_buckets}}\nSegment: {{segment}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Cohort retention table interpretation 2) L1/L7/L30 retention benchmarking 3) Best vs worst cohort comparison (what changed?) 4) Retention curve shape analysis (resurrection?) 5) Feature adoption correlation with retention 6) Notification/engagement campaign impact 7) Predicted LTV by cohort 8) Retention improvement experiments","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"cohort_data","type":"textarea","label":"Dane kohort","defaultValue":""},{"name":"product","type":"text","label":"Produkt","defaultValue":"mobile app"},{"name":"time_buckets","type":"text","label":"Okresy czasu","defaultValue":"Day 1, 7, 14, 30, 60, 90"},{"name":"segment","type":"text","label":"Segment użytkowników","defaultValue":"all users / paid users"}]'::jsonb,
 '## Role\nGrowth analyst — cohort retention.\n\n## Data\n{{cohort_data}}\n\n## Task\nL1/L7/L30 benchmarks, best/worst cohort, feature correlation, experiments.',
 91, 22, true, 329),

('Vendor Evaluation Matrix',
 'Tworzy strukturowany framework oceny i wyboru dostawców.',
 'analysis', 'intermediate',
 ARRAY['vendor-management','procurement','evaluation','decision-making'],
 '[{"id":"1","content":"You are a procurement specialist who builds objective vendor evaluation frameworks that minimize bias and ensure the best long-term partnerships.","order_index":0,"section_slug":"role"},{"id":"2","content":"Category: {{category}}\nVendors to compare: {{vendors}}\nMust-have criteria: {{must_haves}}\nBudget: {{budget}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create: 1) Weighted evaluation criteria matrix 2) Scoring rubric (1-5) per criterion 3) Total cost of ownership model 4) Risk assessment per vendor 5) Reference check questions 6) POC/trial evaluation plan 7) Contract negotiation leverage points 8) Final recommendation with rationale","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"category","type":"text","label":"Kategoria zakupowa","defaultValue":"CRM software"},{"name":"vendors","type":"text","label":"Porównywani dostawcy","defaultValue":"Salesforce, HubSpot, Pipedrive"},{"name":"must_haves","type":"text","label":"Wymagania konieczne","defaultValue":"API access, GDPR compliance, Slack integration"},{"name":"budget","type":"text","label":"Budżet","defaultValue":"$20,000/year"}]'::jsonb,
 '## Role\nProcurement specialist.\n\n## Category\n{{category}}\n\n## Task\nWeighted matrix, TCO, risk assessment, POC plan, negotiation points.',
 87, 14, false, 330),

('Gap Analysis Framework',
 'Identyfikuje luki między aktualnym a pożądanym stanem organizacji.',
 'analysis', 'intermediate',
 ARRAY['gap-analysis','strategy','organizational-development','planning'],
 '[{"id":"1","content":"You are a management consultant who conducts gap analyses to help organizations identify exactly what needs to change to reach their goals.","order_index":0,"section_slug":"role"},{"id":"2","content":"Current state: {{current_state}}\nDesired future state: {{future_state}}\nOrganization: {{organization}}\nTime to close gap: {{timeframe}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Current state assessment (capabilities, processes, resources) 2) Future state definition (clear success criteria) 3) Gap identification across dimensions (people, process, technology, data) 4) Gap prioritization by business impact 5) Root cause for each gap 6) Initiative mapping to close gaps 7) Quick wins vs long-term investments 8) Change management considerations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"current_state","type":"textarea","label":"Aktualny stan","defaultValue":""},{"name":"future_state","type":"text","label":"Pożądany stan","defaultValue":""},{"name":"organization","type":"text","label":"Organizacja","defaultValue":""},{"name":"timeframe","type":"text","label":"Czas zamknięcia luki","defaultValue":"12 months"}]'::jsonb,
 '## Role\nManagement consultant — gap analysis.\n\n## Gap\n{{current_state}} → {{future_state}}\n\n## Task\nGap by dimension, prioritization, root causes, initiatives, quick wins.',
 86, 17, false, 331),

('Brand Health Monitor',
 'Mierzy i analizuje zdrowie marki w mediach i świadomości konsumentów.',
 'analysis', 'intermediate',
 ARRAY['brand','reputation','social-listening','marketing'],
 '[{"id":"1","content":"You are a brand strategist who tracks brand health metrics, sentiment, and competitive perception to protect and grow brand equity.","order_index":0,"section_slug":"role"},{"id":"2","content":"Brand: {{brand}}\nData sources: {{sources}}\nCompetitors: {{competitors}}\nKey concerns: {{concerns}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Brand awareness tracking (aided/unaided) 2) Brand sentiment over time 3) Share of voice vs competitors 4) Brand association mapping 5) Net sentiment score 6) Crisis/opportunity signals 7) Influencer and media coverage analysis 8) Brand health scorecard 9) Protective and growth recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"brand","type":"text","label":"Marka","defaultValue":""},{"name":"sources","type":"text","label":"Źródła danych","defaultValue":"social media, review sites, surveys, PR mentions"},{"name":"competitors","type":"text","label":"Konkurenci","defaultValue":""},{"name":"concerns","type":"text","label":"Główne obawy","defaultValue":"negative sentiment, declining awareness"}]'::jsonb,
 '## Role\nBrand health analyst.\n\n## Brand\n{{brand}}\n\n## Task\nAwareness, sentiment, share of voice, associations, scorecard, recommendations.',
 85, 13, false, 332),

('Subscription Analytics Report',
 'Analizuje metryki subskrypcyjne i identyfikuje możliwości wzrostu.',
 'analysis', 'advanced',
 ARRAY['subscriptions','revenue','saas','growth-analytics'],
 '[{"id":"1","content":"You are a subscription business analyst who understands the nuances of recurring revenue models and builds clear pictures of business health.","order_index":0,"section_slug":"role"},{"id":"2","content":"Subscription data: {{data}}\nProduct: {{product}}\nPricing tiers: {{tiers}}\nPeriod: {{period}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) MRR movements waterfall (new, expansion, contraction, churn, reactivation) 2) Plan tier migration analysis 3) Subscription age distribution 4) Upgrade/downgrade triggers 5) Payment failure and recovery rates 6) Annual vs monthly plan split 7) Seasonal patterns 8) Revenue forecasting 9) Expansion revenue opportunities","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"data","type":"textarea","label":"Dane subskrypcji","defaultValue":""},{"name":"product","type":"text","label":"Produkt","defaultValue":""},{"name":"tiers","type":"text","label":"Plany cenowe","defaultValue":"Starter $29, Pro $79, Business $199"},{"name":"period","type":"text","label":"Okres analizy","defaultValue":"last 12 months"}]'::jsonb,
 '## Role\nSubscription business analyst.\n\n## Data\n{{data}}\n\n## Task\nMRR waterfall, tier migration, payment failures, forecast, expansion opps.',
 90, 19, true, 333),

('Market Size Estimation',
 'Szacuje rozmiar rynku metodologią bottom-up i top-down.',
 'analysis', 'advanced',
 ARRAY['tam','sam','som','market-sizing','startup'],
 '[{"id":"1","content":"You are a market sizing expert who builds credible TAM/SAM/SOM analyses using both top-down and bottom-up methodologies for investor decks and strategic planning.","order_index":0,"section_slug":"role"},{"id":"2","content":"Market to size: {{market}}\nGeography: {{geography}}\nProduct/service: {{product}}\nYear: {{year}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Estimate: 1) Top-down TAM (industry reports approach with sources) 2) Bottom-up TAM (unit economics × addressable customers) 3) SAM (your specific segment) 4) SOM (realistically capturable in 3-5 years) 5) Key assumptions and sensitivity 6) Growth rate projection 7) Comparison with public company revenues 8) Investor-ready narrative","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"market","type":"text","label":"Rynek do oszacowania","defaultValue":"AI-powered code review tools"},{"name":"geography","type":"text","label":"Obszar geograficzny","defaultValue":"Global / North America / Europe"},{"name":"product","type":"text","label":"Produkt/usługa","defaultValue":""},{"name":"year","type":"text","label":"Rok bazowy","defaultValue":"2025"}]'::jsonb,
 '## Role\nMarket sizing expert.\n\n## Market\n{{market}} in {{geography}}\n\n## Task\nTop-down + bottom-up TAM, SAM, SOM, assumptions, investor narrative.',
 91, 21, false, 334),

('Customer Lifetime Value Model',
 'Buduje model Customer Lifetime Value dla optymalizacji CAC i retencji.',
 'analysis', 'advanced',
 ARRAY['clv','ltv','customer-analytics','revenue-modeling'],
 '[{"id":"1","content":"You are a customer economics analyst who builds LTV models to optimize acquisition spending and identify the most valuable customer segments.","order_index":0,"section_slug":"role"},{"id":"2","content":"Business model: {{model}}\nCustomer data: {{data}}\nSegments: {{segments}}\nGoal: {{goal}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Build model: 1) LTV calculation methodology (simple, predictive, probabilistic) 2) LTV by segment and acquisition channel 3) LTV:CAC ratio analysis 4) Payback period by segment 5) Expansion revenue impact on LTV 6) Retention curve integration 7) LTV improvement levers 8) Maximum CAC recommendation per segment","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"model","type":"text","label":"Model biznesowy","defaultValue":"B2B SaaS subscription"},{"name":"data","type":"textarea","label":"Dane klientów","defaultValue":""},{"name":"segments","type":"text","label":"Segmenty","defaultValue":"SMB, Mid-Market, Enterprise"},{"name":"goal","type":"text","label":"Cel analizy","defaultValue":"optimize marketing spend allocation"}]'::jsonb,
 '## Role\nCustomer economics analyst — LTV.\n\n## Model\n{{model}}\n\n## Task\nLTV by segment, LTV:CAC, payback, expansion impact, max CAC recommendation.',
 92, 23, false, 335),

('Recruiting Funnel Analysis',
 'Analizuje lejek rekrutacyjny i identyfikuje wąskie gardła.',
 'analysis', 'intermediate',
 ARRAY['recruiting','talent-acquisition','hr-analytics','hiring'],
 '[{"id":"1","content":"You are an HR analytics specialist who optimizes recruiting processes using conversion data, time-to-hire analysis, and offer acceptance drivers.","order_index":0,"section_slug":"role"},{"id":"2","content":"Recruiting data: {{data}}\nRoles: {{roles}}\nTime period: {{period}}\nCurrent challenges: {{challenges}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Funnel conversion rates (application→screen→interview→offer→accept) 2) Stage-by-stage drop-off causes 3) Time-to-hire by role and department 4) Source quality (cost per hire, quality of hire by channel) 5) Offer acceptance rate and decline reasons 6) Diversity funnel analysis 7) Interviewer calibration issues 8) Process improvement recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"data","type":"textarea","label":"Dane rekrutacyjne","defaultValue":""},{"name":"roles","type":"text","label":"Rekrutowane stanowiska","defaultValue":"Software Engineers, Product Managers"},{"name":"period","type":"text","label":"Okres","defaultValue":"last 6 months"},{"name":"challenges","type":"text","label":"Aktualne wyzwania","defaultValue":"low offer acceptance, long time-to-hire"}]'::jsonb,
 '## Role\nHR analytics — recruiting.\n\n## Funnel\n{{data}}\n\n## Task\nConversion rates, drop-off causes, source quality, diversity, improvements.',
 86, 15, false, 336),

('Due Diligence Checklist',
 'Tworzy kompleksową listę due diligence dla inwestycji i przejęć.',
 'analysis', 'advanced',
 ARRAY['due-diligence','m&a','investment','legal','finance'],
 '[{"id":"1","content":"You are an M&A analyst and investment due diligence specialist who ensures no critical risk is overlooked in investment or acquisition processes.","order_index":0,"section_slug":"role"},{"id":"2","content":"Transaction type: {{transaction}}\nTarget company: {{target}}\nDeal size: {{size}}\nKey concerns: {{concerns}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Create checklist covering: 1) Financial due diligence (P&L, balance sheet, cash flow, revenue quality) 2) Legal (corporate structure, IP, contracts, litigation) 3) Commercial (market position, customer concentration, churn) 4) Technology (architecture, debt, security) 5) HR (team, equity, retention risks) 6) Regulatory compliance 7) Environmental/ESG 8) Integration risk assessment","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"transaction","type":"text","label":"Typ transakcji","defaultValue":"Series A investment / M&A acquisition"},{"name":"target","type":"text","label":"Podmiot docelowy","defaultValue":"B2B SaaS startup, $3M ARR"},{"name":"size","type":"text","label":"Wartość transakcji","defaultValue":""},{"name":"concerns","type":"text","label":"Kluczowe obawy","defaultValue":"customer concentration, IP ownership"}]'::jsonb,
 '## Role\nM&A due diligence specialist.\n\n## Transaction\n{{transaction}} — {{target}}\n\n## Task\nChecklist: financial, legal, commercial, tech, HR, regulatory, ESG.',
 93, 17, false, 337),

('Product Feature Prioritization',
 'Priorytetyzuje funkcje produktowe według wpływu i wysiłku implementacji.',
 'analysis', 'intermediate',
 ARRAY['product-management','prioritization','roadmap','rice'],
 '[{"id":"1","content":"You are a product manager who uses data-driven frameworks to prioritize features objectively, balancing user needs with business impact.","order_index":0,"section_slug":"role"},{"id":"2","content":"Feature list: {{features}}\nPrioritization goal: {{goal}}\nConstraints: {{constraints}}\nUser research insights: {{research}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Prioritize using: 1) RICE scoring (Reach × Impact × Confidence / Effort) 2) ICE score comparison 3) MoSCoW categorization 4) Value vs complexity 2×2 matrix 5) User story mapping alignment 6) Revenue impact estimation per feature 7) Technical dependency mapping 8) Final ranked roadmap with rationale","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"features","type":"textarea","label":"Lista funkcji do priorytetyzacji","defaultValue":""},{"name":"goal","type":"text","label":"Cel priorytetyzacji","defaultValue":"maximize retention impact in Q1"},{"name":"constraints","type":"text","label":"Ograniczenia","defaultValue":"team of 3 engineers, 6-week sprint"},{"name":"research","type":"textarea","label":"Wnioski z badań użytkownika","defaultValue":""}]'::jsonb,
 '## Role\nProduct manager — feature prioritization.\n\n## Features\n{{features}}\n\n## Task\nRICE, ICE, MoSCoW, value/complexity matrix, ranked roadmap.',
 89, 29, true, 338),

('Cost-Benefit Analysis',
 'Przeprowadza analizę kosztów i korzyści dla decyzji biznesowych.',
 'analysis', 'intermediate',
 ARRAY['cost-benefit','decision-making','finance','strategy'],
 '[{"id":"1","content":"You are a business analyst who conducts rigorous cost-benefit analyses that capture both tangible and intangible factors for strategic decisions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Decision: {{decision}}\nOptions: {{options}}\nTime horizon: {{horizon}}\nKey stakeholders: {{stakeholders}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Direct costs per option (one-time + recurring) 2) Indirect and opportunity costs 3) Quantified benefits (revenue, cost savings, time savings) 4) Intangible benefits (brand, morale, strategic positioning) 5) Risk-adjusted NPV per option 6) Non-financial factors weighting 7) Scenario analysis (best/base/worst) 8) Final recommendation with confidence level","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"decision","type":"text","label":"Decyzja do analizy","defaultValue":"build vs buy vs outsource"},{"name":"options","type":"text","label":"Opcje","defaultValue":""},{"name":"horizon","type":"text","label":"Horyzont analizy","defaultValue":"3 years"},{"name":"stakeholders","type":"text","label":"Interesariusze","defaultValue":"executive team, finance, engineering"}]'::jsonb,
 '## Role\nBusiness analyst — cost-benefit.\n\n## Decision\n{{decision}}\n\n## Task\nDirect/indirect costs, quantified benefits, NPV, scenarios, recommendation.',
 87, 19, false, 339),

('API Performance Report',
 'Analizuje wydajność API i identyfikuje problemy z latencją i dostępnością.',
 'analysis', 'advanced',
 ARRAY['api','performance','sla','monitoring','observability'],
 '[{"id":"1","content":"You are a site reliability engineer who analyzes API performance metrics to ensure SLA compliance and identify optimization opportunities.","order_index":0,"section_slug":"role"},{"id":"2","content":"API metrics: {{metrics}}\nSLA targets: {{sla}}\nTime period: {{period}}\nCritical endpoints: {{endpoints}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Latency distribution (p50/p95/p99/p999) 2) Error rate by endpoint and error type 3) Throughput trends and peak analysis 4) SLA breach incidents 5) Slowest endpoints (ranked) 6) Dependency latency contribution 7) Geographic performance variation 8) Correlation with deployment events 9) Capacity planning recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"metrics","type":"textarea","label":"Metryki API","defaultValue":""},{"name":"sla","type":"text","label":"Cele SLA","defaultValue":"p99 < 200ms, error rate < 0.1%, uptime 99.9%"},{"name":"period","type":"text","label":"Okres analizy","defaultValue":"last 30 days"},{"name":"endpoints","type":"text","label":"Krytyczne endpointy","defaultValue":""}]'::jsonb,
 '## Role\nSRE — API performance.\n\n## SLA\n{{sla}}\n\n## Task\nLatency distribution, error rates, slowest endpoints, capacity planning.',
 90, 16, false, 340),

('Supply Chain Analysis',
 'Analizuje łańcuch dostaw i identyfikuje ryzyka i możliwości optymalizacji.',
 'analysis', 'advanced',
 ARRAY['supply-chain','operations','logistics','risk-management'],
 '[{"id":"1","content":"You are a supply chain analyst who maps supply chain vulnerabilities, optimizes inventory levels, and improves supplier relationships.","order_index":0,"section_slug":"role"},{"id":"2","content":"Supply chain: {{supply_chain}}\nKey suppliers: {{suppliers}}\nCurrent issues: {{issues}}\nIndustry: {{industry}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Supply chain mapping (tier 1/2/3 suppliers) 2) Single-source dependencies and risks 3) Lead time analysis 4) Inventory turnover and holding costs 5) Supplier scorecards (quality, delivery, price) 6) Geopolitical/climate disruption risks 7) Cost reduction opportunities 8) Resilience improvement strategies","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"supply_chain","type":"text","label":"Opis łańcucha dostaw","defaultValue":"electronics manufacturer supply chain"},{"name":"suppliers","type":"text","label":"Kluczowi dostawcy","defaultValue":""},{"name":"issues","type":"text","label":"Aktualne problemy","defaultValue":"delivery delays, cost increases"},{"name":"industry","type":"text","label":"Branża","defaultValue":"manufacturing / retail / tech hardware"}]'::jsonb,
 '## Role\nSupply chain analyst.\n\n## Supply chain\n{{supply_chain}}\n\n## Task\nMapping, single-source risks, lead times, scorecards, resilience strategies.',
 88, 12, false, 341),

('Web Traffic Analysis',
 'Analizuje ruch na stronie i identyfikuje możliwości wzrostu.',
 'analysis', 'beginner',
 ARRAY['web-analytics','traffic','ga4','conversion'],
 '[{"id":"1","content":"You are a web analytics specialist who transforms GA4 data into actionable insights for improving traffic, engagement, and conversions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Website: {{website}}\nAnalytics data: {{data}}\nGoals: {{goals}}\nPeriod: {{period}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Traffic sources performance (organic, paid, social, direct, referral) 2) Landing page performance 3) Engagement metrics (bounce rate, session duration, pages/session) 4) Conversion funnel analysis 5) Top exit pages and reasons 6) New vs returning visitor behavior 7) Device and geographic breakdown 8) Quick wins and 30-day action plan","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"website","type":"text","label":"Strona internetowa","defaultValue":""},{"name":"data","type":"textarea","label":"Dane analityczne (GA4 lub opis)","defaultValue":""},{"name":"goals","type":"text","label":"Cele","defaultValue":"increase conversions, reduce bounce rate"},{"name":"period","type":"text","label":"Okres","defaultValue":"last 3 months"}]'::jsonb,
 '## Role\nWeb analytics specialist — GA4.\n\n## Website\n{{website}}\n\n## Task\nSource performance, landing pages, funnels, exit analysis, 30-day plan.',
 84, 25, false, 342),

('Stakeholder Analysis',
 'Identyfikuje i analizuje interesariuszy projektu dla efektywnego zarządzania.',
 'analysis', 'intermediate',
 ARRAY['stakeholder-management','project-management','strategy','communication'],
 '[{"id":"1","content":"You are a change management consultant who maps stakeholder landscapes to ensure projects succeed through proactive engagement and communication.","order_index":0,"section_slug":"role"},{"id":"2","content":"Project: {{project}}\nOrganization: {{organization}}\nChange magnitude: {{change}}\nTimeline: {{timeline}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Stakeholder identification (all affected parties) 2) Power/Interest grid positioning 3) Current vs desired attitude assessment 4) Influence network mapping 5) Key concerns and motivations per group 6) Resistance risk assessment 7) Engagement strategy per stakeholder type 8) Communication plan recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"project","type":"text","label":"Projekt","defaultValue":"ERP system implementation"},{"name":"organization","type":"text","label":"Organizacja","defaultValue":"500-person manufacturing company"},{"name":"change","type":"text","label":"Skala zmiany","defaultValue":"high — affects all departments"},{"name":"timeline","type":"text","label":"Harmonogram","defaultValue":"18 months"}]'::jsonb,
 '## Role\nChange management consultant.\n\n## Project\n{{project}}\n\n## Task\nPower/interest grid, attitude assessment, resistance risks, engagement plan.',
 86, 14, false, 343),

('Trend Forecasting Analysis',
 'Prognozuje trendy technologiczne i rynkowe metodologią futures thinking.',
 'analysis', 'advanced',
 ARRAY['forecasting','trends','strategy','futures-thinking'],
 '[{"id":"1","content":"You are a futurist and trend analyst who uses signals scanning, scenario planning, and expert synthesis to forecast industry trends for strategic planning.","order_index":0,"section_slug":"role"},{"id":"2","content":"Industry: {{industry}}\nForecast horizon: {{horizon}}\nForce area: {{forces}}\nDecision context: {{decision}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Forecast: 1) Weak signals and emerging trends scan 2) STEEP analysis (Social, Technological, Economic, Environmental, Political) 3) Trend convergence analysis 4) Three scenarios (optimistic/base/disruptive) 5) Technology adoption curve positioning 6) Strategic implications per scenario 7) Early indicators to monitor 8) Strategic options and hedging strategies","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"industry","type":"text","label":"Branża","defaultValue":"enterprise software / fintech / healthcare"},{"name":"horizon","type":"text","label":"Horyzont prognozy","defaultValue":"3-5 years"},{"name":"forces","type":"text","label":"Obszary sił","defaultValue":"technology, regulation, consumer behavior"},{"name":"decision","type":"text","label":"Kontekst decyzji","defaultValue":"product roadmap planning"}]'::jsonb,
 '## Role\nFuturist and trend analyst.\n\n## Industry\n{{industry}} ({{horizon}} horizon)\n\n## Task\nSTEEP, 3 scenarios, adoption curve, strategic options, early indicators.',
 91, 18, true, 344),

('Budget Variance Analysis',
 'Analizuje odchylenia budżetowe i identyfikuje ich przyczyny.',
 'analysis', 'intermediate',
 ARRAY['budgeting','finance','variance-analysis','controlling'],
 '[{"id":"1","content":"You are a financial controller who conducts budget variance analyses, providing management with clear explanations of financial performance vs plan.","order_index":0,"section_slug":"role"},{"id":"2","content":"Budget data: {{budget_data}}\nActual results: {{actual}}\nPeriod: {{period}}\nDepartments: {{departments}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Variance summary table (favorable/unfavorable) 2) Volume vs price vs mix variance decomposition 3) Largest variance explanations (root causes) 4) One-time vs recurring variances 5) Forecast revision based on actuals 6) Department-level accountability 7) Corrective action recommendations 8) Early warning signals for next period","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"budget_data","type":"textarea","label":"Dane budżetowe","defaultValue":""},{"name":"actual","type":"textarea","label":"Dane rzeczywiste","defaultValue":""},{"name":"period","type":"text","label":"Okres","defaultValue":"Q1 2026"},{"name":"departments","type":"text","label":"Działy","defaultValue":"Sales, Marketing, R&D, Operations"}]'::jsonb,
 '## Role\nFinancial controller.\n\n## Period\n{{period}}\n\n## Task\nVariance table, volume/price/mix decomposition, root causes, forecast revision.',
 88, 15, false, 345),

('Security Risk Audit',
 'Audytuje bezpieczeństwo organizacji i tworzy plan zarządzania ryzykiem.',
 'analysis', 'advanced',
 ARRAY['security','risk-audit','compliance','iso27001'],
 '[{"id":"1","content":"You are a cybersecurity risk analyst who conducts comprehensive security audits and prioritizes remediation based on business risk exposure.","order_index":0,"section_slug":"role"},{"id":"2","content":"Organization: {{organization}}\nScope: {{scope}}\nCurrent controls: {{controls}}\nCompliance requirements: {{compliance}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Audit: 1) Asset inventory and criticality ranking 2) Threat landscape specific to industry 3) Vulnerability assessment by domain (network, application, IAM, data, physical) 4) Control gap analysis vs framework (ISO 27001, NIST, SOC2) 5) Risk register (likelihood × impact matrix) 6) Remediation priority ranking 7) Quick wins (0-30 days) vs strategic investments 8) Compliance roadmap","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"organization","type":"text","label":"Organizacja","defaultValue":"SaaS company, 150 employees"},{"name":"scope","type":"text","label":"Zakres audytu","defaultValue":"full IT infrastructure, cloud, applications"},{"name":"controls","type":"text","label":"Istniejące kontrole","defaultValue":"MFA, VPN, basic firewall"},{"name":"compliance","type":"text","label":"Wymagania compliance","defaultValue":"SOC2 Type II, GDPR"}]'::jsonb,
 '## Role\nCybersecurity risk analyst.\n\n## Organization\n{{organization}}\n\n## Task\nAsset criticality, threat landscape, control gaps, risk register, compliance roadmap.',
 93, 20, true, 346),

('HR Analytics Workforce Report',
 'Analizuje dane HR i tworzy raport o sile roboczej i trendach.',
 'analysis', 'intermediate',
 ARRAY['hr-analytics','workforce','planning','talent'],
 '[{"id":"1","content":"You are an HR analytics director who transforms people data into strategic workforce insights for executive decision-making.","order_index":0,"section_slug":"role"},{"id":"2","content":"HR data: {{hr_data}}\nOrganization: {{organization}}\nStrategic goals: {{goals}}\nPeriod: {{period}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Report on: 1) Headcount and growth trends 2) Turnover analysis (voluntary/involuntary, by department/tenure/level) 3) Time-to-hire and cost-per-hire 4) Compensation equity analysis 5) Training ROI and skill gap assessment 6) Absenteeism and productivity correlation 7) Diversity metrics trend 8) Workforce planning forecast (12-24 months) 9) Top 5 people risk areas","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"hr_data","type":"textarea","label":"Dane HR","defaultValue":""},{"name":"organization","type":"text","label":"Organizacja","defaultValue":"tech company, 200 employees"},{"name":"goals","type":"text","label":"Cele strategiczne","defaultValue":"scale to 300 employees, improve diversity"},{"name":"period","type":"text","label":"Okres raportu","defaultValue":"Annual 2025"}]'::jsonb,
 '## Role\nHR analytics director.\n\n## Data\n{{hr_data}}\n\n## Task\nHeadcount, turnover, compensation equity, skill gaps, workforce forecast.',
 87, 13, false, 347),

('Growth Experiment Analyzer',
 'Analizuje eksperymenty wzrostowe i wyciąga wnioski do skalowania.',
 'analysis', 'advanced',
 ARRAY['growth-hacking','experiments','product-led-growth','analytics'],
 '[{"id":"1","content":"You are a growth analyst who evaluates growth experiments using rigorous statistical methods and extracts generalizable learnings to build playbooks.","order_index":0,"section_slug":"role"},{"id":"2","content":"Experiments run: {{experiments}}\nResults: {{results}}\nHypotheses: {{hypotheses}}\nGrowth goal: {{goal}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Analyze: 1) Statistical validity of each experiment 2) Effect size and practical significance 3) Segment-level heterogeneity 4) Unexpected side effects (guardrail metrics) 5) Successful pattern extraction 6) Failed experiment learnings 7) Compound experiment opportunities 8) Scaled impact projection 9) Next experiment recommendations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"experiments","type":"textarea","label":"Przeprowadzone eksperymenty","defaultValue":""},{"name":"results","type":"textarea","label":"Wyniki eksperymentów","defaultValue":""},{"name":"hypotheses","type":"text","label":"Hipotezy","defaultValue":""},{"name":"goal","type":"text","label":"Cel wzrostowy","defaultValue":"improve activation rate 20%"}]'::jsonb,
 '## Role\nGrowth analyst.\n\n## Experiments\n{{experiments}}\n\n## Task\nStatistical validity, effect sizes, patterns, compound opps, next experiments.',
 91, 21, true, 348),

('Conversion Rate Optimization Report',
 'Analizuje CRO i tworzy priorytetyzowany plan optymalizacji konwersji.',
 'analysis', 'intermediate',
 ARRAY['cro','conversion','ux','analytics','testing'],
 '[{"id":"1","content":"You are a CRO specialist who uses qualitative and quantitative research to identify conversion barriers and design experiments that systematically improve rates.","order_index":0,"section_slug":"role"},{"id":"2","content":"Page/funnel: {{target}}\nCurrent conversion rate: {{current_cr}}\nTraffic volume: {{traffic}}\nExisting research: {{research}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Audit: 1) Heuristic evaluation (clarity, friction, motivation, anxiety) 2) Analytics-identified drop-off points 3) Qualitative insights (heatmaps, session recordings, surveys) 4) Trust and credibility signals assessment 5) Value proposition clarity score 6) Mobile experience issues 7) Prioritized test backlog (ICE scored) 8) Test designs for top 5 opportunities","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"target","type":"text","label":"Strona/lejek do optymalizacji","defaultValue":"pricing page"},{"name":"current_cr","type":"text","label":"Aktualny wskaźnik konwersji","defaultValue":"2.3%"},{"name":"traffic","type":"text","label":"Ruch miesięczny","defaultValue":"10,000 unique visitors"},{"name":"research","type":"textarea","label":"Istniejące badania","defaultValue":""}]'::jsonb,
 '## Role\nCRO specialist.\n\n## Target\n{{target}} (CR: {{current_cr}})\n\n## Task\nHeuristic evaluation, analytics, qualitative, ICE-scored test backlog.',
 89, 26, true, 349);
