-- Migration: 200 high-quality prompts — Part 1: Coding (50 prompts)
-- Date: 2026-06-11

INSERT INTO public.system_templates (title, description, category, difficulty, tags, blocks, variables, content_md, ai_score, fork_count, is_featured, order_index) VALUES

('TypeScript Interface Designer',
 'Projektuje typy i interfejsy TypeScript na podstawie opisu struktury danych.',
 'coding', 'intermediate',
 ARRAY['typescript','types','interfaces','architecture'],
 '[{"id":"1","content":"You are an expert TypeScript architect with deep knowledge of type system design, generics, and best practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design TypeScript interfaces and types for the following data structure:\n\nDescription: {{description}}\nUse case: {{use_case}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Complete interface/type definitions with JSDoc comments 2) Generic variants where appropriate 3) Utility types (Partial, Required, Pick, etc.) 4) Example usage code 5) Potential edge cases and how to handle them","order_index":2,"section_slug":"task"},{"id":"4","content":"Format as TypeScript code blocks with explanations. Include a summary of design decisions.","order_index":3,"section_slug":"format"}]'::jsonb,
 '[{"name":"description","type":"textarea","label":"Opis struktury danych","defaultValue":""},{"name":"use_case","type":"text","label":"Przypadek użycia","defaultValue":"REST API response"}]'::jsonb,
 '## Role\nYou are an expert TypeScript architect.\n\n## Context\nDescription: {{description}}\nUse case: {{use_case}}\n\n## Task\nDesign complete TypeScript interfaces with generics, utility types, and JSDoc.\n\n## Format\nTypeScript code blocks with design decision summary.',
 88, 12, true, 100),

('React Custom Hook Generator',
 'Tworzy reużywalne hooki React z logiką stanu i efektów ubocznych.',
 'coding', 'intermediate',
 ARRAY['react','hooks','typescript','state-management'],
 '[{"id":"1","content":"You are a senior React developer specializing in custom hooks, state management patterns, and React 19 best practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create a custom React hook for the following functionality:\n\nFeature: {{feature}}\nDependencies available: {{dependencies}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Implement the hook with: 1) Full TypeScript types 2) Proper cleanup in useEffect 3) Error and loading states 4) Memoization with useMemo/useCallback 5) Unit test examples","order_index":2,"section_slug":"task"},{"id":"4","content":"Return the hook code, its TypeScript interface, and a usage example component.","order_index":3,"section_slug":"format"}]'::jsonb,
 '[{"name":"feature","type":"text","label":"Funkcjonalność hooka","defaultValue":"data fetching with pagination"},{"name":"dependencies","type":"text","label":"Dostępne biblioteki","defaultValue":"React Query, Zustand"}]'::jsonb,
 '## Role\nSenior React developer.\n\n## Feature\n{{feature}}\n\n## Task\nCustom hook with TypeScript, cleanup, error states, memoization, and tests.',
 91, 24, true, 101),

('SQL Query Optimizer',
 'Analizuje i optymalizuje zapytania SQL pod kątem wydajności.',
 'coding', 'advanced',
 ARRAY['sql','postgresql','optimization','performance','database'],
 '[{"id":"1","content":"You are a database performance expert specializing in PostgreSQL query optimization, indexing strategies, and execution plan analysis.","order_index":0,"section_slug":"role"},{"id":"2","content":"Optimize the following SQL query:\n\n```sql\n{{query}}\n```\n\nDatabase: {{database}}\nTable sizes: {{table_sizes}}\nCurrent execution time: {{execution_time}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Analysis of the current query issues 2) Optimized query version 3) Index recommendations with CREATE INDEX statements 4) EXPLAIN ANALYZE interpretation 5) Alternative approaches if applicable","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"query","type":"textarea","label":"Zapytanie SQL do optymalizacji","defaultValue":"SELECT * FROM orders WHERE ..."},{"name":"database","type":"text","label":"Typ bazy danych","defaultValue":"PostgreSQL 15"},{"name":"table_sizes","type":"text","label":"Rozmiary tabel","defaultValue":"orders: 5M rows"},{"name":"execution_time","type":"text","label":"Aktualny czas wykonania","defaultValue":"8s"}]'::jsonb,
 '## Role\nDatabase performance expert.\n\n## Query\n```sql\n{{query}}\n```\n\n## Task\nOptimize with execution plan analysis, index recommendations, and alternatives.',
 93, 31, true, 102),

('Python Automation Script Writer',
 'Pisze skrypty Python automatyzujące powtarzalne zadania.',
 'coding', 'beginner',
 ARRAY['python','automation','scripting','productivity'],
 '[{"id":"1","content":"You are an experienced Python developer who writes clean, well-documented automation scripts with proper error handling.","order_index":0,"section_slug":"role"},{"id":"2","content":"Write a Python script to automate the following task:\n\nTask: {{task}}\nInput: {{input_description}}\nExpected output: {{output_description}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Clear comments 2) Error handling with try/except 3) Logging 4) Command-line argument parsing with argparse 5) Type hints 6) Docstrings","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"task","type":"text","label":"Zadanie do automatyzacji","defaultValue":"rename files in bulk based on pattern"},{"name":"input_description","type":"text","label":"Dane wejściowe","defaultValue":"folder path, pattern"},{"name":"output_description","type":"text","label":"Oczekiwany wynik","defaultValue":"renamed files with log"}]'::jsonb,
 '## Role\nPython developer writing clean automation scripts.\n\n## Task\n{{task}}\n\n## Requirements\nError handling, logging, argparse, type hints, docstrings.',
 85, 18, false, 103),

('Docker Compose Stack Designer',
 'Projektuje konfigurację Docker Compose dla złożonych aplikacji wielousługowych.',
 'coding', 'intermediate',
 ARRAY['docker','docker-compose','devops','containers','infrastructure'],
 '[{"id":"1","content":"You are a DevOps engineer with deep expertise in containerization, Docker best practices, and multi-service orchestration.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design a Docker Compose configuration for:\n\nApplication: {{app_description}}\nServices needed: {{services}}\nEnvironment: {{environment}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Complete docker-compose.yml with all services 2) Dockerfile for custom services 3) Health checks for each service 4) Volume mounts and networking 5) Environment variable management 6) Development vs production variants","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"app_description","type":"text","label":"Opis aplikacji","defaultValue":"Node.js API with PostgreSQL and Redis"},{"name":"services","type":"text","label":"Potrzebne serwisy","defaultValue":"api, db, redis, nginx"},{"name":"environment","type":"text","label":"Środowisko","defaultValue":"production"}]'::jsonb,
 '## Role\nDevOps engineer specializing in containerization.\n\n## Application\n{{app_description}}\n\n## Task\nComplete docker-compose.yml with health checks, volumes, networking.',
 87, 22, true, 104),

('GitHub Actions CI/CD Pipeline',
 'Tworzy kompletny pipeline CI/CD z testami, budowaniem i wdrożeniem.',
 'coding', 'advanced',
 ARRAY['github-actions','ci-cd','devops','automation','testing'],
 '[{"id":"1","content":"You are a DevOps engineer specializing in GitHub Actions, CI/CD pipelines, and automated deployment strategies.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create a GitHub Actions CI/CD pipeline for:\n\nProject type: {{project_type}}\nDeployment target: {{deployment_target}}\nTests: {{test_framework}}\nBranch strategy: {{branch_strategy}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) CI workflow (lint, type-check, test, build) 2) CD workflow with environment gates 3) Caching for dependencies 4) Secrets management 5) Deployment rollback strategy 6) Notifications on failure","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"project_type","type":"text","label":"Typ projektu","defaultValue":"Node.js/TypeScript"},{"name":"deployment_target","type":"text","label":"Cel wdrożenia","defaultValue":"AWS ECS"},{"name":"test_framework","type":"text","label":"Framework testowy","defaultValue":"Vitest + Playwright"},{"name":"branch_strategy","type":"text","label":"Strategia branchy","defaultValue":"main → production, develop → staging"}]'::jsonb,
 '## Role\nDevOps engineer for GitHub Actions.\n\n## Project\n{{project_type}} deployed to {{deployment_target}}\n\n## Task\nComplete CI/CD with caching, gates, rollback, and notifications.',
 92, 35, true, 105),

('Unit Test Suite Generator',
 'Generuje kompletne zestawy testów jednostkowych dla funkcji i klas.',
 'coding', 'intermediate',
 ARRAY['testing','jest','vitest','unit-tests','tdd'],
 '[{"id":"1","content":"You are a test-driven development expert who writes comprehensive, maintainable unit tests following the AAA pattern (Arrange, Act, Assert).","order_index":0,"section_slug":"role"},{"id":"2","content":"Write unit tests for the following code:\n\n```{{language}}\n{{code}}\n```\n\nTest framework: {{framework}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Cover: 1) Happy path scenarios 2) Edge cases and boundary conditions 3) Error cases 4) Mock external dependencies 5) Test descriptions that document behavior 6) Aim for >90% coverage","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"code","type":"textarea","label":"Kod do przetestowania","defaultValue":""},{"name":"language","type":"text","label":"Język programowania","defaultValue":"typescript"},{"name":"framework","type":"text","label":"Framework testowy","defaultValue":"Vitest"}]'::jsonb,
 '## Role\nTDD expert writing comprehensive unit tests.\n\n## Code\n```{{language}}\n{{code}}\n```\n\n## Task\nFull test suite: happy path, edge cases, errors, mocks, >90% coverage.',
 89, 28, false, 106),

('GraphQL Schema Designer',
 'Projektuje schematy GraphQL z mutacjami, zapytaniami i subskrypcjami.',
 'coding', 'advanced',
 ARRAY['graphql','api-design','schema','backend'],
 '[{"id":"1","content":"You are a GraphQL architect with expertise in schema design, resolver patterns, and API performance optimization.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design a GraphQL schema for:\n\nDomain: {{domain}}\nEntities: {{entities}}\nRequirements: {{requirements}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Complete SDL schema 2) Query and Mutation definitions 3) Subscription events 4) Input types and enums 5) Pagination pattern (Relay cursor) 6) Error handling with union types 7) Example queries","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"domain","type":"text","label":"Domena aplikacji","defaultValue":"e-commerce platform"},{"name":"entities","type":"text","label":"Encje (lista)","defaultValue":"User, Product, Order, Review"},{"name":"requirements","type":"text","label":"Wymagania","defaultValue":"real-time order updates, pagination"}]'::jsonb,
 '## Role\nGraphQL architect.\n\n## Domain\n{{domain}} with entities: {{entities}}\n\n## Task\nComplete SDL schema with queries, mutations, subscriptions, pagination.',
 90, 19, false, 107),

('REST API Endpoint Designer',
 'Projektuje endpointy REST API zgodnie z najlepszymi praktykami.',
 'coding', 'intermediate',
 ARRAY['rest','api-design','backend','openapi'],
 '[{"id":"1","content":"You are a backend API architect who designs clean, RESTful APIs following Richardson Maturity Model level 3 and OpenAPI 3.0 standards.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design REST API endpoints for:\n\nResource: {{resource}}\nOperations needed: {{operations}}\nAuthentication: {{auth_method}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) URL structure with proper HTTP methods 2) Request/response schemas 3) Status codes for each scenario 4) Error response format 5) Pagination for list endpoints 6) OpenAPI 3.0 YAML snippet 7) Example curl commands","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"resource","type":"text","label":"Zasób API","defaultValue":"User profile management"},{"name":"operations","type":"text","label":"Operacje","defaultValue":"CRUD + avatar upload"},{"name":"auth_method","type":"text","label":"Autentykacja","defaultValue":"JWT Bearer token"}]'::jsonb,
 '## Role\nAPI architect following REST best practices.\n\n## Resource\n{{resource}}\n\n## Task\nEndpoints with schemas, status codes, errors, pagination, OpenAPI snippet.',
 87, 16, false, 108),

('Database Schema Generator',
 'Tworzy schematy baz danych z relacjami, indeksami i politykami RLS.',
 'coding', 'advanced',
 ARRAY['database','postgresql','schema','migrations','rls'],
 '[{"id":"1","content":"You are a database architect specializing in PostgreSQL schema design, normalization, indexing strategies, and Row Level Security.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design a database schema for:\n\nApplication: {{application}}\nKey entities: {{entities}}\nAccess patterns: {{access_patterns}}\nExpected scale: {{scale}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) CREATE TABLE statements with constraints 2) Foreign key relationships 3) Indexes optimized for access patterns 4) RLS policies for multi-tenant scenarios 5) Triggers for updated_at 6) Migration file structure","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"application","type":"text","label":"Nazwa aplikacji","defaultValue":"SaaS project management tool"},{"name":"entities","type":"text","label":"Encje","defaultValue":"User, Workspace, Project, Task, Comment"},{"name":"access_patterns","type":"textarea","label":"Wzorce dostępu","defaultValue":"Users access only their workspace data"},{"name":"scale","type":"text","label":"Skala","defaultValue":"100k users, 10M tasks"}]'::jsonb,
 '## Role\nDatabase architect.\n\n## Application\n{{application}}\n\n## Task\nCREATE TABLE, FK, indexes, RLS policies, triggers, migrations.',
 94, 27, true, 109),

('Code Security Audit',
 'Przeprowadza audyt bezpieczeństwa kodu identyfikując podatności OWASP.',
 'coding', 'advanced',
 ARRAY['security','owasp','code-review','vulnerability'],
 '[{"id":"1","content":"You are a senior application security engineer specializing in OWASP Top 10, secure coding practices, and vulnerability assessment.","order_index":0,"section_slug":"role"},{"id":"2","content":"Perform a security audit on the following code:\n\n```{{language}}\n{{code}}\n```","order_index":1,"section_slug":"context"},{"id":"3","content":"Identify: 1) OWASP Top 10 vulnerabilities 2) Injection risks (SQL, XSS, command) 3) Authentication/authorization flaws 4) Sensitive data exposure 5) Cryptographic weaknesses 6) Provide secure code alternatives for each finding","order_index":2,"section_slug":"task"},{"id":"4","content":"Format as: CRITICAL / HIGH / MEDIUM / LOW severity findings with CVSS score estimates and remediation code.","order_index":3,"section_slug":"format"}]'::jsonb,
 '[{"name":"code","type":"textarea","label":"Kod do audytu","defaultValue":""},{"name":"language","type":"text","label":"Język","defaultValue":"TypeScript/Node.js"}]'::jsonb,
 '## Role\nSecurity engineer — OWASP specialist.\n\n## Code\n```{{language}}\n{{code}}\n```\n\n## Task\nIdentify OWASP Top 10 vulnerabilities with CVSS scores and remediation.',
 95, 42, true, 110),

('Regex Pattern Generator',
 'Tworzy i tłumaczy wyrażenia regularne z przykładami testów.',
 'coding', 'intermediate',
 ARRAY['regex','patterns','validation','parsing'],
 '[{"id":"1","content":"You are a regex expert who writes precise, well-commented regular expressions for any text matching challenge.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create a regex pattern for:\n\nTask: {{task}}\nExample valid inputs: {{valid_examples}}\nExample invalid inputs: {{invalid_examples}}\nLanguage/flavor: {{language}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) The regex pattern with named groups 2) Step-by-step explanation of each component 3) Test cases (10 valid + 10 invalid) 4) Alternative patterns if multiple approaches exist 5) Performance considerations","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"task","type":"text","label":"Cel wyrażenia regularnego","defaultValue":"validate international phone numbers"},{"name":"valid_examples","type":"text","label":"Prawidłowe przykłady","defaultValue":"+1 (555) 123-4567, +44 20 7946 0958"},{"name":"invalid_examples","type":"text","label":"Nieprawidłowe przykłady","defaultValue":"555-CALL-NOW, 123"},{"name":"language","type":"text","label":"Język/środowisko","defaultValue":"JavaScript"}]'::jsonb,
 '## Role\nRegex expert.\n\n## Task\n{{task}}\n\n## Task\nPattern with named groups, explanation, test cases, alternatives.',
 86, 14, false, 111),

('Architecture Decision Record Writer',
 'Dokumentuje decyzje architektoniczne w standardowym formacie ADR.',
 'coding', 'advanced',
 ARRAY['architecture','documentation','adr','decision-making'],
 '[{"id":"1","content":"You are a software architect who writes clear Architecture Decision Records (ADRs) following the Nygard format, helping teams document and communicate technical decisions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Write an ADR for the following decision:\n\nDecision: {{decision}}\nContext: {{context}}\nOptions considered: {{options}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: Title, Status, Context, Decision, Rationale, Consequences (positive/negative), Alternatives rejected, and follow-up actions.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"decision","type":"text","label":"Decyzja architektoniczna","defaultValue":"Use event sourcing for order management"},{"name":"context","type":"textarea","label":"Kontekst problemu","defaultValue":""},{"name":"options","type":"text","label":"Rozważane opcje","defaultValue":"Event sourcing, CRUD with audit log, CQRS"}]'::jsonb,
 '## Role\nSoftware architect writing ADRs.\n\n## Decision\n{{decision}}\n\n## Task\nFull ADR: status, context, rationale, consequences, rejected alternatives.',
 88, 9, false, 112),

('Code Refactoring Assistant',
 'Refaktoryzuje kod poprawiając czytelność, wydajność i testowalność.',
 'coding', 'intermediate',
 ARRAY['refactoring','clean-code','patterns','solid'],
 '[{"id":"1","content":"You are a senior engineer who specializes in refactoring legacy code to improve maintainability, following SOLID principles and clean code practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Refactor the following code:\n\n```{{language}}\n{{code}}\n```\n\nPriority: {{priority}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Refactored code with comments explaining changes 2) Specific patterns applied (extract method, strategy, factory, etc.) 3) Before/after comparison 4) Test coverage improvements 5) What NOT to change and why","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"code","type":"textarea","label":"Kod do refaktoryzacji","defaultValue":""},{"name":"language","type":"text","label":"Język","defaultValue":"TypeScript"},{"name":"priority","type":"text","label":"Priorytet","defaultValue":"readability and testability"}]'::jsonb,
 '## Role\nRefactoring expert — SOLID principles.\n\n## Code\n```{{language}}\n{{code}}\n```\n\n## Task\nRefactored code with pattern names, before/after, test improvements.',
 87, 33, true, 113),

('API Integration Guide',
 'Tworzy kompletny przewodnik integracji z zewnętrznym API.',
 'coding', 'intermediate',
 ARRAY['api','integration','http','sdk'],
 '[{"id":"1","content":"You are an integration engineer who writes clear, production-ready code for connecting to third-party APIs with proper error handling and retry logic.","order_index":0,"section_slug":"role"},{"id":"2","content":"Write an integration guide for:\n\nAPI: {{api_name}}\nLanguage: {{language}}\nUse case: {{use_case}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Authentication setup 2) Base client with retry/backoff 3) Rate limiting handling 4) Webhook verification 5) Example for top 5 use cases 6) Error taxonomy 7) Testing with mocks","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"api_name","type":"text","label":"Nazwa API","defaultValue":"Stripe Payments API"},{"name":"language","type":"text","label":"Język/framework","defaultValue":"TypeScript/Node.js"},{"name":"use_case","type":"text","label":"Przypadek użycia","defaultValue":"process subscriptions and refunds"}]'::jsonb,
 '## Role\nIntegration engineer.\n\n## API\n{{api_name}} in {{language}}\n\n## Task\nAuth, retry logic, rate limits, webhooks, 5 use cases, error handling.',
 89, 21, true, 114),

('WebSocket Server Implementation',
 'Implementuje serwer WebSocket z obsługą pokojów i uwierzytelnianiem.',
 'coding', 'advanced',
 ARRAY['websocket','real-time','nodejs','socket-io'],
 '[{"id":"1","content":"You are a real-time systems engineer with expertise in WebSocket protocols, Socket.IO, and scalable event-driven architectures.","order_index":0,"section_slug":"role"},{"id":"2","content":"Implement a WebSocket server for:\n\nApplication: {{application}}\nFeatures: {{features}}\nScale requirement: {{scale}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Server setup with authentication middleware 2) Room management 3) Event broadcasting patterns 4) Reconnection handling 5) Redis adapter for horizontal scaling 6) Rate limiting per connection 7) Client implementation example","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"application","type":"text","label":"Typ aplikacji","defaultValue":"collaborative document editor"},{"name":"features","type":"text","label":"Funkcje","defaultValue":"real-time edits, presence, cursors"},{"name":"scale","type":"text","label":"Skala","defaultValue":"10k concurrent connections"}]'::jsonb,
 '## Role\nReal-time systems engineer.\n\n## Application\n{{application}}\n\n## Task\nWebSocket server with auth, rooms, Redis scaling, reconnection.',
 91, 17, false, 115),

('Microservices Architecture Designer',
 'Projektuje architekturę mikroserwisów z wzorcami komunikacji.',
 'coding', 'advanced',
 ARRAY['microservices','architecture','distributed-systems','kafka'],
 '[{"id":"1","content":"You are a distributed systems architect with expertise in microservices patterns, event-driven architecture, and service mesh.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design microservices architecture for:\n\nMonolith to decompose: {{monolith}}\nBoundaries: {{boundaries}}\nTraffic: {{traffic}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) Service boundaries (DDD bounded contexts) 2) Inter-service communication (sync REST vs async events) 3) Data ownership per service 4) API gateway design 5) Distributed tracing strategy 6) Saga pattern for transactions 7) Circuit breaker implementation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"monolith","type":"text","label":"Opis monolitu","defaultValue":"e-commerce platform"},{"name":"boundaries","type":"text","label":"Granice domenowe","defaultValue":"Users, Orders, Products, Payments, Notifications"},{"name":"traffic","type":"text","label":"Ruch","defaultValue":"1M requests/day, peak 10k rps"}]'::jsonb,
 '## Role\nDistributed systems architect.\n\n## System\n{{monolith}}\n\n## Task\nBounded contexts, communication patterns, sagas, circuit breakers.',
 93, 28, true, 116),

('OpenAPI Specification Writer',
 'Tworzy kompletną specyfikację OpenAPI 3.0 dla API.',
 'coding', 'intermediate',
 ARRAY['openapi','swagger','api-documentation','rest'],
 '[{"id":"1","content":"You are an API documentation specialist who writes comprehensive OpenAPI 3.0 specifications following best practices for developer experience.","order_index":0,"section_slug":"role"},{"id":"2","content":"Write an OpenAPI 3.0 spec for:\n\nAPI name: {{api_name}}\nEndpoints: {{endpoints}}\nAuth type: {{auth_type}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: Complete YAML with info, servers, paths, components/schemas, securitySchemes, examples for every endpoint, error responses, and pagination schemas.","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"api_name","type":"text","label":"Nazwa API","defaultValue":"User Management API"},{"name":"endpoints","type":"textarea","label":"Lista endpointów","defaultValue":"GET /users, POST /users, GET /users/{id}, PATCH /users/{id}, DELETE /users/{id}"},{"name":"auth_type","type":"text","label":"Typ autentykacji","defaultValue":"JWT Bearer"}]'::jsonb,
 '## Role\nAPI documentation specialist.\n\n## API\n{{api_name}}\n\n## Task\nComplete OpenAPI 3.0 YAML with schemas, examples, errors, pagination.',
 86, 15, false, 117),

('Performance Profiling Guide',
 'Diagnozuje wąskie gardła wydajności aplikacji i sugeruje optymalizacje.',
 'coding', 'advanced',
 ARRAY['performance','profiling','optimization','benchmark'],
 '[{"id":"1","content":"You are a performance engineer who diagnoses bottlenecks in web applications, databases, and Node.js backends using profiling tools and benchmarking.","order_index":0,"section_slug":"role"},{"id":"2","content":"Profile and optimize:\n\nApplication type: {{app_type}}\nSymptoms: {{symptoms}}\nStack: {{stack}}\nCurrent metrics: {{metrics}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Profiling approach and tools (Clinic.js, Chrome DevTools, pg_stat_statements) 2) Likely root causes 3) Measurement methodology 4) Optimization techniques specific to symptoms 5) Before/after benchmark template 6) Monitoring setup to prevent regression","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"app_type","type":"text","label":"Typ aplikacji","defaultValue":"Node.js REST API"},{"name":"symptoms","type":"text","label":"Objawy","defaultValue":"p99 latency > 2s, high CPU under load"},{"name":"stack","type":"text","label":"Stack technologiczny","defaultValue":"Node.js, PostgreSQL, Redis"},{"name":"metrics","type":"text","label":"Aktualne metryki","defaultValue":"500 rps, 2s p99, 80% CPU"}]'::jsonb,
 '## Role\nPerformance engineer.\n\n## Symptoms\n{{symptoms}} on {{stack}}\n\n## Task\nProfiling approach, root causes, optimizations, benchmark template.',
 92, 20, false, 118),

('Terraform Infrastructure Module',
 'Tworzy moduły Terraform dla infrastruktury chmurowej.',
 'coding', 'advanced',
 ARRAY['terraform','iac','aws','cloud','devops'],
 '[{"id":"1","content":"You are a cloud infrastructure engineer specializing in Terraform, AWS, and Infrastructure as Code best practices including state management and module design.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create Terraform configuration for:\n\nCloud provider: {{provider}}\nInfrastructure: {{infrastructure}}\nEnvironments: {{environments}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Module structure (main.tf, variables.tf, outputs.tf) 2) Remote state configuration 3) Environment-specific workspaces 4) Security groups and IAM roles 5) Tagging strategy 6) README with usage examples","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"provider","type":"text","label":"Dostawca chmury","defaultValue":"AWS"},{"name":"infrastructure","type":"text","label":"Infrastruktura","defaultValue":"ECS cluster with RDS, ElastiCache, ALB"},{"name":"environments","type":"text","label":"Środowiska","defaultValue":"dev, staging, production"}]'::jsonb,
 '## Role\nCloud infrastructure engineer.\n\n## Infrastructure\n{{infrastructure}} on {{provider}}\n\n## Task\nTerraform modules with state, IAM, security groups, workspaces.',
 90, 24, false, 119),

('Error Handling Strategy Designer',
 'Projektuje kompleksową strategię obsługi błędów dla aplikacji.',
 'coding', 'intermediate',
 ARRAY['error-handling','patterns','typescript','reliability'],
 '[{"id":"1","content":"You are a reliability engineer who designs robust error handling systems using typed errors, Result patterns, and observability best practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design error handling for:\n\nApplication type: {{app_type}}\nError categories: {{error_categories}}\nLanguage: {{language}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Error taxonomy with typed error classes 2) Result<T, E> pattern implementation 3) Global error handler for the framework 4) User-facing vs technical error messages 5) Error logging with context (request ID, user ID) 6) Retry logic for transient errors","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"app_type","type":"text","label":"Typ aplikacji","defaultValue":"REST API with Astro/Node.js"},{"name":"error_categories","type":"text","label":"Kategorie błędów","defaultValue":"validation, auth, database, external API, rate limit"},{"name":"language","type":"text","label":"Język","defaultValue":"TypeScript"}]'::jsonb,
 '## Role\nReliability engineer.\n\n## Application\n{{app_type}}\n\n## Task\nError taxonomy, Result<T,E>, global handler, logging, retry logic.',
 88, 19, false, 120),

('JWT Authentication Implementation',
 'Implementuje kompletny system autentykacji JWT z odświeżaniem tokenów.',
 'coding', 'intermediate',
 ARRAY['jwt','authentication','security','nodejs'],
 '[{"id":"1","content":"You are a security engineer specializing in authentication systems, JWT best practices, and session management.","order_index":0,"section_slug":"role"},{"id":"2","content":"Implement JWT authentication for:\n\nPlatform: {{platform}}\nRequirements: {{requirements}}\nStorage strategy: {{storage}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Token generation (access + refresh) 2) Middleware for route protection 3) Refresh token rotation 4) Token revocation strategy 5) Secure cookie vs localStorage trade-offs 6) CSRF protection 7) Example login/logout/refresh flows","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"platform","type":"text","label":"Platforma","defaultValue":"Node.js/Express"},{"name":"requirements","type":"text","label":"Wymagania","defaultValue":"15min access token, 7day refresh, remember me"},{"name":"storage","type":"text","label":"Przechowywanie tokenów","defaultValue":"httpOnly cookies"}]'::jsonb,
 '## Role\nSecurity engineer — JWT specialist.\n\n## Platform\n{{platform}}\n\n## Task\nAccess + refresh tokens, rotation, revocation, CSRF protection.',
 90, 38, true, 121),

('CLI Tool Generator',
 'Buduje narzędzia wiersza poleceń z interfejsem tekstowym.',
 'coding', 'intermediate',
 ARRAY['cli','nodejs','commander','ux'],
 '[{"id":"1","content":"You are a developer who builds intuitive CLI tools with great UX, using Node.js/TypeScript with interactive prompts and progress indicators.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build a CLI tool for:\n\nPurpose: {{purpose}}\nCommands: {{commands}}\nTarget users: {{users}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Command structure with subcommands 2) Interactive prompts (Inquirer) 3) Progress bars for long operations 4) Colored output with chalk 5) Config file support 6) --help documentation 7) Error messages that suggest fixes","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"purpose","type":"text","label":"Cel narzędzia","defaultValue":"deploy applications to multiple environments"},{"name":"commands","type":"text","label":"Komendy","defaultValue":"deploy, rollback, status, logs, config"},{"name":"users","type":"text","label":"Docelowi użytkownicy","defaultValue":"developers, DevOps engineers"}]'::jsonb,
 '## Role\nCLI tool developer.\n\n## Purpose\n{{purpose}}\n\n## Task\nSubcommands, Inquirer prompts, progress bars, chalk, --help docs.',
 85, 13, false, 122),

('Redis Caching Strategy',
 'Projektuje strategię cachowania Redis z TTL i wzorcami inwalidacji.',
 'coding', 'advanced',
 ARRAY['redis','caching','performance','backend'],
 '[{"id":"1","content":"You are a backend architect specializing in Redis caching strategies, cache invalidation patterns, and distributed caching at scale.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design Redis caching for:\n\nApplication: {{application}}\nData types: {{data_types}}\nConsistency requirement: {{consistency}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) Cache-aside vs write-through vs write-behind patterns 2) TTL strategy per data type 3) Cache key naming conventions 4) Invalidation on updates (pub/sub, event-driven) 5) Cache stampede prevention 6) Redis data structures selection 7) Monitoring (hit rate, eviction)","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"application","type":"text","label":"Aplikacja","defaultValue":"e-commerce product catalog API"},{"name":"data_types","type":"text","label":"Typy danych","defaultValue":"product listings, user sessions, rate limits"},{"name":"consistency","type":"text","label":"Wymagania spójności","defaultValue":"eventual consistency acceptable for products"}]'::jsonb,
 '## Role\nRedis caching architect.\n\n## Application\n{{application}}\n\n## Task\nCaching patterns, TTL, invalidation, stampede prevention, monitoring.',
 91, 22, false, 123),

('React Component Library Setup',
 'Konfiguruje bibliotekę komponentów React z Storybook i testami wizualnymi.',
 'coding', 'advanced',
 ARRAY['react','storybook','component-library','design-system'],
 '[{"id":"1","content":"You are a frontend architect who builds scalable React component libraries with Storybook, visual regression testing, and proper documentation.","order_index":0,"section_slug":"role"},{"id":"2","content":"Set up a component library for:\n\nDesign system: {{design_system}}\nComponents needed: {{components}}\nConsumers: {{consumers}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Monorepo structure (Turborepo) 2) Storybook configuration 3) Component template with variants prop pattern 4) CSS-in-JS vs Tailwind decision 5) Chromatic visual testing setup 6) NPM publishing workflow 7) Changelog automation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"design_system","type":"text","label":"System projektowania","defaultValue":"based on shadcn/ui with custom tokens"},{"name":"components","type":"text","label":"Komponenty","defaultValue":"Button, Input, Modal, Table, Toast"},{"name":"consumers","type":"text","label":"Konsumenci biblioteki","defaultValue":"3 internal React applications"}]'::jsonb,
 '## Role\nFrontend architect.\n\n## Design system\n{{design_system}}\n\n## Task\nMonorepo, Storybook, visual testing, Chromatic, NPM publishing.',
 89, 16, false, 124),

('Data Migration Script',
 'Tworzy bezpieczne skrypty migracji danych między schematami lub bazami.',
 'coding', 'advanced',
 ARRAY['migration','database','data-engineering','postgresql'],
 '[{"id":"1","content":"You are a data engineer who writes safe, idempotent data migration scripts with rollback capabilities and progress tracking.","order_index":0,"section_slug":"role"},{"id":"2","content":"Write a migration script for:\n\nSource: {{source}}\nTarget: {{target}}\nData volume: {{volume}}\nConstraints: {{constraints}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Pre-migration validation checks 2) Batched processing to avoid locks 3) Progress logging 4) Dry-run mode 5) Rollback mechanism 6) Post-migration verification queries 7) Estimated runtime calculation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"source","type":"text","label":"Źródło danych","defaultValue":"PostgreSQL v1 schema"},{"name":"target","type":"text","label":"Cel migracji","defaultValue":"PostgreSQL v2 schema with new columns"},{"name":"volume","type":"text","label":"Wolumen danych","defaultValue":"10M rows"},{"name":"constraints","type":"text","label":"Ograniczenia","defaultValue":"zero downtime, max 10min"}]'::jsonb,
 '## Role\nData engineer.\n\n## Migration\n{{source}} → {{target}}\n\n## Task\nIdempotent batched migration with dry-run, rollback, verification.',
 92, 18, false, 125),

('Accessibility Audit Tool',
 'Audytuje dostępność aplikacji webowej zgodnie z WCAG 2.1 AA.',
 'coding', 'intermediate',
 ARRAY['accessibility','wcag','a11y','testing'],
 '[{"id":"1","content":"You are an accessibility engineer with expertise in WCAG 2.1 AA standards, ARIA patterns, and assistive technology testing.","order_index":0,"section_slug":"role"},{"id":"2","content":"Audit accessibility for:\n\nComponent/page: {{component}}\nComponent code:\n```{{language}}\n{{code}}\n```","order_index":1,"section_slug":"context"},{"id":"3","content":"Check: 1) Keyboard navigation (tab order, focus management) 2) Screen reader announcements (ARIA labels, live regions) 3) Color contrast ratios 4) Touch target sizes 5) Motion/animation preferences 6) Provide fixed code for each violation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"component","type":"text","label":"Komponent/strona","defaultValue":"modal dialog component"},{"name":"code","type":"textarea","label":"Kod komponentu","defaultValue":""},{"name":"language","type":"text","label":"Język","defaultValue":"tsx"}]'::jsonb,
 '## Role\nAccessibility engineer — WCAG 2.1 AA.\n\n## Component\n{{component}}\n\n## Task\nKeyboard nav, ARIA, contrast, touch targets, motion, fixes.',
 88, 11, false, 126),

('Load Testing Script',
 'Pisze skrypty testów obciążeniowych z k6 lub Artillery.',
 'coding', 'advanced',
 ARRAY['load-testing','k6','performance','devops'],
 '[{"id":"1","content":"You are a performance testing engineer who writes realistic load test scenarios using k6, simulating real user behavior with proper assertions.","order_index":0,"section_slug":"role"},{"id":"2","content":"Write load tests for:\n\nAPI endpoint(s): {{endpoints}}\nAcceptance criteria: {{criteria}}\nLoad pattern: {{pattern}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Realistic think time between requests 2) Virtual user scenarios mirroring user journeys 3) Thresholds for p50/p95/p99 latency 4) Error rate thresholds 5) Ramp-up and spike test scenarios 6) Output report interpretation guide","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"endpoints","type":"text","label":"Testowane endpointy","defaultValue":"GET /api/products, POST /api/orders"},{"name":"criteria","type":"text","label":"Kryteria akceptacji","defaultValue":"p99 < 500ms at 1000 rps"},{"name":"pattern","type":"text","label":"Wzorzec obciążenia","defaultValue":"ramp 0→1000 users in 5min, hold 10min"}]'::jsonb,
 '## Role\nPerformance testing engineer with k6.\n\n## Endpoints\n{{endpoints}}\n\n## Task\nRealistic scenarios with thresholds, ramp-up, spike tests.',
 90, 14, false, 127),

('Nginx Configuration Generator',
 'Generuje konfigurację Nginx z SSL, proxy i optymalizacją.',
 'coding', 'intermediate',
 ARRAY['nginx','devops','ssl','reverse-proxy','security'],
 '[{"id":"1","content":"You are a systems engineer who configures Nginx for production with security hardening, SSL/TLS best practices, and performance optimization.","order_index":0,"section_slug":"role"},{"id":"2","content":"Configure Nginx for:\n\nApplication: {{application}}\nDomain: {{domain}}\nUpstreams: {{upstreams}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) SSL/TLS with Let''s Encrypt 2) HTTP/2 and HTTP/3 (QUIC) 3) Security headers (HSTS, CSP, X-Frame-Options) 4) Gzip/Brotli compression 5) Rate limiting 6) Upstream health checks 7) Caching for static assets","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"application","type":"text","label":"Typ aplikacji","defaultValue":"Node.js SPA + API"},{"name":"domain","type":"text","label":"Domena","defaultValue":"example.com"},{"name":"upstreams","type":"text","label":"Serwery upstream","defaultValue":"app:4321 (API), static files on /dist"}]'::jsonb,
 '## Role\nSystems engineer — Nginx specialist.\n\n## Application\n{{application}} on {{domain}}\n\n## Task\nSSL, HTTP/2, security headers, compression, rate limits, caching.',
 88, 19, false, 128),

('State Machine Designer',
 'Projektuje maszyny stanów dla złożonej logiki biznesowej.',
 'coding', 'advanced',
 ARRAY['state-machine','xstate','patterns','architecture'],
 '[{"id":"1","content":"You are a software architect who models complex business processes as finite state machines using XState, ensuring predictable and testable behavior.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design a state machine for:\n\nProcess: {{process}}\nStates: {{states}}\nActors involved: {{actors}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) State diagram description 2) XState v5 configuration 3) Guards and actions 4) Parallel states if needed 5) Actor model for sub-processes 6) Test cases for each transition 7) Visualization using Stately","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"process","type":"text","label":"Proces do modelowania","defaultValue":"payment checkout flow"},{"name":"states","type":"text","label":"Stany","defaultValue":"idle, cart, shipping, payment, confirming, success, failed"},{"name":"actors","type":"text","label":"Aktorzy","defaultValue":"user, payment gateway, inventory, email service"}]'::jsonb,
 '## Role\nXState state machine architect.\n\n## Process\n{{process}}\n\n## Task\nXState v5 config with guards, actors, parallel states, tests.',
 91, 15, false, 129),

('Python FastAPI Service',
 'Tworzy mikroserwis FastAPI z walidacją Pydantic i dokumentacją.',
 'coding', 'intermediate',
 ARRAY['python','fastapi','pydantic','microservice'],
 '[{"id":"1","content":"You are a Python backend developer who builds production-grade FastAPI services with Pydantic v2, async database access, and automatic OpenAPI docs.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build a FastAPI service for:\n\nService purpose: {{purpose}}\nEndpoints: {{endpoints}}\nDatabase: {{database}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Pydantic v2 models 2) Async SQLAlchemy or asyncpg 3) Dependency injection pattern 4) Background tasks 5) Middleware (CORS, logging, timing) 6) pytest fixtures and test examples 7) Dockerfile","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"purpose","type":"text","label":"Cel serwisu","defaultValue":"user profile management"},{"name":"endpoints","type":"text","label":"Endpointy","defaultValue":"CRUD for profiles, avatar upload"},{"name":"database","type":"text","label":"Baza danych","defaultValue":"PostgreSQL with asyncpg"}]'::jsonb,
 '## Role\nFastAPI Python developer.\n\n## Service\n{{purpose}}\n\n## Task\nPydantic v2, async DB, dependency injection, tests, Dockerfile.',
 88, 20, false, 130),

('Go REST Service',
 'Buduje wydajny serwis REST w Go z goroutines i testami.',
 'coding', 'advanced',
 ARRAY['golang','rest','backend','performance'],
 '[{"id":"1","content":"You are a Go developer who builds high-performance REST services using idiomatic Go patterns, goroutines, and the standard library plus minimal dependencies.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build a Go REST service for:\n\nPurpose: {{purpose}}\nEndpoints: {{endpoints}}\nConcurrency requirements: {{concurrency}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Clean architecture (handler/service/repository) 2) Context propagation and cancellation 3) Goroutine pool for concurrent operations 4) Graceful shutdown 5) Structured logging (slog) 6) Table-driven tests 7) Dockerized build","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"purpose","type":"text","label":"Cel serwisu","defaultValue":"high-throughput event ingestion API"},{"name":"endpoints","type":"text","label":"Endpointy","defaultValue":"POST /events, GET /events/{id}"},{"name":"concurrency","type":"text","label":"Wymagania współbieżności","defaultValue":"50k rps, goroutine pool"}]'::jsonb,
 '## Role\nGo developer — idiomatic patterns.\n\n## Service\n{{purpose}}\n\n## Task\nClean arch, goroutine pool, graceful shutdown, slog, tests.',
 91, 17, false, 131),

('React Server Component Designer',
 'Projektuje architekturę z React Server Components i Streaming.',
 'coding', 'advanced',
 ARRAY['react','rsc','streaming','next-js','performance'],
 '[{"id":"1","content":"You are a React architect specializing in React Server Components, Suspense streaming, and the data-fetching patterns that minimize client-side JavaScript.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design RSC architecture for:\n\nPage/feature: {{feature}}\nData requirements: {{data}}\nInteractivity: {{interactivity}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) Component tree split (server vs client) 2) Streaming boundaries with Suspense 3) Loading skeletons 4) Error boundaries 5) Data fetching colocation 6) Cache strategies (fetch cache, unstable_cache) 7) Trade-offs vs traditional SPA","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"feature","type":"text","label":"Strona/funkcja","defaultValue":"dashboard with analytics charts"},{"name":"data","type":"text","label":"Dane","defaultValue":"user stats, recent activity, recommendations"},{"name":"interactivity","type":"text","label":"Interaktywność","defaultValue":"filters, date picker, export"}]'::jsonb,
 '## Role\nRSC architect.\n\n## Feature\n{{feature}}\n\n## Task\nServer/client split, Suspense streaming, cache strategies.',
 92, 23, false, 132),

('Vue 3 Composable Designer',
 'Tworzy reużywalne composables Vue 3 z Composition API.',
 'coding', 'intermediate',
 ARRAY['vue','composables','composition-api','typescript'],
 '[{"id":"1","content":"You are a Vue 3 developer who creates elegant composables using Composition API, following the VueUse patterns and TypeScript best practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create a Vue 3 composable for:\n\nFeature: {{feature}}\nReactivity needs: {{reactivity}}\nSide effects: {{side_effects}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) TypeScript generics 2) Reactive state with ref/reactive 3) Computed properties 4) Lifecycle hooks 5) Cleanup on unmount 6) Server-side rendering compatibility 7) VueUse integration where appropriate","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"feature","type":"text","label":"Funkcjonalność","defaultValue":"infinite scroll with intersection observer"},{"name":"reactivity","type":"text","label":"Reaktywność","defaultValue":"items list, loading, hasMore"},{"name":"side_effects","type":"text","label":"Efekty uboczne","defaultValue":"API calls, IntersectionObserver cleanup"}]'::jsonb,
 '## Role\nVue 3 Composition API expert.\n\n## Feature\n{{feature}}\n\n## Task\nComposable with TypeScript, cleanup, SSR compat, VueUse.',
 86, 12, false, 133),

('Kubernetes Deployment Designer',
 'Tworzy manifesty Kubernetes dla aplikacji produkcyjnych.',
 'coding', 'advanced',
 ARRAY['kubernetes','k8s','devops','infrastructure','containers'],
 '[{"id":"1","content":"You are a Kubernetes engineer who writes production-grade manifests with proper resource limits, health checks, and rolling deployment strategies.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create Kubernetes manifests for:\n\nApplication: {{application}}\nResources: {{resources}}\nHA requirements: {{ha}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Deployment with resource requests/limits 2) HorizontalPodAutoscaler 3) PodDisruptionBudget 4) ConfigMap and Secret management 5) Liveness/readiness/startup probes 6) Network policies 7) Ingress with TLS","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"application","type":"text","label":"Aplikacja","defaultValue":"Node.js API with Redis sidecar"},{"name":"resources","type":"text","label":"Zasoby","defaultValue":"200m CPU, 256Mi RAM per pod"},{"name":"ha","type":"text","label":"Wymagania HA","defaultValue":"min 3 replicas, zero-downtime deploys"}]'::jsonb,
 '## Role\nKubernetes engineer.\n\n## Application\n{{application}}\n\n## Task\nDeployment, HPA, PDB, probes, network policies, Ingress TLS.',
 93, 26, true, 134),

('Event-Driven Architecture Designer',
 'Projektuje systemy oparte na zdarzeniach z Kafka lub RabbitMQ.',
 'coding', 'advanced',
 ARRAY['event-driven','kafka','rabbitmq','architecture','microservices'],
 '[{"id":"1","content":"You are an event-driven systems architect with deep expertise in Kafka, event sourcing, CQRS, and reliable message processing patterns.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design event-driven architecture for:\n\nDomain: {{domain}}\nEvents: {{events}}\nConsumers: {{consumers}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) Event schema with CloudEvents standard 2) Topic/exchange design 3) Consumer group strategy 4) Dead letter queue handling 5) Exactly-once vs at-least-once trade-offs 6) Event versioning strategy 7) Outbox pattern for reliability","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"domain","type":"text","label":"Domena","defaultValue":"e-commerce order processing"},{"name":"events","type":"text","label":"Zdarzenia","defaultValue":"OrderPlaced, PaymentProcessed, InventoryReserved, OrderShipped"},{"name":"consumers","type":"text","label":"Konsumenci","defaultValue":"inventory, notifications, analytics, fulfillment"}]'::jsonb,
 '## Role\nEvent-driven architect.\n\n## Domain\n{{domain}}\n\n## Task\nCloudEvents schema, topics, DLQ, exactly-once, outbox pattern.',
 94, 19, false, 135),

('Swift iOS Feature Developer',
 'Implementuje funkcje iOS w Swift z SwiftUI i async/await.',
 'coding', 'intermediate',
 ARRAY['swift','ios','swiftui','mobile'],
 '[{"id":"1","content":"You are a senior iOS developer who builds modern SwiftUI features with Swift Concurrency, Combine, and clean MVVM architecture.","order_index":0,"section_slug":"role"},{"id":"2","content":"Implement iOS feature:\n\nFeature: {{feature}}\nMinimum iOS version: {{ios_version}}\nData layer: {{data_layer}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) SwiftUI view hierarchy 2) ViewModel with @Observable 3) async/await data fetching 4) Error handling with user-friendly alerts 5) Accessibility modifiers 6) Preview providers 7) Unit tests for ViewModel","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"feature","type":"text","label":"Funkcja iOS","defaultValue":"user profile with photo upload"},{"name":"ios_version","type":"text","label":"Minimalna wersja iOS","defaultValue":"iOS 17"},{"name":"data_layer","type":"text","label":"Warstwa danych","defaultValue":"REST API + CoreData cache"}]'::jsonb,
 '## Role\nSenior iOS developer — SwiftUI.\n\n## Feature\n{{feature}}\n\n## Task\n@Observable ViewModel, async/await, accessibility, tests.',
 87, 13, false, 136),

('Kotlin Android Feature',
 'Tworzy funkcje Android w Kotlin z Jetpack Compose.',
 'coding', 'intermediate',
 ARRAY['kotlin','android','jetpack-compose','mobile'],
 '[{"id":"1","content":"You are a senior Android developer who builds modern apps with Jetpack Compose, Kotlin Coroutines, and Clean Architecture.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build Android feature:\n\nFeature: {{feature}}\nTarget SDK: {{sdk}}\nArchitecture: {{architecture}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Composable functions with proper state hoisting 2) ViewModel with StateFlow 3) Hilt dependency injection 4) Room database if needed 5) Coroutines for async operations 6) Material 3 components 7) UI tests with Compose Testing","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"feature","type":"text","label":"Funkcja Android","defaultValue":"news feed with pagination"},{"name":"sdk","type":"text","label":"Target SDK","defaultValue":"API 34 (Android 14)"},{"name":"architecture","type":"text","label":"Architektura","defaultValue":"MVVM + Clean Architecture"}]'::jsonb,
 '## Role\nAndroid developer — Jetpack Compose.\n\n## Feature\n{{feature}}\n\n## Task\nStateFlow, Hilt, Room, Coroutines, Material 3, UI tests.',
 86, 11, false, 137),

('Chrome Extension Builder',
 'Buduje rozszerzenia Chrome z Manifest V3.',
 'coding', 'intermediate',
 ARRAY['chrome-extension','manifest-v3','javascript','browser'],
 '[{"id":"1","content":"You are a browser extension developer who builds Chrome extensions using Manifest V3, following Chrome Web Store policies and performance best practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build a Chrome extension for:\n\nPurpose: {{purpose}}\nPermissions needed: {{permissions}}\nUI type: {{ui_type}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) manifest.json (MV3) 2) Service worker background script 3) Content script with message passing 4) Popup UI 5) Storage with chrome.storage.sync 6) CSP compliance 7) Privacy-preserving data handling","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"purpose","type":"text","label":"Cel rozszerzenia","defaultValue":"save highlighted text to Notion"},{"name":"permissions","type":"text","label":"Uprawnienia","defaultValue":"storage, activeTab, contextMenus"},{"name":"ui_type","type":"text","label":"Typ interfejsu","defaultValue":"popup + context menu"}]'::jsonb,
 '## Role\nChrome extension developer — MV3.\n\n## Purpose\n{{purpose}}\n\n## Task\nManifest V3, service worker, content scripts, message passing.',
 85, 16, false, 138),

('Next.js App Router Page',
 'Tworzy strony Next.js z App Router, Server Actions i optymalizacją.',
 'coding', 'intermediate',
 ARRAY['next-js','app-router','react','server-actions'],
 '[{"id":"1","content":"You are a Next.js developer who builds optimized pages with App Router, leveraging Server Components, Server Actions, and Partial Prerendering.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build Next.js page for:\n\nPage: {{page}}\nData requirements: {{data}}\nInteractivity: {{interactivity}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Implement: 1) Page component with metadata generation 2) Server Component data fetching with caching 3) Server Actions for mutations 4) useFormState for form feedback 5) Loading.tsx and Error.tsx 6) Route segment config for caching 7) Open Graph image generation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"page","type":"text","label":"Strona","defaultValue":"product detail page with reviews"},{"name":"data","type":"text","label":"Dane","defaultValue":"product info, reviews, related products"},{"name":"interactivity","type":"text","label":"Interaktywność","defaultValue":"add to cart, submit review, image gallery"}]'::jsonb,
 '## Role\nNext.js App Router developer.\n\n## Page\n{{page}}\n\n## Task\nServer Components, Server Actions, caching, OG image.',
 89, 21, false, 139),

('OAuth 2.0 Provider Integration',
 'Integruje OAuth 2.0 z dowolnym dostawcą tożsamości.',
 'coding', 'advanced',
 ARRAY['oauth','security','authentication','identity'],
 '[{"id":"1","content":"You are a security engineer specializing in OAuth 2.0, OIDC, and identity provider integrations with deep knowledge of security vulnerabilities in auth flows.","order_index":0,"section_slug":"role"},{"id":"2","content":"Implement OAuth 2.0 integration with:\n\nProvider: {{provider}}\nFlow type: {{flow}}\nPlatform: {{platform}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Implement: 1) Authorization Code Flow with PKCE 2) State parameter for CSRF prevention 3) Token storage (server-side session) 4) Token refresh logic 5) Scope management 6) Error handling for each OAuth error 7) Logout with token revocation","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"provider","type":"text","label":"Dostawca OAuth","defaultValue":"Google"},{"name":"flow","type":"text","label":"Typ przepływu","defaultValue":"Authorization Code with PKCE"},{"name":"platform","type":"text","label":"Platforma","defaultValue":"Node.js with Astro SSR"}]'::jsonb,
 '## Role\nOAuth security engineer.\n\n## Provider\n{{provider}}\n\n## Task\nPKCE, CSRF state, server session, refresh, revocation.',
 92, 24, false, 140),

('Svelte Component Creator',
 'Tworzy komponenty Svelte 5 z nową składnią Runes.',
 'coding', 'intermediate',
 ARRAY['svelte','runes','frontend','javascript'],
 '[{"id":"1","content":"You are a Svelte 5 developer who creates elegant components using Runes syntax ($state, $derived, $effect) and SvelteKit best practices.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create Svelte 5 component for:\n\nComponent: {{component}}\nState requirements: {{state}}\nParent communication: {{communication}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) $state and $derived runes 2) $props with proper TypeScript types 3) $effect for side effects with cleanup 4) Transitions and animations 5) Accessible markup 6) Component tests with @testing-library/svelte","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"component","type":"text","label":"Komponent","defaultValue":"autocomplete search input"},{"name":"state","type":"text","label":"Stan","defaultValue":"query, results, loading, selected"},{"name":"communication","type":"text","label":"Komunikacja z rodzicem","defaultValue":"onSelect callback, onSearch event"}]'::jsonb,
 '## Role\nSvelte 5 developer — Runes.\n\n## Component\n{{component}}\n\n## Task\n$state, $derived, $effect, transitions, accessibility, tests.',
 85, 10, false, 141),

('Rust CLI Application',
 'Buduje aplikacje CLI w Rust z clap i obsługą błędów.',
 'coding', 'advanced',
 ARRAY['rust','cli','systems-programming','performance'],
 '[{"id":"1","content":"You are a Rust developer who builds fast, memory-safe CLI applications using idiomatic Rust with proper error handling using thiserror/anyhow.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build Rust CLI application for:\n\nPurpose: {{purpose}}\nCommands: {{commands}}\nPerformance requirements: {{performance}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) clap v4 derive macros for CLI 2) Custom error types with thiserror 3) Async with Tokio where needed 4) Rayon for parallel processing 5) Progress bars with indicatif 6) Config file with serde 7) Integration tests","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"purpose","type":"text","label":"Cel aplikacji","defaultValue":"parallel file processing and transformation"},{"name":"commands","type":"text","label":"Komendy","defaultValue":"process, validate, report"},{"name":"performance","type":"text","label":"Wymagania wydajnościowe","defaultValue":"process 1M files in < 60s"}]'::jsonb,
 '## Role\nRust CLI developer.\n\n## Purpose\n{{purpose}}\n\n## Task\nclap v4, thiserror, Tokio, Rayon, indicatif, serde config.',
 90, 14, false, 142),

('Angular Service & DI',
 'Tworzy serwisy Angular z Dependency Injection i RxJS.',
 'coding', 'intermediate',
 ARRAY['angular','rxjs','dependency-injection','typescript'],
 '[{"id":"1","content":"You are an Angular developer who builds well-structured services using dependency injection, RxJS operators, and Angular signals.","order_index":0,"section_slug":"role"},{"id":"2","content":"Create Angular service for:\n\nService purpose: {{purpose}}\nState management: {{state}}\nExternal dependencies: {{dependencies}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Injectable service with providedIn strategy 2) RxJS BehaviorSubject for state 3) Angular signals for synchronous state 4) HTTP interceptor for auth 5) Error handling with catchError 6) Unit tests with TestBed 7) Mock provider for testing","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"purpose","type":"text","label":"Cel serwisu","defaultValue":"product catalog with filtering and sorting"},{"name":"state","type":"text","label":"Zarządzanie stanem","defaultValue":"products list, filters, pagination, loading"},{"name":"dependencies","type":"text","label":"Zależności","defaultValue":"HttpClient, Router, AuthService"}]'::jsonb,
 '## Role\nAngular service architect.\n\n## Service\n{{purpose}}\n\n## Task\nDI, RxJS, signals, HTTP interceptor, TestBed tests.',
 86, 11, false, 143),

('Prisma ORM Schema Designer',
 'Projektuje schematy Prisma z relacjami i migracjami.',
 'coding', 'intermediate',
 ARRAY['prisma','orm','database','typescript'],
 '[{"id":"1","content":"You are a backend developer who designs Prisma schemas with complex relations, custom types, and performance-optimized queries.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design Prisma schema for:\n\nApplication: {{application}}\nModels: {{models}}\nRelations: {{relations}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Complete schema.prisma with all models 2) Proper relation fields and @relation 3) Indexes for common queries 4) Enums for status fields 5) Generated migration SQL 6) Type-safe query examples 7) Select optimization to avoid N+1","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"application","type":"text","label":"Aplikacja","defaultValue":"multi-tenant SaaS"},{"name":"models","type":"text","label":"Modele","defaultValue":"User, Organization, Project, Task, Comment, Attachment"},{"name":"relations","type":"text","label":"Relacje","defaultValue":"User belongs to many Organizations, Organization has many Projects"}]'::jsonb,
 '## Role\nPrisma schema designer.\n\n## Application\n{{application}}\n\n## Task\nschema.prisma with relations, indexes, enums, N+1 prevention.',
 88, 22, false, 144),

('tRPC API Designer',
 'Projektuje type-safe API z tRPC i Zod walidacją.',
 'coding', 'advanced',
 ARRAY['trpc','typescript','api','zod','full-stack'],
 '[{"id":"1","content":"You are a full-stack TypeScript developer who builds end-to-end type-safe APIs with tRPC, sharing types between client and server automatically.","order_index":0,"section_slug":"role"},{"id":"2","content":"Design tRPC API for:\n\nFeature: {{feature}}\nProcedures needed: {{procedures}}\nAuth requirement: {{auth}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Provide: 1) Router definition with queries and mutations 2) Zod input schemas 3) Protected procedure middleware 4) Context setup with session 5) Client setup in Next.js/React 6) Optimistic updates example 7) Error handling with TRPCError","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"feature","type":"text","label":"Funkcja","defaultValue":"blog post management with comments"},{"name":"procedures","type":"text","label":"Procedury","defaultValue":"getPosts, getPost, createPost, updatePost, deletePost, addComment"},{"name":"auth","type":"text","label":"Autentykacja","defaultValue":"authenticated mutations, public queries"}]'::jsonb,
 '## Role\nFull-stack tRPC developer.\n\n## Feature\n{{feature}}\n\n## Task\nRouter, Zod schemas, protected procedures, optimistic updates.',
 91, 18, false, 145),

('Web Scraper Builder',
 'Buduje scrapery webowe z Playwright lub Puppeteer.',
 'coding', 'intermediate',
 ARRAY['web-scraping','playwright','nodejs','data-extraction'],
 '[{"id":"1","content":"You are a web automation engineer who builds reliable scrapers using Playwright, handling dynamic content, anti-bot measures, and data storage.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build a web scraper for:\n\nTarget site type: {{target}}\nData to extract: {{data}}\nScale: {{scale}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) Playwright browser setup with stealth 2) Selector strategies (CSS, XPath, text) 3) Pagination handling 4) Retry logic for flaky elements 5) Rate limiting to respect robots.txt 6) Data storage (JSON/CSV/DB) 7) Scheduled runs with cron","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"target","type":"text","label":"Typ docelowej strony","defaultValue":"e-commerce product listings"},{"name":"data","type":"text","label":"Dane do pobrania","defaultValue":"product name, price, rating, availability"},{"name":"scale","type":"text","label":"Skala","defaultValue":"1000 products/hour"}]'::jsonb,
 '## Role\nPlaywright scraper engineer.\n\n## Target\n{{target}}\n\n## Task\nStealth browser, selectors, pagination, retry, rate limiting.',
 84, 20, false, 146),

('Monorepo Setup Guide',
 'Konfiguruje monorepo z Turborepo lub Nx dla dużych projektów.',
 'coding', 'advanced',
 ARRAY['monorepo','turborepo','nx','architecture','npm-workspaces'],
 '[{"id":"1","content":"You are a frontend architect who sets up and optimizes monorepos with Turborepo, managing shared packages, build pipelines, and developer experience.","order_index":0,"section_slug":"role"},{"id":"2","content":"Set up monorepo for:\n\nApps: {{apps}}\nShared packages: {{packages}}\nCI requirements: {{ci}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Define: 1) Workspace structure (apps/, packages/) 2) turbo.json pipeline configuration 3) Shared TypeScript config 4) Shared ESLint and Prettier 5) Changesets for versioning 6) Affected-only builds in CI 7) Remote caching setup","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"apps","type":"text","label":"Aplikacje","defaultValue":"web (Next.js), mobile (Expo), admin (Vite)"},{"name":"packages","type":"text","label":"Paczki współdzielone","defaultValue":"ui, utils, types, config, api-client"},{"name":"ci","type":"text","label":"Wymagania CI","defaultValue":"affected-only builds, remote cache"}]'::jsonb,
 '## Role\nMonorepo architect — Turborepo.\n\n## Apps\n{{apps}}\n\n## Task\nturbo.json, shared configs, Changesets, affected builds, remote cache.',
 89, 17, false, 147),

('Webhook Handler Implementation',
 'Implementuje bezpieczny handler webhooka z weryfikacją podpisu.',
 'coding', 'intermediate',
 ARRAY['webhook','security','backend','events'],
 '[{"id":"1","content":"You are a backend engineer who implements secure webhook handlers with signature verification, idempotency, and reliable event processing.","order_index":0,"section_slug":"role"},{"id":"2","content":"Implement webhook handler for:\n\nService: {{service}}\nEvents to handle: {{events}}\nPlatform: {{platform}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Include: 1) HMAC signature verification 2) Idempotency key handling 3) Async processing with queue 4) Retry logic for failed processing 5) Event versioning handling 6) Dead letter queue 7) Monitoring and alerting","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"service","type":"text","label":"Serwis wysyłający webhooki","defaultValue":"Stripe"},{"name":"events","type":"text","label":"Obsługiwane zdarzenia","defaultValue":"payment_intent.succeeded, customer.subscription.updated, invoice.payment_failed"},{"name":"platform","type":"text","label":"Platforma","defaultValue":"Node.js/Express"}]'::jsonb,
 '## Role\nWebhook security engineer.\n\n## Service\n{{service}}\n\n## Task\nHMAC verification, idempotency, queue processing, DLQ.',
 90, 25, false, 148),

('Background Job Processor',
 'Implementuje system przetwarzania zadań w tle z kolejkami.',
 'coding', 'intermediate',
 ARRAY['background-jobs','bull','queues','nodejs','redis'],
 '[{"id":"1","content":"You are a backend engineer specializing in job queue systems, building reliable background processors with BullMQ and Redis.","order_index":0,"section_slug":"role"},{"id":"2","content":"Build job processing system for:\n\nJob types: {{job_types}}\nVolume: {{volume}}\nPrioritization: {{priority}}","order_index":1,"section_slug":"context"},{"id":"3","content":"Implement: 1) BullMQ queue setup 2) Worker with concurrency control 3) Job retry with exponential backoff 4) Priority queues 5) Cron job scheduling 6) Job progress reporting 7) Dashboard with Bull Board 8) Graceful shutdown","order_index":2,"section_slug":"task"}]'::jsonb,
 '[{"name":"job_types","type":"text","label":"Typy zadań","defaultValue":"email sending, PDF generation, image processing, data export"},{"name":"volume","type":"text","label":"Wolumen","defaultValue":"10k jobs/hour"},{"name":"priority","type":"text","label":"Priorytety","defaultValue":"critical (email), normal (PDF), low (export)"}]'::jsonb,
 '## Role\nBullMQ job queue engineer.\n\n## Jobs\n{{job_types}}\n\n## Task\nBullMQ workers, retry backoff, priorities, cron, dashboard.',
 88, 16, false, 149);
